// derived_facts_test.go is layer 1's answer to a finding class that regenerates
// every release: PROSE THAT RESTATES A NUMBER THE TREE ALREADY DERIVES.
//
// WHY THIS FILE EXISTS. The v0.5.2 reading gate ran four rounds — 39, 31, 24, 18
// findings — and the curve decayed without converging. Part of the reason is
// that a whole class of finding is manufactured fresh by every release: a
// sentence, a table row or a count typed by hand that duplicates something
// surface.json already extracts mechanically. Two of them failed inside v0.5.2
// alone:
//
//   - The site's "26 -> 19: what was cut, and where it went" table enumerated
//     TWELVE retired commands. The binary retires SIXTEEN. `lock`, `unlock`,
//     `reaudit` and `flag` were missing, and all four were real top-level
//     commands before v0.3.0 folded them under the claim noun — v0.2.0's
//     root.AddCommand registers newLockCmd, newUnlockCmd, newReauditCmd and
//     newFlagCmd. So an agent that learned the old CLI and reaches for one of
//     them gets a correct answer from the binary and no answer from the one
//     page written to catch exactly that reader.
//   - docs/RELEASING.md's "FIVE pins across FOUR files" sentence, which its own
//     surrounding paragraph admits "has now gone stale twice".
//
// A reading agent can catch either one, but only at release time, only if the
// bundle happened to carry both documents, and only by spending a round. A test
// catches both on every push, for free, and cannot forget.
//
// WHAT MAKES THIS SOUND. surface.json is not a document somebody maintains: it
// is regenerated by cmd/dossierx/surface_test.go's TestGenerateSurfaceJSON and
// compared byte for byte against the committed copy, so a surface change that
// was not regenerated is already a red build. That is what makes it usable here
// as the derived side of a comparison — the prose is checked against a fact, not
// against another piece of prose.
//
// C4 AND C5 WERE ADDED WHEN THIS FILE WAS BROUGHT OVER FROM THE RELEASE BRANCH,
// because the original three checks share a conspicuous gap. surface.json's
// `version_pins` already sweeps the tree for every release-version pin — the
// sweep is how three pin sites the hand-list had missed were found at all — and
// then NOTHING COMPARES THE PINS TO THE VERSION BEING RELEASED. The inventory
// made a stale pin visible and stopped one comparison short of making it a red
// build: C2 checks that the pin PARAGRAPH matches the sweep, C3 that the sweep
// the document prints is the sweep the code runs, and no check said "and every
// pin is the release this tree declares". C4 is that comparison. C5 is the same
// idea for README's counted surface claims ("19 commands under 7 nouns"), which
// the site's meta description has already demonstrated the failure mode for —
// it advertised a 20-command CLI for two minor releases because it was "the one
// count on the page that nothing derives".
//
// WHAT THIS CANNOT REACH. Prose that makes a judgement rather than states a
// number. Most of FORMAT.md is judgement, and no check here pretends otherwise.
// A derived check inherits surface.json's blind spots; it does not invent
// coverage.
package tests

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// the derived side
// ---------------------------------------------------------------------------

// surfacePinsAndRetired reads the two mechanically derived facts the original
// three checks compare prose against.
//
// Unreadable or empty is FATAL rather than skipped. A cross-check that quietly
// passed because surface.json moved or failed to parse would be a pass over zero
// assertions, which is the shape CLAUDE.md refuses by name.
func surfacePinsAndRetired(t *testing.T) (retired []string, pins []struct{ File, Pin, Version string }) {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "surface.json"))
	if err != nil {
		t.Fatalf("read surface.json, the derived side of every comparison in this file: %v", err)
	}
	var doc struct {
		Retired     []string `json:"retired"`
		VersionPins []struct {
			File    string `json:"file"`
			Pin     string `json:"pin"`
			Version string `json:"version"`
		} `json:"version_pins"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode surface.json: %v", err)
	}
	if len(doc.Retired) == 0 {
		t.Fatal("surface.json carries no `retired` entries, so the site comparison would run over an empty set and pass having asserted nothing")
	}
	if len(doc.VersionPins) == 0 {
		t.Fatal("surface.json carries no `version_pins` entries, so the pin-count comparison would run over an empty set and pass having asserted nothing")
	}

	for _, p := range doc.VersionPins {
		pins = append(pins, struct{ File, Pin, Version string }{p.File, p.Pin, p.Version})
	}
	return doc.Retired, pins
}

// surfaceCountsInventory reads surface.json's `counts` block — the mechanically
// derived answer to "how many commands / nouns / error codes / lint rules /
// HTTP routes does this binary ship". Empty or unreadable is fatal for the same
// reason as above: C5 comparing README against an empty map would pass having
// asserted nothing.
func surfaceCountsInventory(t *testing.T) map[string]int {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "surface.json"))
	if err != nil {
		t.Fatalf("read surface.json, the derived side of the counted-claims comparison: %v", err)
	}
	var doc struct {
		Counts map[string]int `json:"counts"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode surface.json: %v", err)
	}
	if len(doc.Counts) == 0 {
		t.Fatal("surface.json carries no `counts` block, so the README counted-claims comparison would run over an empty map and pass having asserted nothing")
	}
	return doc.Counts
}

// proseNumber resolves a counted token as documents in this repository spell
// them: digits ("19"), or the number words used for small counts, in either
// case ("Nineteen", "SEVEN"). A token that resolves as neither is a FAILED
// LOOKUP, not a skipped assertion — the caller fatals, because a count this
// file cannot read is a count it silently stopped checking.
func proseNumber(token string) (int, bool) {
	if n, err := strconv.Atoi(token); err == nil {
		return n, true
	}
	words := map[string]int{
		"ONE": 1, "TWO": 2, "THREE": 3, "FOUR": 4, "FIVE": 5, "SIX": 6,
		"SEVEN": 7, "EIGHT": 8, "NINE": 9, "TEN": 10, "ELEVEN": 11,
		"TWELVE": 12, "THIRTEEN": 13, "FOURTEEN": 14, "FIFTEEN": 15,
		"SIXTEEN": 16, "SEVENTEEN": 17, "EIGHTEEN": 18, "NINETEEN": 19,
		"TWENTY": 20,
	}
	upper := strings.ToUpper(token)
	if n, ok := words[upper]; ok {
		return n, true
	}
	// Composites for the twenties ("twenty-six"), which the site's history prose
	// uses; supported so that a future README sentence using one is read rather
	// than fataled on.
	if rest, found := strings.CutPrefix(upper, "TWENTY-"); found {
		if n, ok := words[rest]; ok && n < 10 {
			return 20 + n, true
		}
	}
	return 0, false
}

// ---------------------------------------------------------------------------
// C1 — the site's migration table against the binary's retired set
// ---------------------------------------------------------------------------

// siteAddedMarker is the one `cut:` value in the migration table that names no
// retired command. The table's last row inverts the columns to list what v0.3.0
// ADDED, and this string sits in the `cut` position to label it. It is skipped
// by name rather than by a heuristic, so a real command that ever looked like a
// marker could not slip through the same door.
const siteAddedMarker = "— added —"

// siteCutRe extracts the `cut:` cell of every row in site/src/content.ts's
// migration table. Every occurrence of `cut:` in that file belongs to that table
// — deliberately not written as a number, in a file whose whole subject is
// hand-typed counts going stale: the first draft said "all eight", and the same
// commit added a ninth row. If a second table ever adopts the key, what notices
// is the unknown-token error below, which fires on any cell naming something
// `surface.json` does not retire.
var siteCutRe = regexp.MustCompile(`cut: "([^"]*)"`)

func TestTheSiteAccountsForEveryRetiredCommand(t *testing.T) {
	retired, _ := surfacePinsAndRetired(t)
	content := readRepoFile(t, "site/src/content.ts")

	if !strings.Contains(content, "migration: {") {
		t.Fatal("site/src/content.ts no longer declares a `migration:` block, so the retired-command table this test reads has moved or gone. That is not a smaller check, it is a check with no subject")
	}

	matches := siteCutRe.FindAllStringSubmatch(content, -1)
	if len(matches) == 0 {
		t.Fatal("site/src/content.ts declares `migration:` but no `cut:` cells were extracted, so the table is unreadable to this test")
	}

	// Longest-prefix mapping, not equality: a cell says "implink status" or
	// "migrate --adopt" because the site names the invocation a reader typed,
	// while surface.json names the command. Longest match so that a future
	// retired name which is a prefix of another cannot silently absorb it.
	onSite := map[string]string{} // retired name -> the cell it was found in
	for _, m := range matches {
		for _, token := range strings.Split(m[1], "·") {
			token = strings.TrimSpace(token)
			if token == "" || token == siteAddedMarker {
				continue
			}
			best := ""
			for _, name := range retired {
				if token != name && !strings.HasPrefix(token, name+" ") {
					continue
				}
				if len(name) > len(best) {
					best = name
				}
			}
			if best == "" {
				t.Errorf("site/src/content.ts's migration table lists %q as cut, and surface.json retires no command by that name.\n"+
					"The table is the only place on the site that answers an agent reaching for a pre-v0.3.0 command, so a row naming something the binary does not answer sends that reader nowhere.", token)
				continue
			}
			onSite[best] = token
		}
	}

	var missing []string
	for _, name := range retired {
		if _, ok := onSite[name]; !ok {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)

	if len(missing) > 0 {
		t.Errorf("surface.json retires %d commands; the site's migration table accounts for %d. Missing: %s.\n\n"+
			"Each missing name is a command the BINARY answers with a replacement and the SITE does not mention. "+
			"The binary's answer is a one-line hint at a terminal; the site's table is the page a person reads before "+
			"they ever install it, and it is what the deployed release carries for as long as that release exists. "+
			"Add a row naming the cut command and where it went, or — if a name here was never a top-level command — "+
			"correct cmd/dossierx/retired.go, because a stub claiming a verb `moved` is claiming it used to exist.",
			len(retired), len(onSite), strings.Join(missing, ", "))
	}
}

// ---------------------------------------------------------------------------
// C2 — RELEASING.md's pin sentence against the mechanical sweep
// ---------------------------------------------------------------------------

// pinSentenceRe reads the two counts out of the sentence that caches what the
// sweep found last time. The sentence is deliberately matched loosely on the
// version so that bumping the release does not have to touch this regexp — the
// numbers are what this test is about.
var pinSentenceRe = regexp.MustCompile(`As of v[0-9]+\.[0-9]+\.[0-9]+ that is ([A-Z]+) pins? across ([A-Z]+) files?`)

func TestTheReleasingPinParagraphMatchesTheMechanicalSweep(t *testing.T) {
	_, pins := surfacePinsAndRetired(t)
	releasing := readRepoFile(t, "docs/RELEASING.md")

	m := pinSentenceRe.FindStringSubmatch(releasing)
	if m == nil {
		t.Fatal("docs/RELEASING.md carries no sentence of the form " +
			"\"As of vX.Y.Z that is <N> pins across <M> files\". That sentence is the cache this test cross-checks " +
			"against surface.json's version_pins; without it there is nothing to compare and this check has lost its subject. " +
			"A pin paragraph that lists files WITHOUT stating the counts is the earlier, hand-list form of the same cache — " +
			"the form that had already gone stale twice before the counted sentence replaced it")
	}

	wantPins, ok := proseNumber(m[1])
	if !ok {
		t.Fatalf("the pin sentence spells its pin count %q, which is not a number this test can read. Spell it in digits or in words up to TWENTY, or widen proseNumber deliberately", m[1])
	}
	wantFiles, ok := proseNumber(m[2])
	if !ok {
		t.Fatalf("the pin sentence spells its file count %q, which is not a number this test can read. Spell it in digits or in words up to TWENTY, or widen proseNumber deliberately", m[2])
	}

	files := map[string]bool{}
	for _, p := range pins {
		files[p.File] = true
	}

	if wantPins != len(pins) || wantFiles != len(files) {
		t.Errorf("docs/RELEASING.md says %s pins across %s files; surface.json's version_pins carries %d pins across %d files (%s).\n\n"+
			"The paragraph itself says this list \"has now gone stale twice\", and that the mechanical answer wins: "+
			"if it and the paragraph disagree, the paragraph is the wrong one. A stale pin list is how a release ships "+
			"a raw URL or a `go install` line still pointing at its predecessor.",
			m[1], m[2], len(pins), len(files), strings.Join(sortedKeysOf(files), ", "))
	}

	// The direction that has actually failed: a NEW pin site created by the same
	// release that forgot to add it here. Every file the sweep found must be
	// named in the paragraph.
	//
	// The reverse direction is deliberately not asserted. The paragraph legitimately
	// names other paths in prose — `surface.json`, the bare `install-git-hook.sh`
	// inside a parenthetical — and a test that demanded every backticked path be a
	// pin site would be asserting something about English, not about pins.
	para := pinParagraph(t, releasing)
	for _, file := range sortedKeysOf(files) {
		if !strings.Contains(para, file) {
			t.Errorf("surface.json's sweep found a version pin in %s, and the pin paragraph in docs/RELEASING.md does not name that file.\n\n"+
				"This is the exact failure v0.5.2 shipped into: the fifth pin site was created by the release that failed to add it to this list. "+
				"A reader working from the list rather than the sweep then bumps four of five pins and ships the fifth stale.", file)
		}
	}
}

// pinParagraph returns the region of docs/RELEASING.md that carries the pin
// cache, so the file-name check reads the list rather than the whole document —
// where a stray mention anywhere else would satisfy it.
//
// The end of the region is the "**Do not work from that list" warning the
// counted paragraph carries, or — where a tree predates that warning — the next
// checklist item. The fallback exists because this file runs against more than
// one branch: a tree still on the hand-list form fails the counted-sentence
// check above with a message naming the missing sentence, and the fallback is
// what lets this bound still resolve if the sentence arrives without the
// warning. Neither marker resolving is fatal: with no bound this test would
// read the rest of the document as if it were the list.
func pinParagraph(t *testing.T, releasing string) string {
	t.Helper()
	const endMarker = "**Do not work from that list"

	start := strings.Index(releasing, "As of v")
	if start < 0 {
		t.Fatal("docs/RELEASING.md carries no \"As of v...\" pin paragraph to read")
	}
	rest := releasing[start:]
	end := len(rest)
	if i := strings.Index(rest, endMarker); i >= 0 && i < end {
		return rest[:i]
	}
	if i := strings.Index(rest, "\n- [ ]"); i >= 0 && i < end {
		return rest[:i]
	}
	t.Fatalf("the pin paragraph in docs/RELEASING.md is followed by neither %q nor another checklist item, so this test cannot tell where the list ends and would read the rest of the document as if it were the list", endMarker)
	return ""
}

// ---------------------------------------------------------------------------
// C3 — the sweep the document prints against the sweep the code runs
// ---------------------------------------------------------------------------

// TestTheDocumentedPinSweepIsTheOneTheCodeRuns closes a gap the v0.5.2 gate found
// one commit after lane C shipped: `surfacePinSweep` in cmd/dossierx/surface_test.go
// calls itself "docs/RELEASING.md's own sweep expression, verbatim", and for one
// commit it was not. The constant gained a third URL shape and the command printed
// in the procedure did not, so a maintainer following the written instruction swept
// for two shapes while the inventory knew three — and the three pins the item was
// rewritten to stop losing were invisible to the person doing the sweeping.
//
// This is the same class as C1 and C2, one level up: not prose restating a derived
// number, but prose restating a derived REGEXP. It is checked the same way.
func TestTheDocumentedPinSweepIsTheOneTheCodeRuns(t *testing.T) {
	const sweepConst = "surfacePinSweep = `"

	source := readRepoFile(t, "cmd/dossierx/surface_test.go")
	i := strings.Index(source, sweepConst)
	if i < 0 {
		t.Fatal("cmd/dossierx/surface_test.go no longer declares surfacePinSweep, so the expression the inventory is built from cannot be read and this check has lost one of its two sides")
	}
	rest := source[i+len(sweepConst):]
	j := strings.Index(rest, "`")
	if j < 0 {
		t.Fatal("surfacePinSweep's raw string literal is unterminated")
	}
	code := rest[:j]

	releasing := readRepoFile(t, "docs/RELEASING.md")
	if !strings.Contains(releasing, code) {
		t.Errorf("docs/RELEASING.md does not print the expression the inventory is actually built from.\n"+
			"  the code sweeps: %s\n\n"+
			"The item tells a maintainer to work from the sweep rather than from the list beside it, so a printed command that is narrower than the code's is worse than no command: it produces a short answer that looks like a complete one. Paste the constant into the `git grep` the item prints.", code)
	}
}

// ---------------------------------------------------------------------------
// C4 — every pin against the release the tree itself declares
// ---------------------------------------------------------------------------

// treeDeclaredVersion is the version this tree says it is releasing, read from
// the two places CLAUDE.md names as the declaration the release driver checks
// the tag against: CHANGELOG.md's newest heading and the site's newest
// `releases[]` entry. The two are cross-checked here and disagreement is FATAL
// rather than a pick-one, because a tree that cannot agree with itself about
// its own version gives this test no side to judge the pins against — and that
// disagreement is itself the defect to report, not to paper over by trusting
// either file alone.
func treeDeclaredVersion(t *testing.T) string {
	t.Helper()

	changelog := readRepoFile(t, "CHANGELOG.md")
	headingRe := regexp.MustCompile(`(?m)^## \[(\d+\.\d+\.\d+)\]`)
	m := headingRe.FindStringSubmatch(changelog)
	if m == nil {
		t.Fatal("CHANGELOG.md carries no `## [X.Y.Z]` release heading, so the version this tree declares cannot be read from it")
	}
	fromChangelog := "v" + m[1]

	// The site's release ledger is oldest-first and the LAST entry is the
	// current release (site/src/content.ts says so above the array, and
	// `latestRelease` is defined as releases[releases.length - 1]). The scan is
	// bounded to the array's declaration so a `version:` field anywhere else in
	// the file can never be mistaken for a release entry.
	content := readRepoFile(t, "site/src/content.ts")
	start := strings.Index(content, "const releases: Release[] = [")
	if start < 0 {
		t.Fatal("site/src/content.ts no longer declares `const releases: Release[]`, so the site's newest release entry cannot be read")
	}
	end := strings.Index(content[start:], "export const latestRelease")
	if end < 0 {
		t.Fatal("site/src/content.ts no longer defines latestRelease after the releases array, so this test cannot tell where the array ends")
	}
	versionRe := regexp.MustCompile(`version: "(v\d+\.\d+\.\d+)"`)
	entries := versionRe.FindAllStringSubmatch(content[start:start+end], -1)
	if len(entries) == 0 {
		t.Fatal("no `version: \"vX.Y.Z\"` entries were extracted from site/src/content.ts's releases array; the extraction is broken, not the site")
	}
	fromSite := entries[len(entries)-1][1]

	if fromChangelog != fromSite {
		t.Fatalf("CHANGELOG.md's newest heading declares %s and site/src/content.ts's newest releases[] entry declares %s. "+
			"These are the two declarations the release driver checks the tag against, and while they disagree there is no version to judge the pins by — fix the declaration before trusting any pin comparison", fromChangelog, fromSite)
	}
	return fromChangelog
}

// TestEveryVersionPinCarriesTheVersionThisTreeDeclares is the comparison the
// inventory stopped one step short of. surface.json's version_pins sweeps the
// tree mechanically — the sweep is how three pin sites the hand-list had missed
// were found at all — and records each pin's file, token and version. Then
// nothing read the `version` column back: C2 counts the pins, C3 checks the
// sweep expression, and a tree could still declare v0.5.2 in its CHANGELOG
// while README's `go install` line handed every new user v0.5.1. That is
// precisely the class this file exists for — the version is a number the tree
// already derives twice (the CHANGELOG heading and the site's release ledger),
// restated by hand at every pin site.
//
// The pin set is read from the inventory, never from a file list written here:
// a pin site created next week enters the sweep on its own and is judged here
// on its own, which is the property the hand-list never had.
//
// WHAT THIS CANNOT REACH. It proves the pins agree with the declaration, not
// that the declared version is releasable: whether the tag exists, whether the
// pinned raw URLs resolve, and whether the published artifact matches this tree
// are the release gate's and driver's questions (docs/RELEASING.md), answered
// against the published archive, which no test over the worktree can see.
func TestEveryVersionPinCarriesTheVersionThisTreeDeclares(t *testing.T) {
	_, pins := surfacePinsAndRetired(t)
	declared := treeDeclaredVersion(t)

	for _, p := range pins {
		if p.Version != declared {
			t.Errorf("%s pins %q at %s, and this tree declares %s (CHANGELOG.md's newest heading, site/src/content.ts's newest releases[] entry).\n\n"+
				"A pin behind the declaration ships the PREVIOUS release to everyone who follows this document: the `go install` "+
				"line installs the old binary, a raw URL fetches the old script, and a copied CI template gates other people's "+
				"merges with the old engine. Move the pin with the release, or — if the declaration itself is the premature side — "+
				"fix CHANGELOG.md and the site together.", p.File, p.Pin, p.Version, declared)
		}
	}
}

// ---------------------------------------------------------------------------
// C5 — README's counted surface claims against the inventory's counts
// ---------------------------------------------------------------------------

// readmeCountedClaimPatterns are the sentence shapes in which README states a
// COUNT of the current surface. Each pattern's captures map, in order, onto
// keys of surface.json's `counts` block.
//
// The command count is matched only in its anchored "N commands under M nouns"
// form, never as a bare "N commands", and the narrowing is deliberate rather
// than cautious: README also says "Twelve commands were removed and four moved
// in v0.3.0", which is a claim about HISTORY, and surface.json inventories only
// the tree as it is — no current count can confirm or deny what v0.3.0 did.
// Historical enumerations have their own derived check where one is possible
// (C1 pins the site's migration table against the retired set, whose stubs the
// binary still ships); a history sentence a current inventory cannot reach is
// this file's stated blind spot, not a case to half-check.
var readmeCountedClaimPatterns = []struct {
	re   *regexp.Regexp
	keys []string
}{
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+(?:leaf\s+)?commands\s+under\s+(\d+|[a-z]+(?:-[a-z]+)?)\s+nouns\b`), []string{"commands", "nouns"}},
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+error codes\b`), []string{"error_codes"}},
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+lint rules\b`), []string{"lint_rules"}},
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+HTTP routes\b`), []string{"http_routes"}},
}

// TestREADMECountedClaimsMatchTheSurfaceInventory pins every count README
// states about the current surface to surface.json's `counts`. The counts block
// exists because hand-typed surface counts are the single most reliable staleness
// generator this project has measured: the site's meta description advertised a
// 20-command CLI from v0.3.0 through two minor releases, "the one count on the
// page that nothing derives", and README states the same numbers twice (the
// two-roles table and the CLI-surface heading), so a release that cuts or adds
// a command has two more places to forget.
//
// No expected value is written here — the day someone adds a twentieth command,
// surface.json's regeneration gate moves the count and this test starts
// demanding README say twenty, with nothing in the test itself to update.
func TestREADMECountedClaimsMatchTheSurfaceInventory(t *testing.T) {
	counts := surfaceCountsInventory(t)
	readme := readRepoFile(t, "README.md")

	found := 0
	for _, pattern := range readmeCountedClaimPatterns {
		for _, m := range pattern.re.FindAllStringSubmatch(readme, -1) {
			for i, key := range pattern.keys {
				token := m[i+1]
				n, ok := proseNumber(token)
				if !ok {
					// An article or stray word the alternation let through is
					// not a counted claim; a pattern that can only match
					// numbers never reaches here, but the word branch of the
					// alternation can. Words that are not numbers are not
					// counts, so they are not claims.
					continue
				}
				found++
				want, known := counts[key]
				if !known {
					t.Fatalf("readmeCountedClaimPatterns maps a capture onto counts[%q], which surface.json does not carry; the pattern table is broken, not README", key)
				}
				if n != want {
					t.Errorf("README states %q — %d %s — and surface.json's counts derive %d.\n\n"+
						"The count is derived from the binary and regenerated on every push, so when the two disagree the prose is "+
						"the stale side. The site's meta description already demonstrated this exact failure: it advertised a "+
						"20-command CLI for two minor releases because nothing derived it.\n  matched: %q",
						strings.TrimSpace(m[0]), n, key, want, m[0])
				}
			}
		}
	}

	// Zero matches means the scanner lost its subject, not that README stopped
	// making counted claims — the two-roles table and the CLI-surface heading
	// both state the command and noun counts today, so an empty scan is a
	// broken extraction and must fail rather than pass over zero assertions.
	if found == 0 {
		t.Fatal("no counted surface claims were extracted from README.md; either README genuinely no longer states any count (update this test deliberately) or the sentence shapes moved out from under readmeCountedClaimPatterns — in both cases a silent zero-assertion pass is the wrong answer")
	}
}
