// derived_facts_test.go is layer 1's answer to a finding class that regenerates
// every release: PROSE THAT RESTATES A NUMBER THE TREE ALREADY DERIVES.
//
// WHY THIS FILE EXISTS. The v0.5.2 reading gate ran four rounds — 39, 31, 24, 18
// findings — and the curve decayed without converging. Part of the reason is
// that a whole class of finding is manufactured fresh by every release: a
// sentence, a table row or a count typed by hand that duplicates something
// surface.json already extracts mechanically. Two of them failed inside v0.5.2
// alone:
//
//   - The site's "26 -> 19: what was cut, and where it went" table enumerated
//     TWELVE retired commands. The binary retires SIXTEEN. `lock`, `unlock`,
//     `reaudit` and `flag` were missing, and all four were real top-level
//     commands before v0.3.0 folded them under the claim noun — v0.2.0's
//     root.AddCommand registers newLockCmd, newUnlockCmd, newReauditCmd and
//     newFlagCmd. So an agent that learned the old CLI and reaches for one of
//     them gets a correct answer from the binary and no answer from the one
//     page written to catch exactly that reader.
//   - docs/RELEASING.md's "FIVE pins across FOUR files" sentence, which its own
//     surrounding paragraph admits "has now gone stale twice".
//
// A reading agent can catch either one, but only at release time, only if the
// bundle happened to carry both documents, and only by spending a round. A test
// catches both on every push, for free, and cannot forget.
//
// WHAT MAKES THIS SOUND. surface.json is not a document somebody maintains: it
// is regenerated by cmd/dossierx/surface_test.go's TestGenerateSurfaceJSON and
// compared byte for byte against the committed copy, so a surface change that
// was not regenerated is already a red build. That is what makes it usable here
// as the derived side of a comparison — the prose is checked against a fact, not
// against another piece of prose.
//
// C4 AND C5 WERE ADDED WHEN THIS FILE WAS BROUGHT OVER FROM THE RELEASE BRANCH,
// because the original three checks share a conspicuous gap. surface.json's
// `version_pins` already sweeps the tree for every release-version pin — the
// sweep is how three pin sites the hand-list had missed were found at all — and
// then NOTHING COMPARES THE PINS TO THE VERSION BEING RELEASED. The inventory
// made a stale pin visible and stopped one comparison short of making it a red
// build: C2 checks that the pin PARAGRAPH matches the sweep, C3 that the sweep
// the document prints is the sweep the code runs, and no check said "and every
// pin is the release this tree declares". C4 is that comparison. C5 is the same
// idea for README's counted surface claims ("19 commands under 7 nouns"), which
// the site's meta description has already demonstrated the failure mode for —
// it advertised a 20-command CLI for two minor releases because it was "the one
// count on the page that nothing derives".
//
// WHAT THIS CANNOT REACH. Prose that makes a judgement rather than states a
// number. Most of FORMAT.md is judgement, and no check here pretends otherwise.
// A derived check inherits surface.json's blind spots; it does not invent
// coverage.
package tests

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
	"testing"

	"github.com/BarterX-Tech/dossierx/internal/config"
)

// ---------------------------------------------------------------------------
// the derived side
// ---------------------------------------------------------------------------

// surfacePinsAndRetired reads the two mechanically derived facts the original
// three checks compare prose against.
//
// Unreadable or empty is FATAL rather than skipped. A cross-check that quietly
// passed because surface.json moved or failed to parse would be a pass over zero
// assertions, which is the shape CLAUDE.md refuses by name.
func surfacePinsAndRetired(t *testing.T) (retired []string, pins []struct{ File, Pin, Version string }) {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "surface.json"))
	if err != nil {
		t.Fatalf("read surface.json, the derived side of every comparison in this file: %v", err)
	}
	var doc struct {
		Retired     []string `json:"retired"`
		VersionPins []struct {
			File    string `json:"file"`
			Pin     string `json:"pin"`
			Version string `json:"version"`
		} `json:"version_pins"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode surface.json: %v", err)
	}
	if len(doc.Retired) == 0 {
		t.Fatal("surface.json carries no `retired` entries, so the site comparison would run over an empty set and pass having asserted nothing")
	}
	if len(doc.VersionPins) == 0 {
		t.Fatal("surface.json carries no `version_pins` entries, so the pin-count comparison would run over an empty set and pass having asserted nothing")
	}

	for _, p := range doc.VersionPins {
		pins = append(pins, struct{ File, Pin, Version string }{p.File, p.Pin, p.Version})
	}
	return doc.Retired, pins
}

// surfaceCountsInventory reads surface.json's `counts` block — the mechanically
// derived answer to "how many commands / nouns / error codes / lint rules /
// HTTP routes does this binary ship". Empty or unreadable is fatal for the same
// reason as above: C5 comparing README against an empty map would pass having
// asserted nothing.
func surfaceCountsInventory(t *testing.T) map[string]int {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "surface.json"))
	if err != nil {
		t.Fatalf("read surface.json, the derived side of the counted-claims comparison: %v", err)
	}
	var doc struct {
		Counts map[string]int `json:"counts"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode surface.json: %v", err)
	}
	if len(doc.Counts) == 0 {
		t.Fatal("surface.json carries no `counts` block, so the README counted-claims comparison would run over an empty map and pass having asserted nothing")
	}
	return doc.Counts
}

// proseNumber resolves a counted token as documents in this repository spell
// them: digits ("19"), or the number words used for small counts, in either
// case ("Nineteen", "SEVEN"). A token that resolves as neither is a FAILED
// LOOKUP, not a skipped assertion — the caller fatals, because a count this
// file cannot read is a count it silently stopped checking.
func proseNumber(token string) (int, bool) {
	if n, err := strconv.Atoi(token); err == nil {
		return n, true
	}
	words := map[string]int{
		"ONE": 1, "TWO": 2, "THREE": 3, "FOUR": 4, "FIVE": 5, "SIX": 6,
		"SEVEN": 7, "EIGHT": 8, "NINE": 9, "TEN": 10, "ELEVEN": 11,
		"TWELVE": 12, "THIRTEEN": 13, "FOURTEEN": 14, "FIFTEEN": 15,
		"SIXTEEN": 16, "SEVENTEEN": 17, "EIGHTEEN": 18, "NINETEEN": 19,
		"TWENTY": 20,
	}
	upper := strings.ToUpper(token)
	if n, ok := words[upper]; ok {
		return n, true
	}
	// Composites for the twenties ("twenty-six"), which the site's history prose
	// uses; supported so that a future README sentence using one is read rather
	// than fataled on.
	if rest, found := strings.CutPrefix(upper, "TWENTY-"); found {
		if n, ok := words[rest]; ok && n < 10 {
			return 20 + n, true
		}
	}
	return 0, false
}

// ---------------------------------------------------------------------------
// C1 — the changelog's migration table against the binary's retired set
// ---------------------------------------------------------------------------

// WHERE THIS CHECK'S SUBJECT WENT, because it used to read the site and the
// site no longer carries a migration table.
//
// site/ was a Vite application with twelve sections describing the CLI, and one
// of them tabulated every command v0.3.0 cut against where it went. That whole
// application was replaced by a two-page static site — a memo on why the project
// exists, and the release ledger — on the reasoning that a pre-1.0 tool whose
// direction is not settled should not be maintaining a second, hand-verified
// account of its command surface alongside the README.
//
// THE INVARIANT SURVIVED THE MOVE, and it had to: a reader reaching for a
// retired command must land somewhere that names its replacement. README.md
// sends that reader to "the CHANGELOG's full migration table", so the CHANGELOG
// is the subject now, and it is a better one — it is where the retirement was
// announced, and it is the file a release cannot be cut without touching.
//
// WHAT GOT WEAKER, stated rather than left to be discovered. The site's table
// was a typed data structure and every `cut:` cell in the file belonged to it.
// The CHANGELOG is prose with a markdown table in it, so the extraction is
// anchored on the table's row syntax, and a retirement written as a paragraph
// instead of a row is invisible to the forward direction. That is exactly what
// happened to `migrate`, and it is why the exemption below is declared BY NAME
// with the check that a name-exempt command is still named somewhere in the
// file — an open-ended "prose is fine" carve-out would have made this check
// unable to fail.

// clogMigrationRowRE reads the command out of the first cell of a migration
// table row: `| ` + "`dossierx <invocation>`" + ` | … |`. Anchored at the start
// of the line and requiring the backtick-wrapped command immediately, so an
// ordinary table elsewhere in the file whose first cell happens to be prose
// cannot enter this set.
var clogMigrationRowRE = regexp.MustCompile("(?m)^\\| `dossierx ([^`]+)` \\|")

// clogRowsRetiringAFlag are the table rows whose first cell names a LIVE
// command, because what the row retires is a flag spelling rather than the
// command. Declared by name and by reason, so a second one cannot arrive
// quietly under cover of the first: an unrecognised row is an error, and this
// map is the only door.
var clogRowsRetiringAFlag = map[string]string{
	"comment list --json": "`comment list` is live and JSON is now its default format; " +
		"the row retires the FLAG, and the binary retires no command by this name.",
}

// clogRetirementsInProseOnly are retired commands the migration table does not
// carry a row for, each with the reason. A name here is not excused from the
// file — it still has to be named in it, checked below — only from the table.
var clogRetirementsInProseOnly = map[string]string{
	"migrate": "v0.3.0 wrote the migration table and v0.4.0 removed `dossierx migrate` " +
		"outright, three releases later. Its account is the v0.4.0 entry's prose, which " +
		"explains why there is no replacement command rather than naming one — the one " +
		"retirement in the set whose answer is not a substitution and does not fit a " +
		"Retired/Replacement row.",
}

func TestTheChangelogAccountsForEveryRetiredCommand(t *testing.T) {
	retired, _ := surfacePinsAndRetired(t)
	content := readRepoFile(t, "CHANGELOG.md")

	rows := clogMigrationRowRE.FindAllStringSubmatch(content, -1)
	if len(rows) == 0 {
		t.Fatal("CHANGELOG.md carries no migration table row matching `| `dossierx <command>` |`, so the retired-command table this test reads has moved or gone. That is not a smaller check, it is a check with no subject")
	}

	// Longest-prefix mapping, not equality: a cell says `implink status` or
	// `deps <id>` because the table names the invocation a reader typed, while
	// surface.json names the command. Longest match so that a future retired
	// name which is a prefix of another cannot silently absorb it.
	inTable := map[string]string{} // retired name -> the row it was found in
	for _, row := range rows {
		token := strings.TrimSpace(row[1])
		best := ""
		for _, name := range retired {
			if token != name && !strings.HasPrefix(token, name+" ") {
				continue
			}
			if len(name) > len(best) {
				best = name
			}
		}
		if best == "" {
			if _, declared := clogRowsRetiringAFlag[token]; declared {
				continue
			}
			t.Errorf("CHANGELOG.md's migration table lists `dossierx %s` as retired, and surface.json retires no command by that name.\n\n"+
				"README.md sends every reader reaching for a pre-v0.3.0 command to this table, so a row naming something the binary does not answer sends that reader nowhere. Either the row names a command that was never top-level — in which case correct cmd/dossierx/retired.go, because a stub claiming a verb `moved` claims it used to exist — or the row retires a flag rather than a command, in which case declare it in clogRowsRetiringAFlag with the reason.", token)
			continue
		}
		inTable[best] = token
	}

	var missing []string
	for _, name := range retired {
		if _, ok := inTable[name]; ok {
			continue
		}
		if _, prose := clogRetirementsInProseOnly[name]; prose {
			// Exempt from the TABLE, never from the file. A declared name that
			// the CHANGELOG does not mention at all is the carve-out swallowing
			// the defect it was written to describe.
			if !strings.Contains(content, "`dossierx "+name+"`") {
				t.Errorf("%q is declared in clogRetirementsInProseOnly as accounted for by CHANGELOG.md's prose rather than by a table row, and CHANGELOG.md does not name `dossierx %s` anywhere.\n\n"+
					"The exemption is from the table's shape, not from the file. Either write the prose that retires it, or delete the declaration and add a table row.", name, name)
			}
			continue
		}
		missing = append(missing, name)
	}
	sort.Strings(missing)

	if len(missing) > 0 {
		t.Errorf("surface.json retires %d commands; CHANGELOG.md's migration table accounts for %d. Missing: %s.\n\n"+
			"Each missing name is a command the BINARY answers with a replacement and the CHANGELOG does not. "+
			"The binary's answer is a one-line hint at a terminal that the reader only sees if they still have the old "+
			"invocation to hand; the migration table is what README.md sends them to, and it is the account that outlives "+
			"any one release. Add a row naming the retired command and where it went, or — if a name here was never a "+
			"top-level command — correct cmd/dossierx/retired.go, because a stub claiming a verb `moved` is claiming it "+
			"used to exist.",
			len(retired), len(inTable), strings.Join(missing, ", "))
	}
}

// ---------------------------------------------------------------------------
// C2 — RELEASING.md's pin sentence against the mechanical sweep
// ---------------------------------------------------------------------------

// pinSentenceRe reads the two counts out of the sentence that caches what the
// sweep found last time. The sentence is deliberately matched loosely on the
// version so that bumping the release does not have to touch this regexp — the
// numbers are what this test is about.
var pinSentenceRe = regexp.MustCompile(`As of v[0-9]+\.[0-9]+\.[0-9]+ that is ([A-Z]+) pins? across ([A-Z]+) files?`)

func TestTheReleasingPinParagraphMatchesTheMechanicalSweep(t *testing.T) {
	_, pins := surfacePinsAndRetired(t)
	releasing := readRepoFile(t, "docs/RELEASING.md")

	m := pinSentenceRe.FindStringSubmatch(releasing)
	if m == nil {
		t.Fatal("docs/RELEASING.md carries no sentence of the form " +
			"\"As of vX.Y.Z that is <N> pins across <M> files\". That sentence is the cache this test cross-checks " +
			"against surface.json's version_pins; without it there is nothing to compare and this check has lost its subject. " +
			"A pin paragraph that lists files WITHOUT stating the counts is the earlier, hand-list form of the same cache — " +
			"the form that had already gone stale twice before the counted sentence replaced it")
	}

	wantPins, ok := proseNumber(m[1])
	if !ok {
		t.Fatalf("the pin sentence spells its pin count %q, which is not a number this test can read. Spell it in digits or in words up to TWENTY, or widen proseNumber deliberately", m[1])
	}
	wantFiles, ok := proseNumber(m[2])
	if !ok {
		t.Fatalf("the pin sentence spells its file count %q, which is not a number this test can read. Spell it in digits or in words up to TWENTY, or widen proseNumber deliberately", m[2])
	}

	files := map[string]bool{}
	for _, p := range pins {
		files[p.File] = true
	}

	if wantPins != len(pins) || wantFiles != len(files) {
		t.Errorf("docs/RELEASING.md says %s pins across %s files; surface.json's version_pins carries %d pins across %d files (%s).\n\n"+
			"The paragraph itself says this list \"has now gone stale twice\", and that the mechanical answer wins: "+
			"if it and the paragraph disagree, the paragraph is the wrong one. A stale pin list is how a release ships "+
			"a raw URL or a `go install` line still pointing at its predecessor.",
			m[1], m[2], len(pins), len(files), strings.Join(sortedKeysOf(files), ", "))
	}

	// The direction that has actually failed: a NEW pin site created by the same
	// release that forgot to add it here. Every file the sweep found must be
	// named in the paragraph.
	//
	// The reverse direction is deliberately not asserted. The paragraph legitimately
	// names other paths in prose — `surface.json`, the bare `install-git-hook.sh`
	// inside a parenthetical — and a test that demanded every backticked path be a
	// pin site would be asserting something about English, not about pins.
	para := pinParagraph(t, releasing)
	for _, file := range sortedKeysOf(files) {
		if !strings.Contains(para, file) {
			t.Errorf("surface.json's sweep found a version pin in %s, and the pin paragraph in docs/RELEASING.md does not name that file.\n\n"+
				"This is the exact failure v0.5.2 shipped into: the fifth pin site was created by the release that failed to add it to this list. "+
				"A reader working from the list rather than the sweep then bumps four of five pins and ships the fifth stale.", file)
		}
	}
}

// pinParagraph returns the region of docs/RELEASING.md that carries the pin
// cache, so the file-name check reads the list rather than the whole document —
// where a stray mention anywhere else would satisfy it.
//
// The end of the region is the "**Do not work from that list" warning the
// counted paragraph carries, or — where a tree predates that warning — the next
// checklist item. The fallback exists because this file runs against more than
// one branch: a tree still on the hand-list form fails the counted-sentence
// check above with a message naming the missing sentence, and the fallback is
// what lets this bound still resolve if the sentence arrives without the
// warning. Neither marker resolving is fatal: with no bound this test would
// read the rest of the document as if it were the list.
func pinParagraph(t *testing.T, releasing string) string {
	t.Helper()
	const endMarker = "**Do not work from that list"

	start := strings.Index(releasing, "As of v")
	if start < 0 {
		t.Fatal("docs/RELEASING.md carries no \"As of v...\" pin paragraph to read")
	}
	rest := releasing[start:]
	end := len(rest)
	if i := strings.Index(rest, endMarker); i >= 0 && i < end {
		return rest[:i]
	}
	if i := strings.Index(rest, "\n- [ ]"); i >= 0 && i < end {
		return rest[:i]
	}
	t.Fatalf("the pin paragraph in docs/RELEASING.md is followed by neither %q nor another checklist item, so this test cannot tell where the list ends and would read the rest of the document as if it were the list", endMarker)
	return ""
}

// ---------------------------------------------------------------------------
// C3 — the sweep the document prints against the sweep the code runs
// ---------------------------------------------------------------------------

// TestTheDocumentedPinSweepIsTheOneTheCodeRuns closes a gap the v0.5.2 gate found
// one commit after lane C shipped: `surfacePinSweep` in cmd/dossierx/surface_test.go
// calls itself "docs/RELEASING.md's own sweep expression, verbatim", and for one
// commit it was not. The constant gained a third URL shape and the command printed
// in the procedure did not, so a maintainer following the written instruction swept
// for two shapes while the inventory knew three — and the three pins the item was
// rewritten to stop losing were invisible to the person doing the sweeping.
//
// This is the same class as C1 and C2, one level up: not prose restating a derived
// number, but prose restating a derived REGEXP. It is checked the same way.
func TestTheDocumentedPinSweepIsTheOneTheCodeRuns(t *testing.T) {
	const sweepConst = "surfacePinSweep = `"

	source := readRepoFile(t, "cmd/dossierx/surface_test.go")
	i := strings.Index(source, sweepConst)
	if i < 0 {
		t.Fatal("cmd/dossierx/surface_test.go no longer declares surfacePinSweep, so the expression the inventory is built from cannot be read and this check has lost one of its two sides")
	}
	rest := source[i+len(sweepConst):]
	j := strings.Index(rest, "`")
	if j < 0 {
		t.Fatal("surfacePinSweep's raw string literal is unterminated")
	}
	code := rest[:j]

	releasing := readRepoFile(t, "docs/RELEASING.md")
	if !strings.Contains(releasing, code) {
		t.Errorf("docs/RELEASING.md does not print the expression the inventory is actually built from.\n"+
			"  the code sweeps: %s\n\n"+
			"The item tells a maintainer to work from the sweep rather than from the list beside it, so a printed command that is narrower than the code's is worse than no command: it produces a short answer that looks like a complete one. Paste the constant into the `git grep` the item prints.", code)
	}
}

// ---------------------------------------------------------------------------
// C4 — every pin against the release the tree itself declares
// ---------------------------------------------------------------------------

// treeDeclaredVersion is the version this tree says it is releasing, read from
// the two places CLAUDE.md names as the declaration the release driver checks
// the tag against: CHANGELOG.md's newest heading and the entry
// site/releases.html marks `data-current="true"`. The two are cross-checked here and disagreement is FATAL
// rather than a pick-one, because a tree that cannot agree with itself about
// its own version gives this test no side to judge the pins against — and that
// disagreement is itself the defect to report, not to paper over by trusting
// either file alone.
func treeDeclaredVersion(t *testing.T) string {
	t.Helper()

	changelog := readRepoFile(t, "CHANGELOG.md")
	headingRe := regexp.MustCompile(`(?m)^## \[(\d+\.\d+\.\d+)\]`)
	m := headingRe.FindStringSubmatch(changelog)
	if m == nil {
		t.Fatal("CHANGELOG.md carries no `## [X.Y.Z]` release heading, so the version this tree declares cannot be read from it")
	}
	fromChangelog := "v" + m[1]

	// The site's ledger marks its current entry rather than positioning it;
	// siteCurrentRelease (tests/site_ledger_test.go) is the one reader of that
	// marker in this package, and every way of failing to read it is fatal
	// there rather than returning a value this comparison could trust.
	fromSite := siteCurrentRelease(t)

	if fromChangelog != fromSite {
		t.Fatalf("CHANGELOG.md's newest heading declares %s and site/releases.html's entry marked current declares %s. "+
			"These are the two declarations the release driver checks the tag against, and while they disagree there is no version to judge the pins by — fix the declaration before trusting any pin comparison", fromChangelog, fromSite)
	}
	return fromChangelog
}

// TestEveryVersionPinCarriesTheVersionThisTreeDeclares is the comparison the
// inventory stopped one step short of. surface.json's version_pins sweeps the
// tree mechanically — the sweep is how three pin sites the hand-list had missed
// were found at all — and records each pin's file, token and version. Then
// nothing read the `version` column back: C2 counts the pins, C3 checks the
// sweep expression, and a tree could still declare v0.5.2 in its CHANGELOG
// while README's `go install` line handed every new user v0.5.1. That is
// precisely the class this file exists for — the version is a number the tree
// already declares twice (the CHANGELOG heading and the site's release ledger),
// restated by hand at every pin site.
//
// The pin set is read from the inventory, never from a file list written here:
// a pin site created next week enters the sweep on its own and is judged here
// on its own, which is the property the hand-list never had.
//
// WHAT THIS CANNOT REACH. It proves the pins agree with the declaration, not
// that the declared version is releasable: whether the tag exists, whether the
// pinned raw URLs resolve, and whether the published artifact matches this tree
// are docs/RELEASING.md's questions, answered by hand against the published
// archive, which no test over the worktree can see.
func TestEveryVersionPinCarriesTheVersionThisTreeDeclares(t *testing.T) {
	_, pins := surfacePinsAndRetired(t)
	declared := treeDeclaredVersion(t)

	for _, p := range pins {
		if p.Version != declared {
			t.Errorf("%s pins %q at %s, and this tree declares %s (CHANGELOG.md's newest heading, site/releases.html's entry marked current).\n\n"+
				"A pin behind the declaration ships the PREVIOUS release to everyone who follows this document: the `go install` "+
				"line installs the old binary, a raw URL fetches the old script, and a copied CI template gates other people's "+
				"merges with the old engine. Move the pin with the release, or — if the declaration itself is the premature side — "+
				"fix CHANGELOG.md and the site together.", p.File, p.Pin, p.Version, declared)
		}
	}
}

// ---------------------------------------------------------------------------
// C5 — README's counted surface claims against the inventory's counts
// ---------------------------------------------------------------------------

// readmeCountedClaimPatterns are the sentence shapes in which README states a
// COUNT of the current surface. Each pattern's captures map, in order, onto
// keys of surface.json's `counts` block.
//
// The command count is matched only in its anchored "N commands under M nouns"
// form, never as a bare "N commands", and the narrowing is deliberate rather
// than cautious: README also says "Twelve commands were removed and four moved
// in v0.3.0", which is a claim about HISTORY, and surface.json inventories only
// the tree as it is — no current count can confirm or deny what v0.3.0 did.
// Historical enumerations have their own derived check where one is possible
// (C1 pins the site's migration table against the retired set, whose stubs the
// binary still ships); a history sentence a current inventory cannot reach is
// this file's stated blind spot, not a case to half-check.
var readmeCountedClaimPatterns = []struct {
	re   *regexp.Regexp
	keys []string
}{
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+(?:leaf\s+)?commands\s+under\s+(\d+|[a-z]+(?:-[a-z]+)?)\s+nouns\b`), []string{"commands", "nouns"}},
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+error codes\b`), []string{"error_codes"}},
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+lint rules\b`), []string{"lint_rules"}},
	{regexp.MustCompile(`(?i)\b(\d+|[a-z]+(?:-[a-z]+)?)\s+HTTP routes\b`), []string{"http_routes"}},
}

// TestREADMECountedClaimsMatchTheSurfaceInventory pins every count README
// states about the current surface to surface.json's `counts`. The counts block
// exists because hand-typed surface counts are the single most reliable staleness
// generator this project has measured: the site's meta description advertised a
// 20-command CLI from v0.3.0 through two minor releases, "the one count on the
// page that nothing derives", and README states the same numbers twice (the
// two-roles table and the CLI-surface heading), so a release that cuts or adds
// a command has two more places to forget.
//
// No expected value is written here — the day someone adds a twentieth command,
// surface.json's regeneration gate moves the count and this test starts
// demanding README say twenty, with nothing in the test itself to update.
func TestREADMECountedClaimsMatchTheSurfaceInventory(t *testing.T) {
	counts := surfaceCountsInventory(t)
	readme := readRepoFile(t, "README.md")

	found := 0
	for _, pattern := range readmeCountedClaimPatterns {
		for _, m := range pattern.re.FindAllStringSubmatch(readme, -1) {
			for i, key := range pattern.keys {
				token := m[i+1]
				n, ok := proseNumber(token)
				if !ok {
					// An article or stray word the alternation let through is
					// not a counted claim; a pattern that can only match
					// numbers never reaches here, but the word branch of the
					// alternation can. Words that are not numbers are not
					// counts, so they are not claims.
					continue
				}
				found++
				want, known := counts[key]
				if !known {
					t.Fatalf("readmeCountedClaimPatterns maps a capture onto counts[%q], which surface.json does not carry; the pattern table is broken, not README", key)
				}
				if n != want {
					t.Errorf("README states %q — %d %s — and surface.json's counts derive %d.\n\n"+
						"The count is derived from the binary and regenerated on every push, so when the two disagree the prose is "+
						"the stale side. The site's meta description already demonstrated this exact failure: it advertised a "+
						"20-command CLI for two minor releases because nothing derived it.\n  matched: %q",
						strings.TrimSpace(m[0]), n, key, want, m[0])
				}
			}
		}
	}

	// Zero matches means the scanner lost its subject, not that README stopped
	// making counted claims — the two-roles table and the CLI-surface heading
	// both state the command and noun counts today, so an empty scan is a
	// broken extraction and must fail rather than pass over zero assertions.
	if found == 0 {
		t.Fatal("no counted surface claims were extracted from README.md; either README genuinely no longer states any count (update this test deliberately) or the sentence shapes moved out from under readmeCountedClaimPatterns — in both cases a silent zero-assertion pass is the wrong answer")
	}
}

// ---------------------------------------------------------------------------
// C6 — README's viewer.theme token list against the engine's own allowlist
// ---------------------------------------------------------------------------

// readmeThemeTokenListRe finds the sentence README states the full token
// vocabulary in: "`viewer.theme`'s 28 allowed token names: `a`, `b`, ..., `z`."
// The count in the middle is not captured or checked here — it is prose, not
// a mechanical count, and TestREADMECountedClaimsMatchTheSurfaceInventory's
// bound is that a current inventory can confirm it; ThemeTokenAllowlist's own
// length is what the token LIST is checked against, which is the fact this
// sentence would actually go stale by.
var readmeThemeTokenListRe = regexp.MustCompile("`viewer\\.theme`'s \\d+ allowed token names: ((?:`[a-z0-9-]+`(?:, )?)+)\\.")

// readmeBacktickTokenRe pulls each backtick-quoted token name out of the
// captured list in the order README wrote them.
var readmeBacktickTokenRe = regexp.MustCompile("`([a-z0-9-]+)`")

// TestREADMEThemeTokenListIsDerivedFromThemeTokenAllowlist pins README's
// stated viewer.theme token vocabulary to config.ThemeTokenAllowlist, in
// ORDER as well as membership. Order matters here beyond the usual "two
// renderings of one sequence" argument other engine-order comparisons in this
// file make: internal/render emits every theme declaration in
// ThemeTokenAllowlist's order, so this list is also, incidentally, the order
// a project's exported theme file and every emitted <style> block declare
// these tokens in. A README that lists the right 28 names in the wrong order
// would still describe a different engine than the one shipping.
//
// This is the derived-facts pattern the rest of this file uses: the engine
// side (config.ThemeTokenAllowlist) is a Go slice under test elsewhere in
// this tree (internal/config's own tests, and internal/render's
// theme_tokens_test.go, both fail independently if it drifts from what
// style.css and the validator actually recognise), so comparing README's
// prose against it is a comparison against a fact, not against another piece
// of prose.
func TestREADMEThemeTokenListIsDerivedFromThemeTokenAllowlist(t *testing.T) {
	readme := readRepoFile(t, "README.md")

	m := readmeThemeTokenListRe.FindStringSubmatch(readme)
	if m == nil {
		t.Fatal("README.md carries no sentence matching `viewer.theme`'s N allowed token names: `a`, `b`, ....\" — " +
			"either the sentence was reworded (update readmeThemeTokenListRe deliberately) or it was deleted, and " +
			"in both cases a silent zero-assertion pass over config.ThemeTokenAllowlist is the wrong answer")
	}

	tokenMatches := readmeBacktickTokenRe.FindAllStringSubmatch(m[1], -1)
	if len(tokenMatches) == 0 {
		t.Fatal("the token-list sentence matched but no backtick-quoted token name was extracted from it; " +
			"the capture group is empty, which is a broken regex, not an empty README claim")
	}
	got := make([]string, 0, len(tokenMatches))
	for _, tm := range tokenMatches {
		got = append(got, tm[1])
	}

	want := config.ThemeTokenAllowlist
	if len(want) == 0 {
		t.Fatal("config.ThemeTokenAllowlist is empty; the engine side of this comparison has nothing to compare README " +
			"against, which would make a pass here mean nothing")
	}

	if len(got) != len(want) {
		t.Fatalf("README's viewer.theme token list names %d token(s); config.ThemeTokenAllowlist carries %d.\n\n"+
			"README:   %s\nengine:   %s\n\n"+
			"The allowlist is the engine's own theme vocabulary (internal/config/config.go); when the two counts "+
			"disagree, README is describing a different token set than the one that actually loads.",
			len(got), len(want), strings.Join(got, ", "), strings.Join(want, ", "))
	}
	for i := range want {
		if got[i] != want[i] {
			t.Errorf("README's viewer.theme token list disagrees with config.ThemeTokenAllowlist at position %d: "+
				"README says %q, the engine says %q.\n\nREADME:   %s\nengine:   %s\n\n"+
				"internal/render emits theme declarations in ThemeTokenAllowlist's order (it is documented as load-bearing "+
				"in config.go), so this is not just a cosmetic reordering — README would be describing a different "+
				"emission order than the one the engine actually produces.",
				i, got[i], want[i], strings.Join(got, ", "), strings.Join(want, ", "))
			break
		}
	}
}
