// derived_facts_test.go is layer 1's answer to a finding class that regenerates
// every release: PROSE THAT RESTATES A NUMBER THE TREE ALREADY DERIVES.
//
// WHY THIS FILE EXISTS. The v0.5.2 reading gate ran four rounds — 39, 31, 24, 18
// findings — and the curve decayed without converging. Part of the reason is
// that a whole class of finding is manufactured fresh by every release: a
// sentence, a table row or a count typed by hand that duplicates something
// surface.json already extracts mechanically. Two of them failed inside v0.5.2
// alone:
//
//   - The site's "26 -> 19: what was cut, and where it went" table enumerated
//     TWELVE retired commands. The binary retires SIXTEEN. `lock`, `unlock`,
//     `reaudit` and `flag` were missing, and all four were real top-level
//     commands before v0.3.0 folded them under the claim noun — v0.2.0's
//     root.AddCommand registers newLockCmd, newUnlockCmd, newReauditCmd and
//     newFlagCmd. So an agent that learned the old CLI and reaches for one of
//     them gets a correct answer from the binary and no answer from the one
//     page written to catch exactly that reader.
//   - docs/RELEASING.md's "FIVE pins across FOUR files" sentence, which its own
//     surrounding paragraph admits "has now gone stale twice".
//
// A reading agent can catch either one, but only at release time, only if the
// bundle happened to carry both documents, and only by spending a round. A test
// catches both on every push, for free, and cannot forget.
//
// WHAT MAKES THIS SOUND. surface.json is not a document somebody maintains: it
// is regenerated by cmd/dossierx/surface_test.go's TestGenerateSurfaceJSON and
// compared byte for byte against the committed copy, so a surface change that
// was not regenerated is already a red build. That is what makes it usable here
// as the derived side of a comparison — the prose is checked against a fact, not
// against another piece of prose.
//
// WHAT THIS CANNOT REACH. Prose that makes a judgement rather than states a
// number. Most of FORMAT.md is judgement, and no check here pretends otherwise.
// A derived check inherits surface.json's blind spots; it does not invent
// coverage.
//
// The design record is docs/superpowers/specs/2026-08-14-gate-cycle-reduction-design.md.
package tests

import (
	"encoding/json"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------------
// the derived side
// ---------------------------------------------------------------------------

// surfacePinsAndRetired reads the two mechanically derived facts this file
// compares prose against.
//
// Unreadable or empty is FATAL rather than skipped. A cross-check that quietly
// passed because surface.json moved or failed to parse would be a pass over zero
// assertions, which is the shape CLAUDE.md refuses by name.
func surfacePinsAndRetired(t *testing.T) (retired []string, pins []struct{ File, Pin, Version string }) {
	t.Helper()

	raw, err := os.ReadFile(filepath.Join(repoRoot(t), "surface.json"))
	if err != nil {
		t.Fatalf("read surface.json, the derived side of every comparison in this file: %v", err)
	}
	var doc struct {
		Retired     []string `json:"retired"`
		VersionPins []struct {
			File    string `json:"file"`
			Pin     string `json:"pin"`
			Version string `json:"version"`
		} `json:"version_pins"`
	}
	if err := json.Unmarshal(raw, &doc); err != nil {
		t.Fatalf("decode surface.json: %v", err)
	}
	if len(doc.Retired) == 0 {
		t.Fatal("surface.json carries no `retired` entries, so the site comparison would run over an empty set and pass having asserted nothing")
	}
	if len(doc.VersionPins) == 0 {
		t.Fatal("surface.json carries no `version_pins` entries, so the pin-count comparison would run over an empty set and pass having asserted nothing")
	}

	for _, p := range doc.VersionPins {
		pins = append(pins, struct{ File, Pin, Version string }{p.File, p.Pin, p.Version})
	}
	return doc.Retired, pins
}

// ---------------------------------------------------------------------------
// C1 — the site's migration table against the binary's retired set
// ---------------------------------------------------------------------------

// siteAddedMarker is the one `cut:` value in the migration table that names no
// retired command. The table's last row inverts the columns to list what v0.3.0
// ADDED, and this string sits in the `cut` position to label it. It is skipped
// by name rather than by a heuristic, so a real command that ever looked like a
// marker could not slip through the same door.
const siteAddedMarker = "— added —"

// siteCutRe extracts the `cut:` cell of every row in site/src/content.ts's
// migration table. All eight occurrences of `cut:` in that file belong to that
// table; if a second table ever adopts the key, this test's own count assertion
// below is what notices.
var siteCutRe = regexp.MustCompile(`cut: "([^"]*)"`)

func TestTheSiteAccountsForEveryRetiredCommand(t *testing.T) {
	retired, _ := surfacePinsAndRetired(t)
	content := readRepoFile(t, "site/src/content.ts")

	if !strings.Contains(content, "migration: {") {
		t.Fatal("site/src/content.ts no longer declares a `migration:` block, so the retired-command table this test reads has moved or gone. That is not a smaller check, it is a check with no subject")
	}

	matches := siteCutRe.FindAllStringSubmatch(content, -1)
	if len(matches) == 0 {
		t.Fatal("site/src/content.ts declares `migration:` but no `cut:` cells were extracted, so the table is unreadable to this test")
	}

	// Longest-prefix mapping, not equality: a cell says "implink status" or
	// "migrate --adopt" because the site names the invocation a reader typed,
	// while surface.json names the command. Longest match so that a future
	// retired name which is a prefix of another cannot silently absorb it.
	onSite := map[string]string{} // retired name -> the cell it was found in
	for _, m := range matches {
		for _, token := range strings.Split(m[1], "·") {
			token = strings.TrimSpace(token)
			if token == "" || token == siteAddedMarker {
				continue
			}
			best := ""
			for _, name := range retired {
				if token != name && !strings.HasPrefix(token, name+" ") {
					continue
				}
				if len(name) > len(best) {
					best = name
				}
			}
			if best == "" {
				t.Errorf("site/src/content.ts's migration table lists %q as cut, and surface.json retires no command by that name.\n"+
					"The table is the only place on the site that answers an agent reaching for a pre-v0.3.0 command, so a row naming something the binary does not answer sends that reader nowhere.", token)
				continue
			}
			onSite[best] = token
		}
	}

	var missing []string
	for _, name := range retired {
		if _, ok := onSite[name]; !ok {
			missing = append(missing, name)
		}
	}
	sort.Strings(missing)

	if len(missing) > 0 {
		t.Errorf("surface.json retires %d commands; the site's migration table accounts for %d. Missing: %s.\n\n"+
			"Each missing name is a command the BINARY answers with a replacement and the SITE does not mention. "+
			"The binary's answer is a one-line hint at a terminal; the site's table is the page a person reads before "+
			"they ever install it, and it is what the deployed release carries for as long as that release exists. "+
			"Add a row naming the cut command and where it went, or — if a name here was never a top-level command — "+
			"correct cmd/dossierx/retired.go, because a stub claiming a verb `moved` is claiming it used to exist.",
			len(retired), len(onSite), strings.Join(missing, ", "))
	}
}

// ---------------------------------------------------------------------------
// C2 — RELEASING.md's pin sentence against the mechanical sweep
// ---------------------------------------------------------------------------

// pinSentenceRe reads the two counts out of the sentence that caches what the
// sweep found last time. The sentence is deliberately matched loosely on the
// version so that bumping the release does not have to touch this regexp — the
// numbers are what this test is about.
var pinSentenceRe = regexp.MustCompile(`As of v[0-9]+\.[0-9]+\.[0-9]+ that is ([A-Z]+) pins? across ([A-Z]+) files?`)

// numberWords is the spelling this document uses for small counts. A count that
// grows past this table is a failed lookup, not a skipped assertion.
var numberWords = map[string]int{
	"ONE": 1, "TWO": 2, "THREE": 3, "FOUR": 4, "FIVE": 5, "SIX": 6,
	"SEVEN": 7, "EIGHT": 8, "NINE": 9, "TEN": 10, "ELEVEN": 11, "TWELVE": 12,
}

func TestTheReleasingPinParagraphMatchesTheMechanicalSweep(t *testing.T) {
	_, pins := surfacePinsAndRetired(t)
	releasing := readRepoFile(t, "docs/RELEASING.md")

	m := pinSentenceRe.FindStringSubmatch(releasing)
	if m == nil {
		t.Fatal("docs/RELEASING.md no longer carries a sentence of the form " +
			"\"As of vX.Y.Z that is <N> pins across <M> files\". That sentence is the cache this test cross-checks " +
			"against surface.json's version_pins; without it there is nothing to compare and this check has lost its subject")
	}

	wantPins, ok := numberWords[m[1]]
	if !ok {
		t.Fatalf("the pin sentence spells its pin count %q, which is not a number word this test can read. Spell it in words from ONE to TWELVE, or widen numberWords deliberately", m[1])
	}
	wantFiles, ok := numberWords[m[2]]
	if !ok {
		t.Fatalf("the pin sentence spells its file count %q, which is not a number word this test can read. Spell it in words from ONE to TWELVE, or widen numberWords deliberately", m[2])
	}

	files := map[string]bool{}
	for _, p := range pins {
		files[p.File] = true
	}

	if wantPins != len(pins) || wantFiles != len(files) {
		t.Errorf("docs/RELEASING.md says %s pins across %s files; surface.json's version_pins carries %d pins across %d files (%s).\n\n"+
			"The paragraph itself says this list \"has now gone stale twice\", and that the mechanical answer wins: "+
			"if it and the paragraph disagree, the paragraph is the wrong one. A stale pin list is how a release ships "+
			"a raw URL or a `go install` line still pointing at its predecessor.",
			m[1], m[2], len(pins), len(files), strings.Join(sortedKeysOf(files), ", "))
	}

	// The direction that has actually failed: a NEW pin site created by the same
	// release that forgot to add it here. Every file the sweep found must be
	// named in the paragraph.
	//
	// The reverse direction is deliberately not asserted. The paragraph legitimately
	// names other paths in prose — `surface.json`, the bare `install-git-hook.sh`
	// inside a parenthetical — and a test that demanded every backticked path be a
	// pin site would be asserting something about English, not about pins.
	para := pinParagraph(t, releasing)
	for _, file := range sortedKeysOf(files) {
		if !strings.Contains(para, file) {
			t.Errorf("surface.json's sweep found a version pin in %s, and the pin paragraph in docs/RELEASING.md does not name that file.\n\n"+
				"This is the exact failure v0.5.2 shipped into: the fifth pin site was created by the release that failed to add it to this list. "+
				"A reader working from the list rather than the sweep then bumps four of five pins and ships the fifth stale.", file)
		}
	}
}

// pinParagraph returns the region of docs/RELEASING.md that carries the pin
// cache, so the file-name check reads the list rather than the whole document —
// where a stray mention anywhere else would satisfy it.
func pinParagraph(t *testing.T, releasing string) string {
	t.Helper()
	const endMarker = "**Do not work from that list"

	start := strings.Index(releasing, "As of v")
	if start < 0 {
		t.Fatal("docs/RELEASING.md carries no \"As of v...\" pin paragraph to read")
	}
	rest := releasing[start:]
	if end := strings.Index(rest, endMarker); end >= 0 {
		return rest[:end]
	}
	t.Fatalf("the pin paragraph in docs/RELEASING.md is no longer followed by %q, so this test cannot tell where the list ends and would read the rest of the document as if it were the list", endMarker)
	return ""
}
