// fixture_staleness_test.go closes a hole that shipped twice.
//
// testdata/fixture-*/viewer/index.html and testdata/fixture-*/.catalog.json are
// tracked, GENERATED artifacts — line 1 of the viewer says so — and until this
// file existed no test read either one. So a rendering, CSS or viewer-chrome
// change shipped with the committed copies left behind, which happened in
// v0.3.1 and v0.4.1, caught by review each time and never by CI.
// docs/RELEASING.md carries a checklist item asking a human to remember;
// this file is what makes forgetting red.
//
// The mechanism: for every discovered fixture, copy the whole fixture tree
// into a temp dir, run the real "dossierx check" against the copy, normalize
// the timestamps, and compare the rest byte for byte against what is
// committed. The consequence is deliberate — a commit that changes rendered
// output and does not regenerate the fixtures is now a red build, so
// regeneration stops being a release-time habit and becomes a property of the
// commit that caused the drift.
//
// The fixture list is DISCOVERED, never hardcoded. A test that named two
// fixtures would itself go stale the moment a third appeared, which is exactly
// the failure it exists to prevent — and it means this file needs no knowledge
// of which fixtures a branch has created yet. A fixture whose viewer/ is not
// committed is simply not a fixture this test has anything to compare against,
// and is skipped rather than failed.
package tests

import (
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"
	"testing"
)

// The two timestamp formats a regenerated viewer legitimately differs in, per
// docs/RELEASING.md's "the only expected changes are the generation timestamp"
// sentence. Normalizing by FORMAT rather than by line number means neither
// normalizer has to be revisited when a stamp moves or a third occurrence of
// an existing format appears.
var (
	// Line 1's "<!-- generated by dossierx check at 2026-08-03T20:51:05Z -->"
	// header, and the graph payload's generated_at.
	rfc3339Stamp = regexp.MustCompile(`\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}Z`)
	// The sidebar footer's "Generated 2026-08-03 20:51 UTC" string.
	humanStamp = regexp.MustCompile(`\d{4}-\d{2}-\d{2} \d{2}:\d{2} UTC`)
)

// normalizeGeneratedTimestamps replaces every occurrence of the two expected
// drifting formats with a fixed token. It deliberately does NOT normalize
// anything else: the whole value of this test is that everything except a
// timestamp must match exactly, so any further normalizer would be a hole.
func normalizeGeneratedTimestamps(s string) string {
	s = rfc3339Stamp.ReplaceAllString(s, "<GENERATED-AT-RFC3339>")
	s = humanStamp.ReplaceAllString(s, "<GENERATED-AT-MINUTE-UTC>")
	return s
}

// firstDifferingLine returns the 1-based number of the first line on which
// want and got differ, plus both lines. It returns 0 when they are identical.
// A trailing length difference reports as a difference on the first line one
// side does not have.
func firstDifferingLine(want, got string) (line int, wantLine, gotLine string) {
	w := strings.Split(want, "\n")
	g := strings.Split(got, "\n")
	n := len(w)
	if len(g) < n {
		n = len(g)
	}
	for i := 0; i < n; i++ {
		if w[i] != g[i] {
			return i + 1, w[i], g[i]
		}
	}
	if len(w) != len(g) {
		i := n
		wl, gl := "<end of file>", "<end of file>"
		if i < len(w) {
			wl = w[i]
		}
		if i < len(g) {
			gl = g[i]
		}
		return i + 1, wl, gl
	}
	return 0, "", ""
}

// renderedFixture is one discovered fixture: a directory under testdata/ that
// carries both a project.config.yaml and a committed build/viewer/index.html, which
// together are what make it comparable at all.
type renderedFixture struct {
	name string // e.g. "fixture-basic"
	dir  string // absolute path to the committed fixture
}

// discoverRenderedFixtures walks testdata/ for fixture-* directories carrying
// both a project.config.yaml and a committed build/viewer/index.html.
//
// testdata/fixture-coverage matches the glob but has neither file at its top
// level (its projects are one level down), so it drops out here without being
// named — which is the point of testing for the files rather than for a list
// of directory names.
func discoverRenderedFixtures(t *testing.T) []renderedFixture {
	t.Helper()

	testdata, err := filepath.Abs(filepath.Join("..", "testdata"))
	if err != nil {
		t.Fatalf("resolve testdata path: %v", err)
	}
	entries, err := os.ReadDir(testdata)
	if err != nil {
		t.Fatalf("read %s: %v", testdata, err)
	}

	var found []renderedFixture
	for _, e := range entries {
		if !e.IsDir() || !strings.HasPrefix(e.Name(), "fixture-") {
			continue
		}
		dir := filepath.Join(testdata, e.Name())
		if _, err := os.Stat(filepath.Join(dir, "project.config.yaml")); err != nil {
			continue
		}
		if _, err := os.Stat(filepath.Join(dir, "build", "viewer", "index.html")); err != nil {
			// A fixture with no committed viewer has nothing to be stale
			// against. That is a real, expected state mid-branch: a fixture's
			// inputs can land in one commit and its generated output in a
			// later one.
			continue
		}
		found = append(found, renderedFixture{name: e.Name(), dir: dir})
	}
	sort.Slice(found, func(i, j int) bool { return found[i].name < found[j].name })
	return found
}

// copyTree copies src into dst recursively, including dotfiles — the lock
// store and the comment digest are engine-managed inputs to a check run, and
// omitting them would make the regenerated viewer differ for reasons that have
// nothing to do with staleness.
func copyTree(t *testing.T, src, dst string) {
	t.Helper()
	err := filepath.Walk(src, func(path string, info os.FileInfo, err error) error {
		if err != nil {
			return err
		}
		rel, err := filepath.Rel(src, path)
		if err != nil {
			return err
		}
		if rel == "." {
			return nil
		}
		target := filepath.Join(dst, rel)
		if info.IsDir() {
			return os.MkdirAll(target, 0o755)
		}
		data, err := os.ReadFile(path)
		if err != nil {
			return err
		}
		if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
			return err
		}
		return os.WriteFile(target, data, 0o644)
	})
	if err != nil {
		t.Fatalf("copy %s into %s: %v", src, dst, err)
	}
}

func TestCommittedFixtureViewersAreNotStale(t *testing.T) {
	fixtures := discoverRenderedFixtures(t)

	// Control (a). A discovery bug that matches nothing must fail here, not
	// pass silently forever — the exact way a scoped walk turns into a test
	// that proves nothing. This is the reason the count is asserted rather
	// than the loop simply being allowed to run zero times.
	if len(fixtures) == 0 {
		t.Fatalf("discovered no fixture with both a project.config.yaml and a committed build/viewer/index.html under testdata/; " +
			"either the fixtures moved or this test's discovery is broken — both are failures, not a pass")
	}

	for _, fx := range fixtures {
		fx := fx
		t.Run(fx.name, func(t *testing.T) {
			tmp := filepath.Join(t.TempDir(), fx.name)
			if err := os.MkdirAll(tmp, 0o755); err != nil {
				t.Fatal(err)
			}
			copyTree(t, fx.dir, tmp)

			// Delete the copied generated artifacts before rendering. Without
			// this the test could pass vacuously: if a future change made
			// check skip the render, the comparison would be reading the
			// copied committed file back and declaring it identical to
			// itself. Removing them first means the bytes compared below are
			// bytes this run actually produced, and a check that renders
			// nothing fails on the missing file instead.
			if err := os.RemoveAll(filepath.Join(tmp, "build", "viewer")); err != nil {
				t.Fatalf("remove copied build/viewer/: %v", err)
			}
			if err := os.RemoveAll(filepath.Join(tmp, "build", "catalog")); err != nil {
				t.Fatalf("remove copied build/catalog/: %v", err)
			}

			cfgPath := filepath.Join(tmp, "project.config.yaml")
			stdout, stderr, code := run(t, tmp, "--config", cfgPath, "check")
			if code != 0 {
				t.Fatalf("check on a copy of %s failed with exit %d\nstdout: %s\nstderr: %s", fx.name, code, stdout, stderr)
			}

			regenCmd := "go run ./cmd/dossierx check --config testdata/" + fx.name + "/project.config.yaml"

			// build/viewer/index.html: timestamps normalized, everything else exact.
			assertNoTrailingViewerWhitespace(t, fx.name, filepath.Join(tmp, "build", "viewer", "index.html"), "fresh output")
			assertNoTrailingViewerWhitespace(t, fx.name, filepath.Join(fx.dir, "build", "viewer", "index.html"), "committed output")
			assertRegeneratedMatches(t, fx, tmp, filepath.Join("build", "viewer", "index.html"), true, regenCmd)

			// build/catalog/catalog.json carries no timestamp at all, so it is
			// compared raw. Normalizing it would only be able to hide something.
			assertRegeneratedMatches(t, fx, tmp, filepath.Join("build", "catalog", "catalog.json"), false, regenCmd)

			// build/ledger/comment-digest.json is written by check for a fixture
			// without a ledger and is a tracked fixture input since the build/
			// layout (this repository's .gitignore negates it under testdata/),
			// so a regeneration that moves it is a stale fixture too.
			if _, err := os.Stat(filepath.Join(fx.dir, "build", "ledger", "comment-digest.json")); err == nil {
				assertRegeneratedMatches(t, fx, tmp, filepath.Join("build", "ledger", "comment-digest.json"), false, regenCmd)
			}

			// Control (b). Everything above passed, which by itself does not
			// prove the comparison can FAIL — a normalizer that flattened too
			// much, or a read that returned the same file twice, would look
			// identical from here. So mutate the rendered copy on disk by one
			// byte and require the very same comparison to report it, on the
			// line the byte was added to.
			t.Run("negative_control_one_byte_difference_is_caught", func(t *testing.T) {
				renderedPath := filepath.Join(tmp, "build", "viewer", "index.html")
				rendered, err := os.ReadFile(renderedPath)
				if err != nil {
					t.Fatalf("read regenerated viewer: %v", err)
				}
				mutated, wantLine := injectOneByte(t, string(rendered))
				if err := os.WriteFile(renderedPath, []byte(mutated), 0o644); err != nil {
					t.Fatalf("write mutated viewer: %v", err)
				}
				reread, err := os.ReadFile(renderedPath)
				if err != nil {
					t.Fatalf("re-read mutated viewer: %v", err)
				}
				committed, err := os.ReadFile(filepath.Join(fx.dir, "build", "viewer", "index.html"))
				if err != nil {
					t.Fatalf("read committed viewer: %v", err)
				}
				gotLine, _, _ := firstDifferingLine(
					normalizeGeneratedTimestamps(string(committed)),
					normalizeGeneratedTimestamps(string(reread)),
				)
				if gotLine != wantLine {
					t.Fatalf("negative control: a one-byte change on line %d was reported at line %d; "+
						"the staleness comparison is not actually comparing", wantLine, gotLine)
				}
			})
		})
	}
}

func assertNoTrailingViewerWhitespace(t *testing.T, fixture, path, label string) {
	t.Helper()
	b, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read %s %s: %v", label, fixture, err)
	}
	for lineNo, line := range strings.Split(string(b), "\n") {
		if strings.HasSuffix(line, " ") || strings.HasSuffix(line, "\t") {
			t.Fatalf("%s %s has trailing whitespace at physical line %d", label, fixture, lineNo+1)
		}
	}
}

// assertRegeneratedMatches compares one generated artifact in the temp copy
// against the committed one. normalize selects whether the two timestamp
// formats are flattened first.
func assertRegeneratedMatches(t *testing.T, fx renderedFixture, tmp, rel string, normalize bool, regenCmd string) {
	t.Helper()

	committedBytes, err := os.ReadFile(filepath.Join(fx.dir, rel))
	if err != nil {
		t.Fatalf("read committed %s/%s: %v", fx.name, rel, err)
	}
	regeneratedBytes, err := os.ReadFile(filepath.Join(tmp, rel))
	if err != nil {
		t.Fatalf("check produced no %s for %s: %v", rel, fx.name, err)
	}

	want, got := string(committedBytes), string(regeneratedBytes)
	if normalize {
		want, got = normalizeGeneratedTimestamps(want), normalizeGeneratedTimestamps(got)
	}

	line, wantLine, gotLine := firstDifferingLine(want, got)
	if line == 0 {
		return
	}
	t.Fatalf(`testdata/%s/%s is STALE: regenerating it produces different bytes.

first difference at line %d
  committed:   %s
  regenerated: %s

This is not a test to work around. Regenerate the committed artifact and
commit the diff, in the same commit as the change that caused it:

  %s

Only the generation timestamps are expected to differ; this comparison already
normalizes both of their formats, so anything reported here is a real change
that the committed fixture has not caught up with.`,
		fx.name, rel, line, truncateForDiff(wantLine), truncateForDiff(gotLine), regenCmd)
}

// injectOneByte appends a single byte to the first non-empty line after line 1
// and returns the mutated content plus that line's 1-based number. Line 1 is
// skipped deliberately: it is the only line the normalizer touches, and the
// control is worth more on a line the normalizer leaves alone.
func injectOneByte(t *testing.T, content string) (mutated string, line int) {
	t.Helper()
	lines := strings.Split(content, "\n")
	for i := 1; i < len(lines); i++ {
		if strings.TrimSpace(lines[i]) == "" {
			continue
		}
		lines[i] += "X"
		return strings.Join(lines, "\n"), i + 1
	}
	t.Fatalf("negative control could not find a line to mutate; the rendered document has %d lines", len(lines))
	return "", 0
}

// truncateForDiff keeps a failure message readable when the differing line is
// a minified stylesheet or an inlined payload.
func truncateForDiff(s string) string {
	const maxLen = 160
	if len(s) <= maxLen {
		return s
	}
	return s[:maxLen] + "… (" + itoa(len(s)) + " bytes)"
}
