// This file covers the "Layout / render" edge-case category end-to-end at
// the CLI level (package-level cases for the same rules live in
// internal/render/render_test.go and internal/render/components/
// components_test.go). It reuses the binPath/run/writeFixtureProject
// scaffolding from cli_test.go in this same package.
package tests

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------
// Row 1: rows is an explicit empty array -> valid; renders an explicit
// "no rows" state, not a blank table.
// ---------------------------------------------------------------------

func TestRenderCLI_ExplicitEmptyRowsArrayIsValid(t *testing.T) {
	root := t.TempDir()
	claimsDir := filepath.Join(root, "claims")
	if err := os.MkdirAll(claimsDir, 0o755); err != nil {
		t.Fatalf("mkdir claims dir: %v", err)
	}
	cfg := "schema_version: 1\nfacets:\n  - internals\nmodules:\n  - emptyrowsmod\nclaims_dir: claims\n"
	if err := os.WriteFile(filepath.Join(root, "project.config.yaml"), []byte(cfg), 0o644); err != nil {
		t.Fatalf("write project.config.yaml: %v", err)
	}

	// rows: [] on disk decodes to a non-nil, zero-length slice — distinct
	// from an omitted rows key — and must be treated as valid, intentional
	// data, not a shape error.
	claim := "id: emptyrowsmod.internals.empty-table\n" +
		"facet: internals\nmodule: emptyrowsmod\nstatus: draft\nlayout: table\n" +
		"rows: []\n" +
		"governed_by:\n  type: none\n  reason: fixture claim, not backed by any real doctrine\n"
	if err := os.WriteFile(filepath.Join(claimsDir, "empty-table.yaml"), []byte(claim), 0o644); err != nil {
		t.Fatalf("write claim: %v", err)
	}

	stdout, stderr, code := run(t, root, "lint")
	if code != 0 {
		t.Fatalf("lint should pass for a claim with an explicit empty rows array, got exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}
	if strings.Contains(stdout, "layout-shape-mismatch") {
		t.Fatalf("lint should not flag an explicit empty rows array as a layout-shape-mismatch:\n%s", stdout)
	}

	stdout, stderr, code = run(t, root, "render")
	if code != 0 {
		t.Fatalf("render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	outPath := filepath.Join(root, "viewer", "index.html")
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}

	if !strings.Contains(string(content), "emptyrowsmod.internals.empty-table") {
		t.Fatalf("rendered output missing the empty-rows claim:\n%s", content)
	}
	if !strings.Contains(string(content), "No rows.") {
		t.Fatalf("rendered output missing explicit no-rows placeholder for empty rows array:\n%s", content)
	}
	if strings.Contains(string(content), "<table>") {
		t.Fatalf("rendered output should not contain a blank <table> for an empty rows array:\n%s", content)
	}
}

// ---------------------------------------------------------------------
// Row 5: "docs render" always overwrites viewer/index.html, even if
// hand-edited since the last render — no diff-and-prompt, the generated
// header is the only warning.
// ---------------------------------------------------------------------

func TestRenderCLI_AlwaysOverwritesHandEditedOutput(t *testing.T) {
	root := t.TempDir()
	writeFixtureProject(t, root, "overwritemod")

	stdout, stderr, code := run(t, root, "render")
	if code != 0 {
		t.Fatalf("first render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	outPath := filepath.Join(root, "viewer", "index.html")
	firstContent, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}
	if !strings.Contains(string(firstContent), "overwritemod.contract.overview") {
		t.Fatalf("first render missing expected fixture claim:\n%s", firstContent)
	}

	// Hand-edit the generated file, simulating a user who edited it
	// directly (against the generated-header's advice).
	handEdited := "<!doctype html><html><body>HAND EDITED, DO NOT CLOBBER ME</body></html>"
	if err := os.WriteFile(outPath, []byte(handEdited), 0o644); err != nil {
		t.Fatalf("hand-edit output: %v", err)
	}

	stdout, stderr, code = run(t, root, "render")
	if code != 0 {
		t.Fatalf("second render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	secondContent, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read re-rendered output: %v", err)
	}

	if strings.Contains(string(secondContent), "HAND EDITED, DO NOT CLOBBER ME") {
		t.Fatalf("render did not overwrite hand-edited output; expected unconditional overwrite:\n%s", secondContent)
	}
	if !strings.Contains(string(secondContent), "overwritemod.contract.overview") {
		t.Fatalf("re-render missing expected fixture claim after overwrite:\n%s", secondContent)
	}
	if !strings.Contains(string(secondContent), "generated by dossierx render") {
		t.Fatalf("re-rendered output missing generated-do-not-edit header:\n%s", secondContent)
	}
}

// ---------------------------------------------------------------------
// Row 4: rendered viewer/index.html must carry a "generated - do not edit"
// header, proven against the actual file on disk (not just Render()'s
// in-memory return value, which internal/render/render_test.go already
// covers).
// ---------------------------------------------------------------------

func TestRenderCLI_GeneratedHeaderPresentOnDisk(t *testing.T) {
	root := t.TempDir()
	writeFixtureProject(t, root, "headermod")

	stdout, stderr, code := run(t, root, "render")
	if code != 0 {
		t.Fatalf("render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	outPath := filepath.Join(root, "viewer", "index.html")
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}

	trimmed := strings.TrimSpace(string(content))
	if !strings.HasPrefix(trimmed, "<!--") {
		t.Fatalf("rendered file does not start with a comment header:\n%s", content)
	}
	if !strings.Contains(trimmed, "generated by dossierx render") || !strings.Contains(strings.ToLower(trimmed), "do not edit") {
		t.Fatalf("rendered file header missing generated/do-not-edit warning:\n%s", content)
	}
}
