// This file covers the "Layout / render" edge-case category end-to-end at
// the CLI level (package-level cases for the same rules live in
// internal/render/render_test.go and internal/render/components/
// components_test.go). It reuses the binPath/run/writeFixtureProject
// scaffolding from cli_test.go in this same package.
package tests

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// ---------------------------------------------------------------------
// Row 1: rows is an explicit empty array -> valid; renders an explicit
// "no rows" state, not a blank table.
// ---------------------------------------------------------------------

func TestRenderCLI_ExplicitEmptyRowsArrayIsValid(t *testing.T) {
	root := t.TempDir()
	claimsDir := filepath.Join(root, "claims")
	if err := os.MkdirAll(claimsDir, 0o755); err != nil {
		t.Fatalf("mkdir claims dir: %v", err)
	}
	cfg := "schema_version: 1\nfacets:\n  - internals\nmodules:\n  - emptyrowsmod\nclaims_dir: claims\n"
	if err := os.WriteFile(filepath.Join(root, "project.config.yaml"), []byte(cfg), 0o644); err != nil {
		t.Fatalf("write project.config.yaml: %v", err)
	}

	// rows: [] on disk decodes to a non-nil, zero-length slice — distinct
	// from an omitted rows key — and must be treated as valid, intentional
	// data, not a shape error.
	claim := "id: emptyrowsmod.internals.empty-table\n" +
		"facet: internals\nmodule: emptyrowsmod\nstatus: draft\nlayout: table\n" +
		"rows: []\n" +
		"governed_by:\n  type: none\n  reason: fixture claim, not backed by any real doctrine\n"
	if err := os.WriteFile(filepath.Join(claimsDir, "empty-table.yaml"), []byte(claim), 0o644); err != nil {
		t.Fatalf("write claim: %v", err)
	}

	stdout, stderr, code := run(t, root, "check", "--validate")
	if code != 0 {
		t.Fatalf("lint should pass for a claim with an explicit empty rows array, got exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}
	if strings.Contains(stdout, "layout-shape-mismatch") {
		t.Fatalf("lint should not flag an explicit empty rows array as a layout-shape-mismatch:\n%s", stdout)
	}

	stdout, stderr, code = run(t, root, "check")
	if code != 0 {
		t.Fatalf("render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	outPath := filepath.Join(root, "viewer", "index.html")
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}

	if !strings.Contains(string(content), "emptyrowsmod.internals.empty-table") {
		t.Fatalf("rendered output missing the empty-rows claim:\n%s", content)
	}
	if !strings.Contains(string(content), "No rows.") {
		t.Fatalf("rendered output missing explicit no-rows placeholder for empty rows array:\n%s", content)
	}
	if strings.Contains(string(content), "<table>") {
		t.Fatalf("rendered output should not contain a blank <table> for an empty rows array:\n%s", content)
	}
}

// ---------------------------------------------------------------------
// Row 5: "dossierx check" always overwrites viewer/index.html, even if
// hand-edited since the last render — no diff-and-prompt, the generated
// header is the only warning.
// ---------------------------------------------------------------------

func TestRenderCLI_AlwaysOverwritesHandEditedOutput(t *testing.T) {
	root := t.TempDir()
	writeFixtureProject(t, root, "overwritemod")

	stdout, stderr, code := run(t, root, "check")
	if code != 0 {
		t.Fatalf("first render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	outPath := filepath.Join(root, "viewer", "index.html")
	firstContent, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}
	if !strings.Contains(string(firstContent), "overwritemod.contract.overview") {
		t.Fatalf("first render missing expected fixture claim:\n%s", firstContent)
	}

	// Hand-edit the generated file, simulating a user who edited it
	// directly (against the generated-header's advice).
	handEdited := "<!doctype html><html><body>HAND EDITED, DO NOT CLOBBER ME</body></html>"
	if err := os.WriteFile(outPath, []byte(handEdited), 0o644); err != nil {
		t.Fatalf("hand-edit output: %v", err)
	}

	stdout, stderr, code = run(t, root, "check")
	if code != 0 {
		t.Fatalf("second render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	secondContent, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read re-rendered output: %v", err)
	}

	if strings.Contains(string(secondContent), "HAND EDITED, DO NOT CLOBBER ME") {
		t.Fatalf("render did not overwrite hand-edited output; expected unconditional overwrite:\n%s", secondContent)
	}
	if !strings.Contains(string(secondContent), "overwritemod.contract.overview") {
		t.Fatalf("re-render missing expected fixture claim after overwrite:\n%s", secondContent)
	}
	if !strings.Contains(string(secondContent), "generated by dossierx check") {
		t.Fatalf("re-rendered output missing generated-do-not-edit header:\n%s", secondContent)
	}
}

// ---------------------------------------------------------------------
// DX-AUD-08: `render` and `catalog` must run the raw-html-scope mockup gate
// (error-severity findings only) and fail non-zero on a draft/unreviewed or
// non-allowlisted mockup carrying live HTML/JS, so neither command ever
// publishes stored XSS into the client-shared viewer. A fully valid locked +
// reviewed + allowlisted mockup with safe markup still renders unescaped.
// ---------------------------------------------------------------------

// writeMockupProject writes a project with one layout: mockup claim under
// root. allowlisted controls whether the module is in mockup_modules; the
// remaining fields let each test break exactly one gate requirement.
func writeMockupProject(t *testing.T, root string, allowlisted, locked, reviewed bool, rawHTML string) {
	t.Helper()
	claimsDir := filepath.Join(root, "claims")
	if err := os.MkdirAll(claimsDir, 0o755); err != nil {
		t.Fatalf("mkdir claims dir: %v", err)
	}

	cfg := "schema_version: 1\nfacets:\n  - internals\nmodules:\n  - widget\nclaims_dir: claims\n"
	if allowlisted {
		cfg += "mockup_modules:\n  - widget\n"
	}
	if err := os.WriteFile(filepath.Join(root, "project.config.yaml"), []byte(cfg), 0o644); err != nil {
		t.Fatalf("write project.config.yaml: %v", err)
	}

	status := "draft"
	if locked {
		status = "locked"
	}
	claim := "id: widget.internals.console-mockup\n" +
		"facet: internals\nmodule: widget\nstatus: " + status + "\nlayout: mockup\n" +
		"body: A console mockup.\n" +
		"raw_html: '" + rawHTML + "'\n" +
		"raw_html_reviewed: " + boolStr(reviewed) + "\n" +
		"governed_by:\n  type: none\n  reason: fixture claim, not backed by any real doctrine\n"
	if err := os.WriteFile(filepath.Join(claimsDir, "mockup.yaml"), []byte(claim), 0o644); err != nil {
		t.Fatalf("write mockup claim: %v", err)
	}
}

func boolStr(b bool) string {
	if b {
		return "true"
	}
	return "false"
}

func TestRenderCLI_FailsOnUnreviewedMockupWithHandler(t *testing.T) {
	root := t.TempDir()
	// Allowlisted module, but raw_html_reviewed: false AND an inline
	// event-handler in the markup — the exact draft-authoring stored-XSS
	// scenario `render` must refuse to publish.
	writeMockupProject(t, root, true, false, false, `<div class="gcp-row" onclick="steal()">boom</div>`)

	stdout, stderr, code := run(t, root, "check")
	if code == 0 {
		t.Fatalf("render must fail (non-zero) on an unreviewed mockup with an inline handler, got exit 0\nstdout: %s\nstderr: %s", stdout, stderr)
	}
	if _, err := os.Stat(filepath.Join(root, "viewer", "index.html")); err == nil {
		t.Fatalf("render must not have written viewer/index.html for a gate-failing mockup")
	}
}

func TestCatalogCLI_FailsOnNonAllowlistedMockupWithScript(t *testing.T) {
	root := t.TempDir()
	// Module NOT in mockup_modules, and a <script> tag in the markup — even
	// reviewed, `catalog` must fail rather than bless a non-allowlisted
	// mockup that carries live JS.
	writeMockupProject(t, root, false, true, true, `<div class="gcp-row"><script>steal()</script></div>`)

	stdout, stderr, code := run(t, root, "check")
	if code == 0 {
		t.Fatalf("catalog must fail (non-zero) on a non-allowlisted mockup carrying a script tag, got exit 0\nstdout: %s\nstderr: %s", stdout, stderr)
	}
}

func TestRenderCLI_ValidLockedReviewedAllowlistedMockupRenders(t *testing.T) {
	root := t.TempDir()
	// Fully valid: allowlisted module, locked, reviewed, safe markup.
	writeMockupProject(t, root, true, true, true, `<div class="gcp-row"><span class="mockup-badge">ERROR</span></div>`)
	// Hand-authored "status: locked": say that it is legitimately locked, or
	// the lock-ledger gate correctly reads it as a status flipped by hand.
	armLedger(t, root)

	stdout, stderr, code := run(t, root, "check")
	if code != 0 {
		t.Fatalf("render of a fully valid mockup must succeed, got exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	content, err := os.ReadFile(filepath.Join(root, "viewer", "index.html"))
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}
	if !strings.Contains(string(content), `<span class="mockup-badge">ERROR</span>`) {
		t.Fatalf("valid locked+reviewed+allowlisted mockup should render its markup live/unescaped:\n%s", content)
	}
}

// ---------------------------------------------------------------------
// Row 4: rendered viewer/index.html must carry a "generated - do not edit"
// header, proven against the actual file on disk (not just Render()'s
// in-memory return value, which internal/render/render_test.go already
// covers).
// ---------------------------------------------------------------------

func TestRenderCLI_GeneratedHeaderPresentOnDisk(t *testing.T) {
	root := t.TempDir()
	writeFixtureProject(t, root, "headermod")

	stdout, stderr, code := run(t, root, "check")
	if code != 0 {
		t.Fatalf("render failed: exit %d\nstdout: %s\nstderr: %s", code, stdout, stderr)
	}

	outPath := filepath.Join(root, "viewer", "index.html")
	content, err := os.ReadFile(outPath)
	if err != nil {
		t.Fatalf("read rendered output: %v", err)
	}

	trimmed := strings.TrimSpace(string(content))
	if !strings.HasPrefix(trimmed, "<!--") {
		t.Fatalf("rendered file does not start with a comment header:\n%s", content)
	}
	if !strings.Contains(trimmed, "generated by dossierx check") || !strings.Contains(strings.ToLower(trimmed), "do not edit") {
		t.Fatalf("rendered file header missing generated/do-not-edit warning:\n%s", content)
	}
}
