// skill_router_surface_test.go closes the direction the leaf coverage check
// does not.
//
// tests/envelope_contract_golden_test.go's TestEnvelopeContractGoldenCoversEveryLeaf
// already reads the router skill's noun block and requires a pinned envelope
// for every leaf it names. That is one-directional by construction: it asks
// "is everything the SKILL lists pinned?", and a leaf the skill forgot is
// invisible to it — the leaf is simply not in the set being iterated, so the
// check passes and nothing anywhere says the router is now describing a smaller
// binary than the one shipping beside it.
//
// That is the failure that actually happened. The `theme` noun was added to the
// binary, to surface.json, to README and to the router's companion table, and
// the router's own noun block — the fenced listing an agent reads to learn what
// it can run, and the only listing an AGENTS.md-only harness ever sees — kept
// saying eight nouns and twenty-two leaves. `dossierx skills export` ships that
// block to every consuming project, so the effect is an agent that cannot
// discover a command because the document telling it what exists is stale.
//
// So this file asks the other question: is everything the BINARY has listed?
// surface.json is the derived inventory (regenerated by
// TestGenerateSurfaceJSON, which fails when it drifts from the command tree),
// which makes it the right side to hold the skill against — comparing the skill
// to a hand-written list here would just be a third list to keep in step.
package tests

import (
	"encoding/json"
	"sort"
	"strings"
	"testing"
)

// TestRouterSkillNounBlockListsEveryCommandInTheSurface requires the router's
// fenced noun block and surface.json to name the same set of commands.
//
// Both directions are asserted, and the second is not redundant with the leaf
// coverage check: a leaf the skill names that the binary does NOT have sends an
// agent into a `usage` failure with no recovery, which is the same harm as the
// missing one arriving from the opposite side.
func TestRouterSkillNounBlockListsEveryCommandInTheSurface(t *testing.T) {
	var surface struct {
		Commands []struct {
			Path string `json:"path"`
		} `json:"commands"`
		Counts map[string]int `json:"counts"`
	}
	if err := json.Unmarshal([]byte(readRepoFile(t, "surface.json")), &surface); err != nil {
		t.Fatalf("surface.json: %v", err)
	}
	if len(surface.Commands) == 0 {
		t.Fatal("surface.json lists no commands; this test's source of truth is empty and both comparisons below would pass over nothing")
	}
	// The inventory has to agree with its own headline before it is used as an
	// authority over the skill. surface_meta_test.go pins the number itself;
	// this only refuses to compare against an inventory that contradicts it.
	if want := surface.Counts["commands"]; want != len(surface.Commands) {
		t.Fatalf("surface.json lists %d commands but counts.commands says %d; the inventory disagrees with itself", len(surface.Commands), want)
	}

	inSurface := map[string]bool{}
	for _, c := range surface.Commands {
		inSurface[c.Path] = true
	}
	inSkill := map[string]bool{}
	for _, leaf := range skillLeaves(t) {
		inSkill[leaf] = true
	}

	for path := range inSurface {
		if !inSkill[path] {
			t.Errorf("the binary has %q and the router skill's noun block does not list it; `dossierx skills export` ships that block to every consuming project, so an agent there cannot discover the command at all", quotedLeaf(path))
		}
	}
	for leaf := range inSkill {
		if !inSurface[leaf] {
			t.Errorf("the router skill's noun block lists %q, which surface.json does not carry; an agent that runs it gets a usage failure and no recovery", quotedLeaf(leaf))
		}
	}

	if t.Failed() {
		t.Logf("surface.json: %v", sortedLeafNames(inSurface))
		t.Logf("router noun block: %v", sortedLeafNames(inSkill))
	}
}

// quotedLeaf renders a command path the way a reader would type it.
func quotedLeaf(path string) string { return "dossierx " + path }

func sortedLeafNames(m map[string]bool) []string {
	out := make([]string, 0, len(m))
	for k := range m {
		out = append(out, k)
	}
	sort.Strings(out)
	return out
}

// TestRouterSkillNounBlockHeadingMatchesItsContents keeps the section's own
// heading honest, because that heading is the sentence a reader believes
// without counting: "The nine nouns, twenty-six leaves".
//
// It is checked against the block below it rather than against surface.json, so
// the failure names the right defect — a heading that has fallen behind the
// listing under it is a different edit from a listing that has fallen behind
// the binary, and the test above covers the second.
func TestRouterSkillNounBlockHeadingMatchesItsContents(t *testing.T) {
	src := readRepoFile(t, "skills/dossierx/SKILL.md")
	leaves := skillLeaves(t)
	nouns := map[string]bool{}
	for _, leaf := range leaves {
		nouns[strings.SplitN(leaf, " ", 2)[0]] = true
	}

	heading := routerNounHeading(t, src)
	for _, want := range []struct {
		word  string
		count int
	}{
		{spellNumber(t, len(nouns)), len(nouns)},
		{spellNumber(t, len(leaves)), len(leaves)},
	} {
		if !strings.Contains(strings.ToLower(heading), want.word) {
			t.Errorf("the router's noun-block heading is %q; the block under it has %d (%s) — the heading a reader believes without counting is wrong", heading, want.count, want.word)
		}
	}
}

// routerNounHeading returns the "## The ... nouns, ... leaves" heading line.
func routerNounHeading(t *testing.T, src string) string {
	t.Helper()
	for _, line := range strings.Split(src, "\n") {
		if strings.HasPrefix(line, "## The ") && strings.Contains(line, "nouns") {
			return line
		}
	}
	t.Fatal("skills/dossierx/SKILL.md no longer carries a \"## The ... nouns\" heading; the sentence this test checks has moved or gone")
	return ""
}

// spellNumber spells a small count so the heading is compared against a derived
// word rather than a second hardcoded number.
func spellNumber(t *testing.T, n int) string {
	t.Helper()
	words := map[int]string{
		6: "six", 7: "seven", 8: "eight", 9: "nine", 10: "ten", 11: "eleven",
		12: "twelve", 19: "nineteen", 20: "twenty", 21: "twenty-one",
		22: "twenty-two", 23: "twenty-three", 24: "twenty-four",
		25: "twenty-five", 26: "twenty-six", 27: "twenty-seven",
	}
	w, ok := words[n]
	if !ok {
		t.Fatalf("no spelling for %d; extend the table rather than dropping the heading check", n)
	}
	return w
}
