// store.go implements the on-disk lifecycle of one module's build-order
// Artifact: writing a freshly-Propose'd artifact to disk, loading it back
// (Status), and locking it (Lock) — snapshotting a content-hash baseline
// exactly the way internal/lock.Lock snapshots dependency hashes into its
// Store, so a later edit to a covered claim can be detected as staleness
// rather than silently going unnoticed.
//
// File layout: one JSON file per module (ArtifactPath below), not a single
// file keyed by every module. This is a judgment call — the task
// description explicitly allows either shape — made for two reasons: (1)
// it matches the "Lock(artifactPath, claims)" signature this task
// specifies, which names a single artifact rather than an artifact-plus-
// module-key; (2) it keeps concurrent "dossierx build-order lock --module a"
// and "dossierx build-order lock --module b" invocations from ever touching
// the same file, the same isolation internal/lock.Store's single shared
// file does NOT have (that file's callers serialize instead, via
// lock.AcquireFileLock) — a per-module file sidesteps needing that same
// file-locking machinery here.
package buildorder

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/BarterX-Tech/dossierx/internal/config"
	"github.com/BarterX-Tech/dossierx/internal/lock"
	"github.com/BarterX-Tech/dossierx/internal/model"
)

// nowFunc is this package's clock, overridable in tests so LockedAt can be
// asserted deterministically instead of racing real time — the same
// pattern internal/lock.nowFunc uses.
var nowFunc = time.Now

// ErrNotProposed is returned (wrapped) by LoadArtifact and therefore by
// Status/Lock whenever no artifact file exists yet at the given path. It
// lets callers (the CLI) distinguish "nothing proposed yet" — a normal,
// expected state before a module's first "dossierx build-order propose" — from
// a genuine read/parse failure, the same way config.ErrNotFound lets the
// CLI special-case "no project.config.yaml" instead of reporting a generic
// file error.
var ErrNotProposed = errors.New("buildorder: no build-order artifact proposed yet")

// ArtifactPath returns the on-disk path for module's build-order artifact,
// resolved against cfg's own directory (never the process cwd) — the same
// convention internal/lock.Store's path and catalog's .catalog.json follow.
// The filename is scoped per-module (see this file's package doc comment
// for why) rather than a single shared "dot-build-order.json" for every
// module.
func ArtifactPath(cfg *config.Config, module string) string {
	return filepath.Join(cfg.Dir(), fmt.Sprintf(".build-order.%s.json", module))
}

// WriteArtifact serializes a to path as indented JSON, creating path's
// parent directory if needed. It is always a full overwrite: a
// build-order artifact is always fully regenerated by Propose, never
// hand-edited or merged with a prior version, mirroring catalog.WriteJSON's
// same "always regenerated" contract for .catalog.json.
func WriteArtifact(a *Artifact, path string) error {
	if a == nil {
		return fmt.Errorf("buildorder: cannot write a nil artifact")
	}
	data, err := json.MarshalIndent(a, "", "  ")
	if err != nil {
		return fmt.Errorf("buildorder: marshal artifact: %w", err)
	}
	data = append(data, '\n')

	if dir := filepath.Dir(path); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("buildorder: create output dir %q: %w", dir, err)
		}
	}
	if err := atomicWriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("buildorder: write %s: %w", path, err)
	}
	return nil
}

// LoadArtifact reads and decodes the build-order artifact at path. A
// missing file returns an error wrapping ErrNotProposed (see its doc
// comment) rather than a bare os.IsNotExist-shaped error, so callers can
// use errors.Is(err, ErrNotProposed) the same way they use
// errors.Is(err, config.ErrNotFound).
func LoadArtifact(path string) (*Artifact, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, fmt.Errorf("%w: %s", ErrNotProposed, path)
		}
		return nil, fmt.Errorf("buildorder: read %s: %w", path, err)
	}
	var a Artifact
	if err := json.Unmarshal(raw, &a); err != nil {
		return nil, fmt.Errorf("buildorder: parse %s: %w", path, err)
	}
	return &a, nil
}

// recomputeStale refreshes a.Stale/a.StaleIDs in place against claims'
// current content. It never mutates a.Hashes itself — only Lock ever updates
// that baseline — mirroring internal/lock.DetectStale (read-only re-check)
// vs internal/lock.Lock (the only thing that writes a new baseline).
//
// A not-yet-locked artifact (a.Hashes empty) is never stale: staleness is
// only meaningful relative to a hash baseline that Lock hasn't taken yet.
//
// Six independent drifts all count as staleness, so a frozen artifact can
// never silently stop describing its module's real claim set — nor silently
// describe a different BUILD ORDER than a fresh propose would now compute:
//
//   - content change — a covered claim's lock.ContentHash no longer matches
//     the snapshot taken at the last Lock.
//   - build_role (phase) change — a covered claim's CURRENT build_role no
//     longer matches the phase block the artifact placed it in. A claim's
//     phase is derived from its build_role, so editing it (e.g. schema ->
//     orientation) is an order-affecting change a fresh propose would honor —
//     yet lock.ContentHash deliberately EXCLUDES build_role (that hash is
//     shared with internal/lock's dependency-drift detection, where a
//     build_role edit must NOT flag a claim's DEPENDENTS for review), so the
//     content-hash check above can never catch it. Comparing the claim's
//     current build_role against a.Phases' recorded phase is a build-order-
//     local signal that needs no stored-format change or artifact migration:
//     the placed phase is already in the artifact.
//   - deletion — a covered claim no longer exists at all in the current claim
//     set (it references an id that's gone).
//   - excluded-claim deletion — an id the artifact recorded as out-of-scope
//     (a.Excluded) no longer exists in the current claim set. Symmetric with
//     covered deletion: leaving it unflagged would keep a phantom id in the
//     "N excluded" count for a claim that's gone.
//   - excluded-claim promotion — an id the artifact recorded as out-of-scope
//     (a.Excluded) still exists but its CURRENT build_role now names a build
//     phase (isKnownPhase, Propose's own phased-vs-excluded rule). Symmetric
//     with the covered build_role change: a fresh propose would place it in a
//     phase, a silently different order, yet neither the a.Phases loop (it was
//     never a covered claim) nor the addition loop (a.Excluded ids are folded
//     into the "already covered" set) would otherwise examine it at all.
//   - addition — a claim now locked into this module that the frozen artifact
//     neither placed in a phase (a.ClaimIDs()) nor recorded as excluded
//     (a.Excluded). This was the actual FIX-12 bug: locking a brand-new claim
//     into an already-covered module left stale:false while the artifact
//     silently omitted it. The a.ClaimIDs() UNION a.Excluded set is what
//     keeps a legitimately out-of-scope claim (already in Excluded) from
//     false-positiving here, and the check is scoped to the module's CURRENT
//     locked claims (symmetric with deletion: an artifact only ever exists
//     once its module was fully locked).
func recomputeStale(a *Artifact, claims []model.Claim) {
	if len(a.Hashes) == 0 {
		a.Stale = false
		a.StaleIDs = nil
		return
	}

	byID := make(map[string]model.Claim, len(claims))
	for _, c := range claims {
		byID[c.ID] = c
	}

	staleSet := make(map[string]bool)

	// Content change + deletion + build_role (phase) change, over the
	// artifact's frozen coverage. Iterating a.Phases directly (rather than
	// a.ClaimIDs()) keeps each covered claim's recorded phase — the block it
	// was placed in — in hand for the build_role comparison.
	for _, p := range a.Phases {
		for _, entry := range p.Claims {
			id := entry.ID
			c, ok := byID[id]
			if !ok {
				staleSet[id] = true // deletion
				continue
			}
			if stored, known := a.Hashes[id]; known && stored != lock.ContentHash(c) {
				staleSet[id] = true // content change
			}
			if string(c.BuildRole) != p.Phase {
				staleSet[id] = true // build_role (phase) change
			}
		}
	}

	// Excluded-claim deletion + promotion — over the ids the artifact recorded
	// as out-of-scope. Deletion (the id is gone) is symmetric with covered
	// deletion. Promotion is symmetric with the covered build_role change: an
	// excluded id that STILL exists but whose CURRENT build_role now names a
	// build phase (isKnownPhase — Propose's own phased-vs-excluded rule) would
	// be placed in a phase by a fresh propose, a silently different order, so it
	// must flag stale. A claim that stayed out-of-scope stays unflagged here.
	for _, id := range a.Excluded {
		c, ok := byID[id]
		if !ok {
			staleSet[id] = true // deletion of an excluded claim
			continue
		}
		if isKnownPhase(c.BuildRole) {
			staleSet[id] = true // promotion of an excluded claim into a build phase
		}
	}

	// Addition — any locked claim now in this module that the artifact
	// neither placed in a phase nor recorded as excluded.
	covered := make(map[string]bool)
	for _, id := range a.ClaimIDs() {
		covered[id] = true
	}
	for _, id := range a.Excluded {
		covered[id] = true
	}
	for _, c := range claims {
		if c.Module != a.Module || c.Status != model.StatusLocked {
			continue
		}
		if !covered[c.ID] {
			staleSet[c.ID] = true
		}
	}

	staleIDs := make([]string, 0, len(staleSet))
	for id := range staleSet {
		staleIDs = append(staleIDs, id)
	}
	sort.Strings(staleIDs)
	a.StaleIDs = staleIDs
	a.Stale = len(staleIDs) > 0
}

// Status loads the build-order artifact at path and returns it with
// Stale/StaleIDs freshly recomputed against claims' current content — a
// read-only operation (unlike Lock, it never writes path back out), so
// "dossierx build-order status" can be run at any time without side effects.
func Status(path string, claims []model.Claim) (*Artifact, error) {
	a, err := LoadArtifact(path)
	if err != nil {
		return nil, err
	}
	recomputeStale(a, claims)
	return a, nil
}

// Lock flips the build-order artifact at path from proposed to locked,
// stamping LockedAt and snapshotting lock.ContentHash for every claim
// covered by its Phases (a.ClaimIDs()) into a.Hashes — the new staleness
// baseline, mirroring internal/lock.Lock's own dependency-hash snapshot.
//
// It refuses (returns a non-nil error, path left untouched) in three cases:
//
//   - no artifact exists yet at path (ErrNotProposed — run "dossierx
//     build-order propose" first).
//   - the artifact is stale (a covered claim changed, was deleted, or a new
//     claim was locked into the module). A bare relock here is UNSAFE: Lock
//     only refreshes hashes/flags and never recomputes Phases, so relocking a
//     stale artifact would freeze the now-outdated order (e.g. after a
//     rests_on edit) while silently reporting it fresh. The safe resolution
//     is to re-propose (which recomputes the order against the current claim
//     set) and then lock the freshly-proposed artifact — the re-propose-then-
//     lock flow the dossierx-build-order SKILL documents. Lock returns an
//     error saying exactly that rather than freezing a wrong order.
//   - the artifact is already locked and not stale (nothing to relock —
//     re-locking an unchanged, already-locked artifact would be busywork with
//     no observable effect).
//
// A freshly-proposed artifact (never locked, so no hash baseline) is never
// stale and is the normal thing Lock acts on.
func Lock(path string, claims []model.Claim) (*Artifact, error) {
	a, err := LoadArtifact(path)
	if err != nil {
		return nil, err
	}

	recomputeStale(a, claims)
	if a.Stale {
		return nil, fmt.Errorf(
			"buildorder: %q's build order is stale (%d claim(s) changed, added, or removed: %v); a bare relock would freeze an outdated order, so re-run \"dossierx build-order propose --module %s\" first, then lock",
			a.Module, len(a.StaleIDs), a.StaleIDs, a.Module,
		)
	}
	if a.Locked {
		return nil, fmt.Errorf("buildorder: %q is already locked and not stale; nothing to relock", a.Module)
	}

	byID := make(map[string]model.Claim, len(claims))
	for _, c := range claims {
		byID[c.ID] = c
	}

	hashes := make(map[string]string, len(a.ClaimIDs()))
	for _, id := range a.ClaimIDs() {
		if c, ok := byID[id]; ok {
			hashes[id] = lock.ContentHash(c)
		}
	}

	a.Hashes = hashes
	a.Locked = true
	a.LockedAt = nowFunc().UTC().Format(time.RFC3339Nano)
	a.Stale = false
	a.StaleIDs = nil

	if err := WriteArtifact(a, path); err != nil {
		return nil, err
	}
	return a, nil
}

// atomicWriteFile writes data to path without ever leaving a reader able to
// observe a partially-written file: it writes to a temp file created in
// path's own directory (so the later rename stays on one filesystem, which
// is what makes it atomic) and then renames it over path. Duplicated here
// (rather than exported from internal/lock or internal/loader, which both
// already have their own copy) to keep this package's dependency footprint
// limited to what it actually needs — the same trade-off those two
// packages already made independently of each other.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath) // no-op once the rename below succeeds

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpPath, perm); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
