// store.go implements the on-disk lifecycle of one module's build-order
// Artifact: writing a freshly-Propose'd artifact to disk, loading it back
// (Status), and locking it (Lock) — snapshotting a content-hash baseline
// exactly the way internal/lock.Lock snapshots dependency hashes into its
// Store, so a later edit to a covered claim can be detected as staleness
// rather than silently going unnoticed.
//
// File layout: one JSON file per module (ArtifactPath below), not a single
// file keyed by every module. This is a judgment call — the task
// description explicitly allows either shape — made for two reasons: (1)
// it matches the "Lock(artifactPath, claims)" signature this task
// specifies, which names a single artifact rather than an artifact-plus-
// module-key; (2) it keeps concurrent "dossierx build-order lock --module a"
// and "dossierx build-order lock --module b" invocations from ever touching
// the same file, the same isolation internal/lock.Store's single shared
// file does NOT have (that file's callers serialize instead, via
// lock.AcquireFileLock) — a per-module file sidesteps needing that same
// file-locking machinery here.
package buildorder

import (
	"encoding/json"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"time"

	"github.com/BarterX-Tech/dossierx/internal/config"
	"github.com/BarterX-Tech/dossierx/internal/lock"
	"github.com/BarterX-Tech/dossierx/internal/model"
)

// nowFunc is this package's clock, overridable in tests so LockedAt can be
// asserted deterministically instead of racing real time — the same
// pattern internal/lock.nowFunc uses.
var nowFunc = time.Now

// ErrNotProposed is returned (wrapped) by LoadArtifact and therefore by
// Status/Lock whenever no artifact file exists yet at the given path. It
// lets callers (the CLI) distinguish "nothing proposed yet" — a normal,
// expected state before a module's first "dossierx build-order propose" — from
// a genuine read/parse failure, the same way config.ErrNotFound lets the
// CLI special-case "no project.config.yaml" instead of reporting a generic
// file error.
var ErrNotProposed = errors.New("buildorder: no build-order artifact proposed yet")

// ArtifactPath returns the on-disk path for module's build-order artifact,
// resolved against cfg's own directory (never the process cwd) — the same
// convention internal/lock.Store's path and catalog's .catalog.json follow.
// The filename is scoped per-module (see this file's package doc comment
// for why) rather than a single shared "dot-build-order.json" for every
// module.
func ArtifactPath(cfg *config.Config, module string) string {
	return filepath.Join(cfg.Dir(), fmt.Sprintf(".build-order.%s.json", module))
}

// WriteArtifact serializes a to path as indented JSON, creating path's
// parent directory if needed. It is always a full overwrite: a
// build-order artifact is always fully regenerated by Propose, never
// hand-edited or merged with a prior version, mirroring catalog.WriteJSON's
// same "always regenerated" contract for .catalog.json.
func WriteArtifact(a *Artifact, path string) error {
	if a == nil {
		return fmt.Errorf("buildorder: cannot write a nil artifact")
	}
	data, err := json.MarshalIndent(a, "", "  ")
	if err != nil {
		return fmt.Errorf("buildorder: marshal artifact: %w", err)
	}
	data = append(data, '\n')

	if dir := filepath.Dir(path); dir != "." && dir != "" {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return fmt.Errorf("buildorder: create output dir %q: %w", dir, err)
		}
	}
	if err := atomicWriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("buildorder: write %s: %w", path, err)
	}
	return nil
}

// LoadArtifact reads and decodes the build-order artifact at path. A
// missing file returns an error wrapping ErrNotProposed (see its doc
// comment) rather than a bare os.IsNotExist-shaped error, so callers can
// use errors.Is(err, ErrNotProposed) the same way they use
// errors.Is(err, config.ErrNotFound).
func LoadArtifact(path string) (*Artifact, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		if errors.Is(err, fs.ErrNotExist) {
			return nil, fmt.Errorf("%w: %s", ErrNotProposed, path)
		}
		return nil, fmt.Errorf("buildorder: read %s: %w", path, err)
	}
	var a Artifact
	if err := json.Unmarshal(raw, &a); err != nil {
		return nil, fmt.Errorf("buildorder: parse %s: %w", path, err)
	}
	return &a, nil
}

// recomputeStale refreshes a.Stale/a.StaleIDs in place against claims'
// current content, by comparing each of a.ClaimIDs() against a.Hashes (the
// snapshot taken at the artifact's last Lock). It never mutates a.Hashes
// itself — only Lock ever updates that baseline — mirroring
// internal/lock.DetectStale (read-only re-check) vs internal/lock.Lock
// (the only thing that writes a new baseline).
//
// A not-yet-locked artifact (a.Hashes empty) is never stale: staleness is
// only meaningful relative to a hash baseline that Lock hasn't taken yet.
func recomputeStale(a *Artifact, claims []model.Claim) {
	if len(a.Hashes) == 0 {
		a.Stale = false
		a.StaleIDs = nil
		return
	}

	byID := make(map[string]model.Claim, len(claims))
	for _, c := range claims {
		byID[c.ID] = c
	}

	var staleIDs []string
	for _, id := range a.ClaimIDs() {
		c, ok := byID[id]
		if !ok {
			// A claim this artifact covers no longer exists at all — the
			// artifact can no longer be trusted to describe the current
			// module (it references a file/id that's gone), so this is
			// stale too, not "nothing to hash-compare". Treating a
			// deletion as silently fine was the actual bug: it let
			// "dossierx build-order status" report stale:false for an
			// artifact whose own coverage count no longer matched the
			// module's real claim count.
			staleIDs = append(staleIDs, id)
			continue
		}
		if stored, known := a.Hashes[id]; known && stored != lock.ContentHash(c) {
			staleIDs = append(staleIDs, id)
		}
	}
	sort.Strings(staleIDs)
	a.StaleIDs = staleIDs
	a.Stale = len(staleIDs) > 0
}

// Status loads the build-order artifact at path and returns it with
// Stale/StaleIDs freshly recomputed against claims' current content — a
// read-only operation (unlike Lock, it never writes path back out), so
// "dossierx build-order status" can be run at any time without side effects.
func Status(path string, claims []model.Claim) (*Artifact, error) {
	a, err := LoadArtifact(path)
	if err != nil {
		return nil, err
	}
	recomputeStale(a, claims)
	return a, nil
}

// Lock flips the build-order artifact at path from proposed to locked,
// stamping LockedAt and snapshotting lock.ContentHash for every claim
// covered by its Phases (a.ClaimIDs()) into a.Hashes — the new staleness
// baseline, mirroring internal/lock.Lock's own dependency-hash snapshot.
//
// It refuses (returns a non-nil error, path left untouched) in exactly two
// cases: no artifact exists yet at path (ErrNotProposed — run "dossierx
// build-order propose" first), or the artifact is already locked AND not
// currently stale (nothing to relock — re-locking an unchanged, already-
// locked artifact would just be busywork with no observable effect). An
// already-locked-but-stale artifact IS relockable: that is exactly the
// "someone edited a covered claim after the fact" case this whole
// staleness mechanism exists to let a reviewer resolve, by re-running lock
// once they've confirmed the drift is fine.
func Lock(path string, claims []model.Claim) (*Artifact, error) {
	a, err := LoadArtifact(path)
	if err != nil {
		return nil, err
	}

	recomputeStale(a, claims)
	if a.Locked && !a.Stale {
		return nil, fmt.Errorf("buildorder: %q is already locked and not stale; nothing to relock", a.Module)
	}

	byID := make(map[string]model.Claim, len(claims))
	for _, c := range claims {
		byID[c.ID] = c
	}

	hashes := make(map[string]string, len(a.ClaimIDs()))
	for _, id := range a.ClaimIDs() {
		if c, ok := byID[id]; ok {
			hashes[id] = lock.ContentHash(c)
		}
	}

	a.Hashes = hashes
	a.Locked = true
	a.LockedAt = nowFunc().UTC().Format(time.RFC3339Nano)
	a.Stale = false
	a.StaleIDs = nil

	if err := WriteArtifact(a, path); err != nil {
		return nil, err
	}
	return a, nil
}

// atomicWriteFile writes data to path without ever leaving a reader able to
// observe a partially-written file: it writes to a temp file created in
// path's own directory (so the later rename stays on one filesystem, which
// is what makes it atomic) and then renames it over path. Duplicated here
// (rather than exported from internal/lock or internal/loader, which both
// already have their own copy) to keep this package's dependency footprint
// limited to what it actually needs — the same trade-off those two
// packages already made independently of each other.
func atomicWriteFile(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	tmp, err := os.CreateTemp(dir, filepath.Base(path)+".tmp-*")
	if err != nil {
		return err
	}
	tmpPath := tmp.Name()
	defer os.Remove(tmpPath) // no-op once the rename below succeeds

	if _, err := tmp.Write(data); err != nil {
		tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	if err := os.Chmod(tmpPath, perm); err != nil {
		return err
	}
	return os.Rename(tmpPath, path)
}
