package markdown

// commonMarkEmphasisSpec is the CommonMark 0.31.2 spec's "Emphasis and strong
// emphasis" section, verbatim: all 132 of its examples — numbers 350 to 481
// inclusive, contiguous — each one's source markdown and the reference
// implementation's output, transcribed mechanically from the spec's own
// machine-readable example list (spec.json).
//
// WHY THE TABLE IS IN THE TREE. The flanking rule in markdown_inline.go is not
// a local invention: it is CommonMark's, and the whole underscore decision
// rests on getting it exactly right rather than approximately right. A comment
// claiming conformance is not conformance, so the claim is spelled as a test
// over the spec's own examples and TestCommonMark_EmphasisSection is what holds
// it. Every non-ASCII character is written as a \u escape on purpose: example
// 353 turns entirely on a NO-BREAK SPACE (U+00A0) and 354 on three currency
// signs, and an invisible character in an expected value is worse than an
// unreadable one.
//
// The table is DATA, not expectation-fitting: nothing here was derived from
// this renderer's output. Where this renderer deliberately diverges, the
// divergence is listed in commonMarkEmphasisCeiling with a reason, and the test
// checks that the divergence is exactly the recorded one.
type commonMarkExample struct {
	n    int    // the spec's example number
	md   string // the example's source markdown, verbatim
	html string // the reference implementation's HTML, verbatim
}

var commonMarkEmphasisSpec = []commonMarkExample{
	{n: 350, md: "*foo bar*\n", html: "<p><em>foo bar</em></p>\n"},
	{n: 351, md: "a * foo bar*\n", html: "<p>a * foo bar*</p>\n"},
	{n: 352, md: "a*\"foo\"*\n", html: "<p>a*&quot;foo&quot;*</p>\n"},
	{n: 353, md: "*\u00a0a\u00a0*\n", html: "<p>*\u00a0a\u00a0*</p>\n"},
	{n: 354, md: "*$*alpha.\n\n*\u00a3*bravo.\n\n*\u20ac*charlie.\n", html: "<p>*$*alpha.</p>\n<p>*\u00a3*bravo.</p>\n<p>*\u20ac*charlie.</p>\n"},
	{n: 355, md: "foo*bar*\n", html: "<p>foo<em>bar</em></p>\n"},
	{n: 356, md: "5*6*78\n", html: "<p>5<em>6</em>78</p>\n"},
	{n: 357, md: "_foo bar_\n", html: "<p><em>foo bar</em></p>\n"},
	{n: 358, md: "_ foo bar_\n", html: "<p>_ foo bar_</p>\n"},
	{n: 359, md: "a_\"foo\"_\n", html: "<p>a_&quot;foo&quot;_</p>\n"},
	{n: 360, md: "foo_bar_\n", html: "<p>foo_bar_</p>\n"},
	{n: 361, md: "5_6_78\n", html: "<p>5_6_78</p>\n"},
	{n: 362, md: "\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c_\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f_\n", html: "<p>\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c_\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f_</p>\n"},
	{n: 363, md: "aa_\"bb\"_cc\n", html: "<p>aa_&quot;bb&quot;_cc</p>\n"},
	{n: 364, md: "foo-_(bar)_\n", html: "<p>foo-<em>(bar)</em></p>\n"},
	{n: 365, md: "_foo*\n", html: "<p>_foo*</p>\n"},
	{n: 366, md: "*foo bar *\n", html: "<p>*foo bar *</p>\n"},
	{n: 367, md: "*foo bar\n*\n", html: "<p>*foo bar\n*</p>\n"},
	{n: 368, md: "*(*foo)\n", html: "<p>*(*foo)</p>\n"},
	{n: 369, md: "*(*foo*)*\n", html: "<p><em>(<em>foo</em>)</em></p>\n"},
	{n: 370, md: "*foo*bar\n", html: "<p><em>foo</em>bar</p>\n"},
	{n: 371, md: "_foo bar _\n", html: "<p>_foo bar _</p>\n"},
	{n: 372, md: "_(_foo)\n", html: "<p>_(_foo)</p>\n"},
	{n: 373, md: "_(_foo_)_\n", html: "<p><em>(<em>foo</em>)</em></p>\n"},
	{n: 374, md: "_foo_bar\n", html: "<p>_foo_bar</p>\n"},
	{n: 375, md: "_\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c_\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f\n", html: "<p>_\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c_\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f</p>\n"},
	{n: 376, md: "_foo_bar_baz_\n", html: "<p><em>foo_bar_baz</em></p>\n"},
	{n: 377, md: "_(bar)_.\n", html: "<p><em>(bar)</em>.</p>\n"},
	{n: 378, md: "**foo bar**\n", html: "<p><strong>foo bar</strong></p>\n"},
	{n: 379, md: "** foo bar**\n", html: "<p>** foo bar**</p>\n"},
	{n: 380, md: "a**\"foo\"**\n", html: "<p>a**&quot;foo&quot;**</p>\n"},
	{n: 381, md: "foo**bar**\n", html: "<p>foo<strong>bar</strong></p>\n"},
	{n: 382, md: "__foo bar__\n", html: "<p><strong>foo bar</strong></p>\n"},
	{n: 383, md: "__ foo bar__\n", html: "<p>__ foo bar__</p>\n"},
	{n: 384, md: "__\nfoo bar__\n", html: "<p>__\nfoo bar__</p>\n"},
	{n: 385, md: "a__\"foo\"__\n", html: "<p>a__&quot;foo&quot;__</p>\n"},
	{n: 386, md: "foo__bar__\n", html: "<p>foo__bar__</p>\n"},
	{n: 387, md: "5__6__78\n", html: "<p>5__6__78</p>\n"},
	{n: 388, md: "\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c__\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f__\n", html: "<p>\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c__\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f__</p>\n"},
	{n: 389, md: "__foo, __bar__, baz__\n", html: "<p><strong>foo, <strong>bar</strong>, baz</strong></p>\n"},
	{n: 390, md: "foo-__(bar)__\n", html: "<p>foo-<strong>(bar)</strong></p>\n"},
	{n: 391, md: "**foo bar **\n", html: "<p>**foo bar **</p>\n"},
	{n: 392, md: "**(**foo)\n", html: "<p>**(**foo)</p>\n"},
	{n: 393, md: "*(**foo**)*\n", html: "<p><em>(<strong>foo</strong>)</em></p>\n"},
	{n: 394, md: "**Gomphocarpus (*Gomphocarpus physocarpus*, syn.\n*Asclepias physocarpa*)**\n", html: "<p><strong>Gomphocarpus (<em>Gomphocarpus physocarpus</em>, syn.\n<em>Asclepias physocarpa</em>)</strong></p>\n"},
	{n: 395, md: "**foo \"*bar*\" foo**\n", html: "<p><strong>foo &quot;<em>bar</em>&quot; foo</strong></p>\n"},
	{n: 396, md: "**foo**bar\n", html: "<p><strong>foo</strong>bar</p>\n"},
	{n: 397, md: "__foo bar __\n", html: "<p>__foo bar __</p>\n"},
	{n: 398, md: "__(__foo)\n", html: "<p>__(__foo)</p>\n"},
	{n: 399, md: "_(__foo__)_\n", html: "<p><em>(<strong>foo</strong>)</em></p>\n"},
	{n: 400, md: "__foo__bar\n", html: "<p>__foo__bar</p>\n"},
	{n: 401, md: "__\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c__\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f\n", html: "<p>__\u043f\u0440\u0438\u0441\u0442\u0430\u043d\u044f\u043c__\u0441\u0442\u0440\u0435\u043c\u044f\u0442\u0441\u044f</p>\n"},
	{n: 402, md: "__foo__bar__baz__\n", html: "<p><strong>foo__bar__baz</strong></p>\n"},
	{n: 403, md: "__(bar)__.\n", html: "<p><strong>(bar)</strong>.</p>\n"},
	{n: 404, md: "*foo [bar](/url)*\n", html: "<p><em>foo <a href=\"/url\">bar</a></em></p>\n"},
	{n: 405, md: "*foo\nbar*\n", html: "<p><em>foo\nbar</em></p>\n"},
	{n: 406, md: "_foo __bar__ baz_\n", html: "<p><em>foo <strong>bar</strong> baz</em></p>\n"},
	{n: 407, md: "_foo _bar_ baz_\n", html: "<p><em>foo <em>bar</em> baz</em></p>\n"},
	{n: 408, md: "__foo_ bar_\n", html: "<p><em><em>foo</em> bar</em></p>\n"},
	{n: 409, md: "*foo *bar**\n", html: "<p><em>foo <em>bar</em></em></p>\n"},
	{n: 410, md: "*foo **bar** baz*\n", html: "<p><em>foo <strong>bar</strong> baz</em></p>\n"},
	{n: 411, md: "*foo**bar**baz*\n", html: "<p><em>foo<strong>bar</strong>baz</em></p>\n"},
	{n: 412, md: "*foo**bar*\n", html: "<p><em>foo**bar</em></p>\n"},
	{n: 413, md: "***foo** bar*\n", html: "<p><em><strong>foo</strong> bar</em></p>\n"},
	{n: 414, md: "*foo **bar***\n", html: "<p><em>foo <strong>bar</strong></em></p>\n"},
	{n: 415, md: "*foo**bar***\n", html: "<p><em>foo<strong>bar</strong></em></p>\n"},
	{n: 416, md: "foo***bar***baz\n", html: "<p>foo<em><strong>bar</strong></em>baz</p>\n"},
	{n: 417, md: "foo******bar*********baz\n", html: "<p>foo<strong><strong><strong>bar</strong></strong></strong>***baz</p>\n"},
	{n: 418, md: "*foo **bar *baz* bim** bop*\n", html: "<p><em>foo <strong>bar <em>baz</em> bim</strong> bop</em></p>\n"},
	{n: 419, md: "*foo [*bar*](/url)*\n", html: "<p><em>foo <a href=\"/url\"><em>bar</em></a></em></p>\n"},
	{n: 420, md: "** is not an empty emphasis\n", html: "<p>** is not an empty emphasis</p>\n"},
	{n: 421, md: "**** is not an empty strong emphasis\n", html: "<p>**** is not an empty strong emphasis</p>\n"},
	{n: 422, md: "**foo [bar](/url)**\n", html: "<p><strong>foo <a href=\"/url\">bar</a></strong></p>\n"},
	{n: 423, md: "**foo\nbar**\n", html: "<p><strong>foo\nbar</strong></p>\n"},
	{n: 424, md: "__foo _bar_ baz__\n", html: "<p><strong>foo <em>bar</em> baz</strong></p>\n"},
	{n: 425, md: "__foo __bar__ baz__\n", html: "<p><strong>foo <strong>bar</strong> baz</strong></p>\n"},
	{n: 426, md: "____foo__ bar__\n", html: "<p><strong><strong>foo</strong> bar</strong></p>\n"},
	{n: 427, md: "**foo **bar****\n", html: "<p><strong>foo <strong>bar</strong></strong></p>\n"},
	{n: 428, md: "**foo *bar* baz**\n", html: "<p><strong>foo <em>bar</em> baz</strong></p>\n"},
	{n: 429, md: "**foo*bar*baz**\n", html: "<p><strong>foo<em>bar</em>baz</strong></p>\n"},
	{n: 430, md: "***foo* bar**\n", html: "<p><strong><em>foo</em> bar</strong></p>\n"},
	{n: 431, md: "**foo *bar***\n", html: "<p><strong>foo <em>bar</em></strong></p>\n"},
	{n: 432, md: "**foo *bar **baz**\nbim* bop**\n", html: "<p><strong>foo <em>bar <strong>baz</strong>\nbim</em> bop</strong></p>\n"},
	{n: 433, md: "**foo [*bar*](/url)**\n", html: "<p><strong>foo <a href=\"/url\"><em>bar</em></a></strong></p>\n"},
	{n: 434, md: "__ is not an empty emphasis\n", html: "<p>__ is not an empty emphasis</p>\n"},
	{n: 435, md: "____ is not an empty strong emphasis\n", html: "<p>____ is not an empty strong emphasis</p>\n"},
	{n: 436, md: "foo ***\n", html: "<p>foo ***</p>\n"},
	{n: 437, md: "foo *\\**\n", html: "<p>foo <em>*</em></p>\n"},
	{n: 438, md: "foo *_*\n", html: "<p>foo <em>_</em></p>\n"},
	{n: 439, md: "foo *****\n", html: "<p>foo *****</p>\n"},
	{n: 440, md: "foo **\\***\n", html: "<p>foo <strong>*</strong></p>\n"},
	{n: 441, md: "foo **_**\n", html: "<p>foo <strong>_</strong></p>\n"},
	{n: 442, md: "**foo*\n", html: "<p>*<em>foo</em></p>\n"},
	{n: 443, md: "*foo**\n", html: "<p><em>foo</em>*</p>\n"},
	{n: 444, md: "***foo**\n", html: "<p>*<strong>foo</strong></p>\n"},
	{n: 445, md: "****foo*\n", html: "<p>***<em>foo</em></p>\n"},
	{n: 446, md: "**foo***\n", html: "<p><strong>foo</strong>*</p>\n"},
	{n: 447, md: "*foo****\n", html: "<p><em>foo</em>***</p>\n"},
	{n: 448, md: "foo ___\n", html: "<p>foo ___</p>\n"},
	{n: 449, md: "foo _\\__\n", html: "<p>foo <em>_</em></p>\n"},
	{n: 450, md: "foo _*_\n", html: "<p>foo <em>*</em></p>\n"},
	{n: 451, md: "foo _____\n", html: "<p>foo _____</p>\n"},
	{n: 452, md: "foo __\\___\n", html: "<p>foo <strong>_</strong></p>\n"},
	{n: 453, md: "foo __*__\n", html: "<p>foo <strong>*</strong></p>\n"},
	{n: 454, md: "__foo_\n", html: "<p>_<em>foo</em></p>\n"},
	{n: 455, md: "_foo__\n", html: "<p><em>foo</em>_</p>\n"},
	{n: 456, md: "___foo__\n", html: "<p>_<strong>foo</strong></p>\n"},
	{n: 457, md: "____foo_\n", html: "<p>___<em>foo</em></p>\n"},
	{n: 458, md: "__foo___\n", html: "<p><strong>foo</strong>_</p>\n"},
	{n: 459, md: "_foo____\n", html: "<p><em>foo</em>___</p>\n"},
	{n: 460, md: "**foo**\n", html: "<p><strong>foo</strong></p>\n"},
	{n: 461, md: "*_foo_*\n", html: "<p><em><em>foo</em></em></p>\n"},
	{n: 462, md: "__foo__\n", html: "<p><strong>foo</strong></p>\n"},
	{n: 463, md: "_*foo*_\n", html: "<p><em><em>foo</em></em></p>\n"},
	{n: 464, md: "****foo****\n", html: "<p><strong><strong>foo</strong></strong></p>\n"},
	{n: 465, md: "____foo____\n", html: "<p><strong><strong>foo</strong></strong></p>\n"},
	{n: 466, md: "******foo******\n", html: "<p><strong><strong><strong>foo</strong></strong></strong></p>\n"},
	{n: 467, md: "***foo***\n", html: "<p><em><strong>foo</strong></em></p>\n"},
	{n: 468, md: "_____foo_____\n", html: "<p><em><strong><strong>foo</strong></strong></em></p>\n"},
	{n: 469, md: "*foo _bar* baz_\n", html: "<p><em>foo _bar</em> baz_</p>\n"},
	{n: 470, md: "*foo __bar *baz bim__ bam*\n", html: "<p><em>foo <strong>bar *baz bim</strong> bam</em></p>\n"},
	{n: 471, md: "**foo **bar baz**\n", html: "<p>**foo <strong>bar baz</strong></p>\n"},
	{n: 472, md: "*foo *bar baz*\n", html: "<p>*foo <em>bar baz</em></p>\n"},
	{n: 473, md: "*[bar*](/url)\n", html: "<p>*<a href=\"/url\">bar*</a></p>\n"},
	{n: 474, md: "_foo [bar_](/url)\n", html: "<p>_foo <a href=\"/url\">bar_</a></p>\n"},
	{n: 475, md: "*<img src=\"foo\" title=\"*\"/>\n", html: "<p>*<img src=\"foo\" title=\"*\"/></p>\n"},
	{n: 476, md: "**<a href=\"**\">\n", html: "<p>**<a href=\"**\"></p>\n"},
	{n: 477, md: "__<a href=\"__\">\n", html: "<p>__<a href=\"__\"></p>\n"},
	{n: 478, md: "*a `*`*\n", html: "<p><em>a <code>*</code></em></p>\n"},
	{n: 479, md: "_a `_`_\n", html: "<p><em>a <code>_</code></em></p>\n"},
	{n: 480, md: "**a<https://foo.bar/?q=**>\n", html: "<p>**a<a href=\"https://foo.bar/?q=**\">https://foo.bar/?q=**</a></p>\n"},
	{n: 481, md: "__a<https://foo.bar/?q=__>\n", html: "<p>__a<a href=\"https://foo.bar/?q=__\">https://foo.bar/?q=__</a></p>\n"},
}
