package render

import (
	"html/template"
	"os"
	"regexp"
	"slices"
	"strings"
	"testing"

	"github.com/BarterX-Tech/dossierx/internal/catalog"
	"github.com/BarterX-Tech/dossierx/internal/config"
	"github.com/BarterX-Tech/dossierx/internal/model"
	"github.com/BarterX-Tech/dossierx/internal/visibility"
)

func writeFile(t *testing.T, path, body string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
		t.Fatalf("write %s: %v", path, err)
	}
}

const generatedHeaderText = "generated by dossierx check"

func TestRender_ZeroClaims(t *testing.T) {
	out, err := Render(&catalog.Catalog{}, nil)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.HasPrefix(strings.TrimSpace(out), "<!--") || !strings.Contains(out, generatedHeaderText) {
		t.Errorf("output does not start with a generated-do-not-edit comment header:\n%s", out)
	}
	if !strings.Contains(out, "No claims.") {
		t.Errorf("output missing empty-catalog placeholder:\n%s", out)
	}
	if !strings.Contains(out, "<!doctype html>") {
		t.Errorf("output missing doctype:\n%s", out)
	}
}

func TestRender_NilCatalog(t *testing.T) {
	// Render must never panic on a nil catalog.
	out, err := Render(nil, nil)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(out, "No claims.") {
		t.Errorf("output missing empty-catalog placeholder:\n%s", out)
	}
}

func claimFor(layout model.Layout) model.Claim {
	c := model.Claim{
		ID:      "widget." + string(layout) + ".sample",
		Facet:   string(layout),
		Module:  "widget",
		Status:  model.StatusDraft,
		Layout:  layout,
		RestsOn: model.RestsNone("test fixture"),
	}
	switch layout {
	case model.LayoutCard, model.LayoutTree:
		c.Body = "Some illustrative prose for a " + string(layout) + " claim."
	case model.LayoutTable:
		c.Rows = []model.Row{
			{"field": "id", "type": "string"},
			{"field": "created_at", "type": "timestamp"},
		}
	case model.LayoutList:
		c.Body = "- first item\n- second item\n"
	case model.LayoutSteps:
		c.Steps = []string{"do the first thing", "do the second thing"}
	case model.LayoutBanner:
		c.Body = "heads up: this is a banner"
	}
	return c
}

func TestRender_OnePerLayout(t *testing.T) {
	layouts := []model.Layout{
		model.LayoutCard,
		model.LayoutTable,
		model.LayoutList,
		model.LayoutSteps,
		model.LayoutTree,
		model.LayoutBanner,
	}

	for _, layout := range layouts {
		t.Run(string(layout), func(t *testing.T) {
			claim := claimFor(layout)
			cat, err := catalog.Build([]model.Claim{claim}, nil)
			if err != nil {
				t.Fatalf("catalog.Build: %v", err)
			}
			out, err := Render(cat, nil)
			if err != nil {
				t.Fatalf("Render: %v", err)
			}
			if !strings.Contains(out, claim.ID) {
				t.Errorf("output missing claim id %q:\n%s", claim.ID, out)
			}
			if !strings.Contains(out, `class="claim claim-`+string(layout)) {
				t.Errorf("output missing expected claim-%s section:\n%s", layout, out)
			}
			if !strings.Contains(out, generatedHeaderText) {
				t.Errorf("output missing generated header:\n%s", out)
			}
		})
	}
}

func TestRender_PreservesAuthoredSignificantWhitespace(t *testing.T) {
	claims := []model.Claim{
		{ID: "widget.contract.card", Module: "widget", Facet: "contract", Status: model.StatusDraft, Layout: model.LayoutCard, Body: "hard break  \nnext\n\n```text\n  code value  \n```"},
		{ID: "widget.contract.tree", Module: "widget", Facet: "contract", Status: model.StatusDraft, Layout: model.LayoutTree, Body: "tree value  \n  nested value"},
	}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, &config.Config{Modules: []string{"widget"}, Facets: []string{"contract"}})
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(out, "hard break<br") {
		t.Fatal("authored Markdown hard-break spaces were changed")
	}
	if !strings.Contains(out, "<pre><code class=\"language-text\">  code value  \n</code></pre>") {
		t.Fatal("authored fenced code whitespace was changed")
	}
	if !strings.Contains(out, "<pre class=\"claim-tree-body\">tree value  \n  nested value</pre>") {
		t.Fatal("authored tree whitespace was changed")
	}
}

// TestRender_TableExplicitEmptyRows covers a table claim whose rows is a
// present-but-empty array (rows: [] on disk, decoded to a zero-length,
// non-nil []model.Row) — not simply omitted/nil. It must still be valid
// and render an explicit "no rows" placeholder, never a blank/headerless
// <table> element.
func TestRender_TableExplicitEmptyRows(t *testing.T) {
	claim := model.Claim{
		ID:      "widget.table.empty-rows",
		Facet:   "contract",
		Module:  "widget",
		Status:  model.StatusDraft,
		Layout:  model.LayoutTable,
		Rows:    []model.Row{}, // explicit empty array, not nil/omitted
		RestsOn: model.RestsNone("test fixture"),
	}

	cat, err := catalog.Build([]model.Claim{claim}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, nil)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	if !strings.Contains(out, `class="claim claim-table`) {
		t.Errorf("expected a claim-table section for an empty-rows table claim:\n%s", out)
	}
	if !strings.Contains(out, "No rows.") {
		t.Errorf("expected explicit no-rows placeholder for an empty rows array:\n%s", out)
	}
	if strings.Contains(out, "<table>") {
		t.Errorf("expected no blank <table> element for an empty rows array:\n%s", out)
	}
	// The scroll wrapper opens and closes INSIDE the {{if .Rows}} branch, so the
	// no-rows branch must emit an empty wrapper no more than it emits an empty
	// <table>.
	// (The class name itself is unavoidably present in the inlined stylesheet,
	// so this looks for the wrapper ELEMENT.)
	if strings.Contains(out, `<div class="claim-table-scroll">`) {
		t.Errorf("expected no scroll wrapper for an empty rows array:\n%s", out)
	}
}

// TestRender_TableClaimScrollWrapper pins #22 on the RENDERED html rather than
// on the template: a table claim with rows gets exactly one scroll wrapper,
// opening immediately before its <table> and closing immediately after the
// matching </table>. The overflow lives on that wrapper (style.css), so the
// table keeps its width: 100% and a too-wide table scrolls in its own box
// instead of widening the page.
func TestRender_TableClaimScrollWrapper(t *testing.T) {
	cat, err := catalog.Build([]model.Claim{claimFor(model.LayoutTable)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, nil)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}

	// Count the wrapper ELEMENT, not the class name: style.css is inlined into
	// every rendered viewer, so the selector text is in the document too.
	if n := strings.Count(out, `<div class="claim-table-scroll">`); n != 1 {
		t.Errorf("expected exactly one scroll wrapper, got %d:\n%s", n, out)
	}
	open := regexp.MustCompile(`<div class="claim-table-scroll">\s*<table>`)
	if !open.MatchString(out) {
		t.Errorf("expected the wrapper to open immediately before its <table>:\n%s", out)
	}
	closeRE := regexp.MustCompile(`</table>\s*</div>`)
	if !closeRE.MatchString(out) {
		t.Errorf("expected the wrapper to close immediately after its </table>:\n%s", out)
	}
	// The table itself is untouched — no class, no inline sizing.
	if !strings.Contains(out, "<table>") {
		t.Errorf("expected a bare <table> inside the wrapper:\n%s", out)
	}
}

func TestRender_UnknownLayout(t *testing.T) {
	claim := model.Claim{ID: "x.y.z", Facet: "y", Layout: model.Layout("bogus")}
	cat := &catalog.Catalog{Claims: []model.Claim{claim}}
	if _, err := Render(cat, nil); err == nil {
		t.Fatalf("Render: expected error for unsupported layout, got nil")
	}
}

func TestRender_OverrideMissingPartialFallsBack(t *testing.T) {
	dir := t.TempDir()
	// Only override card.html; every other layout must fall back to the
	// embedded default without erroring.
	overridePath := dir + "/card.html"
	writeFile(t, overridePath, `<section class="claim claim-card override-marker" id="{{.ID}}">OVERRIDDEN: {{.ID}}</section>`)

	cfg := &config.Config{Viewer: config.Viewer{TemplateOverrides: dir}}

	cardCat, err := catalog.Build([]model.Claim{claimFor(model.LayoutCard)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cardCat, cfg)
	if err != nil {
		t.Fatalf("Render (card, overridden): %v", err)
	}
	if !strings.Contains(out, "override-marker") || !strings.Contains(out, "OVERRIDDEN:") {
		t.Errorf("expected overridden card partial to be used:\n%s", out)
	}

	tableCat, err := catalog.Build([]model.Claim{claimFor(model.LayoutTable)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err = Render(tableCat, cfg)
	if err != nil {
		t.Fatalf("Render (table, falls back to default): %v", err)
	}
	if strings.Contains(out, "OVERRIDDEN") {
		t.Errorf("table claim should not pick up the card override:\n%s", out)
	}
	if !strings.Contains(out, `class="claim claim-table`) {
		t.Errorf("expected default table partial to be used:\n%s", out)
	}
}

// ---- grouping (NAV_SPEC) ----------------------------------------------

func groupedClaim(id, module, facet string, status model.Status) model.Claim {
	return model.Claim{
		ID:      id,
		Module:  module,
		Facet:   facet,
		Status:  status,
		Layout:  model.LayoutBanner,
		Body:    "x",
		RestsOn: model.RestsNone("test fixture"),
	}
}

func TestBuildGroups_EmptyCatalogNoPanic(t *testing.T) {
	if got := buildGroups(&catalog.Catalog{}, nil, nil); got != nil {
		t.Errorf("buildGroups(empty) = %#v, want nil", got)
	}
	if got := buildGroups(nil, nil, nil); got != nil {
		t.Errorf("buildGroups(nil catalog) = %#v, want nil", got)
	}
}

func TestBuildGroups_UnknownOrEmptyModuleFacetGoesToUngrouped(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("widget.a", "widget", "contract", model.StatusDraft),
		groupedClaim("widget.b", "", "contract", model.StatusDraft),        // empty module
		groupedClaim("widget.c", "widget", "", model.StatusDraft),          // empty facet
		groupedClaim("widget.d", "mystery", "contract", model.StatusDraft), // unknown module
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}

	rendered := map[string]template.HTML{
		"widget.a": "A", "widget.b": "B", "widget.c": "C", "widget.d": "D",
	}
	groups := buildGroups(cat, cfg, rendered)

	var ungrouped *Group
	for i := range groups {
		if groups[i].Module == ungroupedModuleName {
			ungrouped = &groups[i]
		}
	}
	if ungrouped == nil {
		t.Fatalf("expected an ungrouped bucket, got groups: %#v", groups)
	}
	if len(ungrouped.Claims) != 3 {
		t.Errorf("ungrouped bucket has %d claims, want 3 (b, c, d): %#v", len(ungrouped.Claims), ungrouped.Claims)
	}

	var widgetContract *Group
	for i := range groups {
		if groups[i].Module == "widget" && groups[i].Facet == "contract" {
			widgetContract = &groups[i]
		}
	}
	if widgetContract == nil || len(widgetContract.Claims) != 1 {
		t.Fatalf("expected exactly one widget/contract group with 1 claim, got %#v", widgetContract)
	}
}

func TestBuildGroups_ModuleOrderFollowsConfigThenFallsBackSorted(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("z.a", "zeta", "contract", model.StatusDraft),
		groupedClaim("a.a", "alpha", "contract", model.StatusDraft),
		groupedClaim("m.a", "middle", "contract", model.StatusDraft),
	}
	// cfg only declares "middle" and "alpha" explicitly (in that order);
	// "zeta" is still a recognized module (present in cfg.Modules) so it
	// must appear too, sorted after the declared ones.
	cfg := &config.Config{Modules: []string{"middle", "alpha", "zeta"}, Facets: []string{"contract"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"z.a": "Z", "a.a": "A", "m.a": "M"}
	groups := buildGroups(cat, cfg, rendered)

	if len(groups) != 9 {
		t.Fatalf("got %d groups, want 9 (3 peer tabs × 3 modules): %#v", len(groups), groups)
	}
	gotOrder := []string{groups[0].Module, groups[3].Module, groups[6].Module}
	wantOrder := []string{"middle", "alpha", "zeta"}
	for i := range wantOrder {
		if gotOrder[i] != wantOrder[i] {
			t.Errorf("module order = %v, want %v", gotOrder, wantOrder)
			break
		}
	}
}

func TestBuildGroups_UnknownFacetsLandInUngrouped(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.z", "widget", "zeta-facet", model.StatusDraft),
		groupedClaim("w.a", "widget", "alpha-facet", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.z": "Z", "w.a": "A"}
	groups := buildGroups(cat, cfg, rendered)

	if len(groups) != 1 || groups[0].Module != ungroupedModuleName {
		t.Fatalf("unknown facets must land in ungrouped, got %#v", groups)
	}
}

func TestBuildGroups_AllLockedComputedPerGroup(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusLocked),
		groupedClaim("w.b", "widget", "contract", model.StatusLocked),
		groupedClaim("w.c", "widget", "internals", model.StatusLocked),
		groupedClaim("w.d", "widget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.a": "", "w.b": "", "w.c": "", "w.d": ""}
	groups := buildGroups(cat, cfg, rendered)

	for _, g := range groups {
		switch g.Facet {
		case "contract":
			if !g.AllLocked {
				t.Errorf("contract group should be AllLocked=true: %#v", g)
			}
		case "internals":
			if g.AllLocked {
				t.Errorf("internals group should be AllLocked=false (one draft claim): %#v", g)
			}
		}
	}
}

func TestRender_GroupedClaimsWiredIntoModuleGroups(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusDraft),
		groupedClaim("w.b", "widget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	// buildGroups' output is not exposed on shellData directly — it only
	// feeds buildModuleGroups — so this exercises that wiring end to end via
	// Render: both claims must still reach the rendered output through the
	// ModuleGroups -> Facets -> Claims path shell.html actually ranges over.
	if !strings.Contains(out, "w.a") || !strings.Contains(out, "w.b") {
		t.Errorf("expected both claim ids to appear in rendered output:\n%s", out)
	}
}

// ---- orderClaims (fix 4: viewer display order) ------------------------

func TestOrderClaims_ExplicitOrderFirstThenSourcePathFallback(t *testing.T) {
	claim := func(id string, order int) model.Claim {
		return model.Claim{ID: id, Order: order}
	}
	// Incoming order is deliberately not sorted, to prove orderClaims does
	// the sorting rather than merely preserving input order.
	claims := []model.Claim{
		claim("no-order-a", 0),
		claim("order-5", 5),
		claim("no-order-b", 0),
		claim("order-2", 2),
	}

	got := orderClaims(claims)

	var gotIDs []string
	for _, c := range got {
		gotIDs = append(gotIDs, c.ID)
	}
	// order-2 and order-5 sort ascending by Order, ahead of every unordered
	// claim; the two unordered claims keep their incoming relative order
	// (no-order-a before no-order-b) as the stable fallback.
	want := []string{"order-2", "order-5", "no-order-a", "no-order-b"}
	if len(gotIDs) != len(want) {
		t.Fatalf("orderClaims IDs = %v, want %v", gotIDs, want)
	}
	for i := range want {
		if gotIDs[i] != want[i] {
			t.Errorf("orderClaims IDs = %v, want %v", gotIDs, want)
			break
		}
	}
}

func TestOrderClaims_EqualNonZeroOrderKeepsIncomingOrder(t *testing.T) {
	claim := func(id string, order int) model.Claim {
		return model.Claim{ID: id, Order: order}
	}
	// Two claims share the same non-zero Order; sort.SliceStable must keep
	// them in their incoming relative order rather than swapping them, and
	// the tied pair must still sort ahead of a lower explicit Order that
	// happens to appear earlier in the input.
	claims := []model.Claim{
		claim("order-3-first", 3),
		claim("order-1", 1),
		claim("order-3-second", 3),
	}

	got := orderClaims(claims)

	var gotIDs []string
	for _, c := range got {
		gotIDs = append(gotIDs, c.ID)
	}
	want := []string{"order-1", "order-3-first", "order-3-second"}
	if len(gotIDs) != len(want) {
		t.Fatalf("orderClaims IDs = %v, want %v", gotIDs, want)
	}
	for i := range want {
		if gotIDs[i] != want[i] {
			t.Errorf("orderClaims IDs = %v, want %v", gotIDs, want)
			break
		}
	}
}

func TestOrderClaims_OrderIsScopedPerSectionNotGlobal(t *testing.T) {
	claim := func(id, section string, order int) model.Claim {
		return model.Claim{ID: id, Section: section, Order: order}
	}
	// Two sections, each with its own locally-authored "order: 1, order: 2"
	// sequence, interleaved in SourcePath order the way two sibling section
	// subdirectories would load. A global Order sort would put both
	// "order: 1" claims first (one per section), splitting each section's
	// claims apart and making newGroup emit "section A" then "section B"
	// then "section A" again.
	claims := []model.Claim{
		claim("a1", "A", 1),
		claim("a2", "A", 2),
		claim("b1", "B", 1),
		claim("b2", "B", 2),
	}

	got := orderClaims(claims)

	var gotIDs []string
	for _, c := range got {
		gotIDs = append(gotIDs, c.ID)
	}
	want := []string{"a1", "a2", "b1", "b2"}
	if len(gotIDs) != len(want) {
		t.Fatalf("orderClaims IDs = %v, want %v", gotIDs, want)
	}
	for i := range want {
		if gotIDs[i] != want[i] {
			t.Errorf("orderClaims IDs = %v, want %v — sections must stay contiguous", gotIDs, want)
			break
		}
	}
}

func TestOrderClaims_DoesNotMutateInput(t *testing.T) {
	claims := []model.Claim{
		{ID: "b", Order: 0},
		{ID: "a", Order: 1},
	}
	_ = orderClaims(claims)
	if claims[0].ID != "b" || claims[1].ID != "a" {
		t.Errorf("orderClaims mutated its input slice: %#v", claims)
	}
}

// ---- newGroup section metadata -----------------------------------------

func sectionedClaim(id, module, facet, section string, order int) model.Claim {
	c := groupedClaim(id, module, facet, model.StatusDraft)
	c.Section = section
	c.Order = order
	return c
}

func TestNewGroup_SectionMetadataOrdersClaimsWithoutVisibleHeadings(t *testing.T) {
	claims := []model.Claim{
		sectionedClaim("w.a", "widget", "contract", "Alpha", 1),
		sectionedClaim("w.b", "widget", "contract", "Alpha", 2),
		sectionedClaim("w.c", "widget", "contract", "Beta", 3),
	}
	rendered := map[string]template.HTML{"w.a": "A", "w.b": "B", "w.c": "C"}
	g := newGroup("widget", "contract", claims, rendered)

	want := []template.HTML{
		"A", "B",
		"C",
	}
	if len(g.Claims) != len(want) {
		t.Fatalf("newGroup Claims = %#v, want %#v", g.Claims, want)
	}
	for i := range want {
		if g.Claims[i] != want[i] {
			t.Errorf("newGroup Claims[%d] = %q, want %q", i, g.Claims[i], want[i])
		}
	}
}

func TestNewGroup_NoSectionSetEmitsNoHeadings(t *testing.T) {
	claims := []model.Claim{
		sectionedClaim("w.a", "widget", "contract", "", 1),
		sectionedClaim("w.b", "widget", "contract", "", 2),
	}
	rendered := map[string]template.HTML{"w.a": "A", "w.b": "B"}
	g := newGroup("widget", "contract", claims, rendered)

	for _, h := range g.Claims {
		if strings.Contains(string(h), "section-heading") {
			t.Errorf("unset Section must never produce a heading, got Claims: %#v", g.Claims)
		}
	}
	if len(g.Claims) != 2 {
		t.Fatalf("newGroup Claims = %#v, want exactly the 2 rendered claims", g.Claims)
	}
}

func TestNewGroup_MixedSectionAndNoSectionClaimsStayInSemanticOrder(t *testing.T) {
	claims := []model.Claim{
		sectionedClaim("w.a", "widget", "contract", "Alpha", 1),
		sectionedClaim("w.b", "widget", "contract", "", 2),
		sectionedClaim("w.c", "widget", "contract", "Alpha", 3),
	}
	rendered := map[string]template.HTML{"w.a": "A", "w.b": "B", "w.c": "C"}
	g := newGroup("widget", "contract", claims, rendered)

	want := []template.HTML{
		"A", "B", "C",
	}
	if len(g.Claims) != len(want) {
		t.Fatalf("newGroup Claims = %#v, want %#v", g.Claims, want)
	}
	for i := range want {
		if g.Claims[i] != want[i] {
			t.Errorf("newGroup Claims[%d] = %q, want %q", i, g.Claims[i], want[i])
		}
	}
}

// ---- buildModuleGroups (fix 5: module -> facet two-level nav) ---------

func TestBuildModuleGroups_NilForEmptyGroups(t *testing.T) {
	if got := buildModuleGroups(nil); got != nil {
		t.Errorf("buildModuleGroups(nil) = %#v, want nil", got)
	}
}

func TestBuildModuleGroups_TwoLevelShape(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusDraft),
		groupedClaim("w.b", "widget", "internals", model.StatusDraft),
		groupedClaim("g.a", "gadget", "contract", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget", "gadget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.a": "A", "w.b": "B", "g.a": "G"}
	groups := buildGroups(cat, cfg, rendered)
	moduleGroups := buildModuleGroups(groups)

	if len(moduleGroups) != 2 {
		t.Fatalf("got %d module groups, want 2: %#v", len(moduleGroups), moduleGroups)
	}

	widget := moduleGroups[0]
	if widget.Module != "widget" || widget.ID != "widget" {
		t.Errorf("widget module group = %#v, want Module/ID == widget", widget)
	}
	if len(widget.Facets) != 3 {
		t.Fatalf("widget module group has %d tabs, want 3: %#v", len(widget.Facets), widget.Facets)
	}
	if widget.Facets[0].Facet != "manifest" || widget.Facets[1].Facet != "contract" || widget.Facets[2].Facet != "internals" {
		t.Errorf("widget tabs = [%s, %s, %s], want [manifest, contract, internals]", widget.Facets[0].Facet, widget.Facets[1].Facet, widget.Facets[2].Facet)
	}
	if widget.FirstFacetID != "widget-contract" {
		t.Errorf("FirstFacetID = %q, want widget-contract when Manifest is empty", widget.FirstFacetID)
	}

	gadget := moduleGroups[1]
	if gadget.Module != "gadget" || len(gadget.Facets) != 3 {
		t.Fatalf("gadget module group = %#v, want 3 peer tabs", gadget)
	}
}

func TestBuildModuleGroups_SingleFacetModuleSkipsSubNav(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusDraft),
		groupedClaim("w.b", "widget", "internals", model.StatusDraft),
		groupedClaim("g.a", "gadget", "contract", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget", "gadget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.a": "A", "w.b": "B", "g.a": "G"}
	moduleGroups := buildModuleGroups(buildGroups(cat, cfg, rendered))

	byModule := map[string]ModuleGroup{}
	for _, mg := range moduleGroups {
		byModule[mg.Module] = mg
	}

	if !byModule["widget"].HasSubNav {
		t.Errorf("widget has peer tabs, want HasSubNav=true: %#v", byModule["widget"])
	}
	if !byModule["gadget"].HasSubNav {
		t.Errorf("gadget must still show Manifest | Contract | Internals peers: %#v", byModule["gadget"])
	}
}

func TestBuildModuleGroups_PeerTabsManifestContractInternals(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.c", "widget", "contract", model.StatusDraft),
		groupedClaim("w.i", "widget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{
		Modules: []string{"widget"},
		Facets:  []string{"contract", "internals"},
	}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.c": "C", "w.i": "I"}
	moduleGroups := buildModuleGroups(buildGroups(cat, cfg, rendered))

	if len(moduleGroups) != 1 {
		t.Fatalf("got %d module groups, want 1: %#v", len(moduleGroups), moduleGroups)
	}

	widget := moduleGroups[0]
	if len(widget.Facets) != 3 {
		t.Fatalf("widget module group has %d tabs, want 3: %#v", len(widget.Facets), widget.Facets)
	}
	wantOrder := []string{"manifest", "contract", "internals"}
	gotOrder := make([]string, len(widget.Facets))
	for i, f := range widget.Facets {
		gotOrder[i] = f.Facet
	}
	if !slices.Equal(gotOrder, wantOrder) {
		t.Errorf("widget tab order = %v, want %v", gotOrder, wantOrder)
	}
	if widget.FirstFacetID != "widget-contract" {
		t.Errorf("FirstFacetID = %q, want widget-contract when Manifest is empty", widget.FirstFacetID)
	}
	if !widget.HasSubNav {
		t.Errorf("peer tabs require HasSubNav=true: %#v", widget)
	}
}

func TestBuildModuleGroups_AllLockedRequiresEveryFacetLocked(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusLocked),
		groupedClaim("w.b", "widget", "internals", model.StatusLocked),
		groupedClaim("g.a", "gadget", "contract", model.StatusLocked),
		groupedClaim("g.b", "gadget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget", "gadget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.a": "", "w.b": "", "g.a": "", "g.b": ""}
	moduleGroups := buildModuleGroups(buildGroups(cat, cfg, rendered))

	byModule := map[string]ModuleGroup{}
	for _, mg := range moduleGroups {
		byModule[mg.Module] = mg
	}

	if !byModule["widget"].AllLocked {
		t.Errorf("widget: both facets fully locked, want AllLocked=true: %#v", byModule["widget"])
	}
	if byModule["gadget"].AllLocked {
		t.Errorf("gadget: internals facet has a draft claim, want AllLocked=false: %#v", byModule["gadget"])
	}
}

func TestBuildModuleGroups_LockCountsOnTwoFacetLockedModule(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusLocked),
		groupedClaim("w.b", "widget", "contract", model.StatusLocked),
		groupedClaim("w.c", "widget", "internals", model.StatusLocked),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{"w.a": "", "w.b": "", "w.c": ""}
	moduleGroups := buildModuleGroups(buildGroups(cat, cfg, rendered))
	if len(moduleGroups) != 1 {
		t.Fatalf("module groups = %d, want 1", len(moduleGroups))
	}
	got := moduleGroups[0]
	if got.ClaimCount != 3 || got.LockedCount != 3 || got.FacetCount != 3 {
		t.Fatalf("widget counts = claims %d locked %d facets %d, want 3/3/3", got.ClaimCount, got.LockedCount, got.FacetCount)
	}
}

func TestRender_ModuleSectionLockMetricAttrs(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusLocked),
		groupedClaim("w.b", "widget", "internals", model.StatusLocked),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatal(err)
	}
	out, err := Render(cat, cfg)
	if err != nil {
		t.Fatal(err)
	}
	for _, want := range []string{
		`data-claim-count="2"`,
		`data-locked-count="2"`,
		`data-facet-count="3"`,
	} {
		if !strings.Contains(out, want) {
			t.Fatalf("rendered module section missing %q", want)
		}
	}
}

func TestOrderedNames_EmptyPresentReturnsNil(t *testing.T) {
	if got := orderedNames([]string{"a", "b"}, nil); got != nil {
		t.Errorf("orderedNames(preferred, nil) = %#v, want nil", got)
	}
}

func TestSlugify(t *testing.T) {
	cases := map[string]string{
		"widget-contract":   "widget-contract",
		"Widget Contract":   "widget-contract",
		"widget/contract!!": "widget-contract",
		"  spaced  ":        "spaced",
	}
	for in, want := range cases {
		if got := slugify(in); got != want {
			t.Errorf("slugify(%q) = %q, want %q", in, got, want)
		}
	}
}

// TestRender_ShellOverrideUsedInsteadOfEmbeddedDefault proves an override
// dir containing a custom shell.html is used instead of the embedded
// default, mirroring the existing per-component override test above but
// for the outer shell.
func TestRender_ShellOverrideUsedInsteadOfEmbeddedDefault(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir+"/shell.html", `<!doctype html><html><body class="custom-shell-marker">{{range .ModuleGroups}}{{range .Facets}}{{range .Claims}}{{.}}{{end}}{{end}}{{end}}</body></html>`)

	cfg := &config.Config{Viewer: config.Viewer{TemplateOverrides: dir}}
	cat, err := catalog.Build([]model.Claim{claimFor(model.LayoutCard)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(out, "custom-shell-marker") {
		t.Errorf("expected overridden shell.html to be used:\n%s", out)
	}
	if strings.Contains(out, "shell-body") {
		t.Errorf("overridden shell should not also render the embedded default shell's markup:\n%s", out)
	}
}

// TestRender_ShellAndStyleOverrideMissingFallsBackToDefaults proves an
// override dir that exists but contains neither shell.html nor style.css
// falls back to the embedded defaults for both without erroring — the same
// soft-fallback semantics the component loader already has, extended here
// to shell.html/style.css.
func TestRender_ShellAndStyleOverrideMissingFallsBackToDefaults(t *testing.T) {
	dir := t.TempDir() // exists, but empty: no shell.html, no style.css, no partials

	cfg := &config.Config{Viewer: config.Viewer{TemplateOverrides: dir}}
	cat, err := catalog.Build([]model.Claim{claimFor(model.LayoutCard)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(out, "<!doctype html>") {
		t.Errorf("expected default shell doctype when no shell.html override present:\n%s", out)
	}
	if strings.Contains(out, "custom-shell-marker") {
		t.Errorf("did not expect any override marker when override dir has no shell.html:\n%s", out)
	}
	if !strings.Contains(out, "<style>") {
		t.Errorf("expected default style.css to be embedded when no style.css override present:\n%s", out)
	}
}

// TestShellHasViewerRuntime_DefaultAndOverride exercises the live-viewer
// runtime detector "dossierx serve" uses to decide read-only vs. live: the
// embedded default shell (also the nil-cfg and no-shell-override fallbacks) must
// carry ViewerRuntimeMarker; an override that keeps the marker reports true; one
// that drops it reports false so serve can degrade. This also guards the marker
// against silent removal from the embedded shell.html.
func TestShellHasViewerRuntime_DefaultAndOverride(t *testing.T) {
	// nil cfg -> embedded default -> carries the runtime marker.
	if has, err := ShellHasViewerRuntime(nil); err != nil || !has {
		t.Fatalf("ShellHasViewerRuntime(nil) = (%v, %v); embedded default must carry the %q marker", has, err, ViewerRuntimeMarker)
	}

	// Override dir with no shell.html -> falls back to the marker-bearing default.
	empty := t.TempDir()
	if has, err := ShellHasViewerRuntime(&config.Config{Viewer: config.Viewer{TemplateOverrides: empty}}); err != nil || !has {
		t.Fatalf("no-shell-override fallback = (%v, %v); want (true, nil)", has, err)
	}

	// Override that KEEPS the marker -> true.
	withMarker := t.TempDir()
	writeFile(t, withMarker+"/shell.html",
		`<!doctype html><html><head><meta name="`+ViewerRuntimeMarker+`" content="x"></head><body>{{range .ModuleGroups}}{{end}}</body></html>`)
	if has, err := ShellHasViewerRuntime(&config.Config{Viewer: config.Viewer{TemplateOverrides: withMarker}}); err != nil || !has {
		t.Fatalf("marker-bearing override = (%v, %v); want (true, nil)", has, err)
	}

	// Override that DROPS the marker -> false (serve degrades to read-only).
	noMarker := t.TempDir()
	writeFile(t, noMarker+"/shell.html",
		`<!doctype html><html><head></head><body class="custom">{{range .ModuleGroups}}{{end}}</body></html>`)
	if has, err := ShellHasViewerRuntime(&config.Config{Viewer: config.Viewer{TemplateOverrides: noMarker}}); err != nil || has {
		t.Fatalf("marker-less override = (%v, %v); want (false, nil)", has, err)
	}
}

// TestRender_StyleOverrideUsedInsteadOfEmbeddedDefault proves an override
// dir containing a custom style.css is used instead of the embedded
// default stylesheet.
func TestRender_StyleOverrideUsedInsteadOfEmbeddedDefault(t *testing.T) {
	dir := t.TempDir()
	writeFile(t, dir+"/style.css", `.custom-style-marker{color:red}`)

	cfg := &config.Config{Viewer: config.Viewer{TemplateOverrides: dir}}
	cat, err := catalog.Build([]model.Claim{claimFor(model.LayoutCard)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if !strings.Contains(out, "custom-style-marker") {
		t.Errorf("expected overridden style.css to be used:\n%s", out)
	}
}

func TestRender_OverrideDirMissingEntirelyErrors(t *testing.T) {
	const missingPath = "/nonexistent/does-not-exist-dir"
	cfg := &config.Config{Viewer: config.Viewer{TemplateOverrides: missingPath}}
	cat, err := catalog.Build([]model.Claim{claimFor(model.LayoutCard)}, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	_, err = Render(cat, cfg)
	if err == nil {
		t.Fatalf("Render: expected hard error for missing override directory, got nil")
	}
	if !strings.Contains(err.Error(), missingPath) {
		t.Errorf("Render error should name the missing override path %q, got: %v", missingPath, err)
	}
}

func TestBuildGroups_UndeclaredFacetIsUngroupedNotInjected(t *testing.T) {
	leftover := groupedClaim("w.overview.router", "widget", "overview", model.StatusDraft)
	claims := []model.Claim{
		leftover,
		groupedClaim("w.a", "widget", "contract", model.StatusDraft),
		groupedClaim("w.b", "widget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	rendered := map[string]template.HTML{
		"w.overview.router": "LEFTOVER",
		"w.a":               "A",
		"w.b":               "B",
	}
	groups := buildGroups(cat, cfg, rendered)

	if len(groups) != 4 {
		t.Fatalf("got %d groups, want 3 peer tabs plus ungrouped leftover: %#v", len(groups), groups)
	}
	var leftoverCount int
	for _, g := range groups {
		if g.Facet == "overview" {
			t.Fatalf("overview must not become a reserved tab: %#v", groups)
		}
		for _, html := range g.Claims {
			if html == template.HTML("LEFTOVER") {
				leftoverCount++
			}
		}
	}
	if leftoverCount != 1 {
		t.Fatalf("undeclared leftover claim copies = %d, want 1 (ungrouped, not injected): %#v", leftoverCount, groups)
	}
}

func TestBuildGroups_PeerTabsAreManifestContractInternals(t *testing.T) {
	claims := []model.Claim{
		groupedClaim("w.a", "widget", "contract", model.StatusDraft),
		groupedClaim("w.b", "widget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	groups := buildGroups(cat, cfg, map[string]template.HTML{"w.a": "A", "w.b": "B"})
	if len(groups) != 3 {
		t.Fatalf("got %d groups, want 3 peer tabs: %#v", len(groups), groups)
	}
	want := []string{visibility.ViewerTabManifest, "contract", "internals"}
	for i, g := range groups {
		if g.Facet != want[i] {
			t.Fatalf("group %d facet = %q, want %q: %#v", i, g.Facet, want[i], groups)
		}
	}
}

func TestRender_ClaimBodyAppearsOncePerClaim(t *testing.T) {
	note := model.Claim{
		ID:      "widget.contract.router",
		Module:  "widget",
		Facet:   "contract",
		Status:  model.StatusDraft,
		Layout:  model.LayoutCard,
		Body:    "CONTRACT-BODY",
		RestsOn: model.RestsNone("test fixture"),
	}
	claims := []model.Claim{
		note,
		groupedClaim("widget.internals.b", "widget", "internals", model.StatusDraft),
	}
	cfg := &config.Config{Modules: []string{"widget"}, Facets: []string{"contract", "internals"}}
	cat, err := catalog.Build(claims, nil)
	if err != nil {
		t.Fatalf("catalog.Build: %v", err)
	}
	out, err := Render(cat, cfg)
	if err != nil {
		t.Fatalf("Render: %v", err)
	}
	if got := strings.Count(out, ` id="widget.contract.router"`); got != 1 {
		t.Fatalf("canonical id appears %d times, want 1:\n%s", got, out)
	}
	if got := strings.Count(out, "CONTRACT-BODY"); got != 1 {
		t.Fatalf("claim body appears %d times, want 1 (no facet-tab injection):\n%s", got, out)
	}
}
