// Package render turns a built catalog.Catalog into the viewer's
// index.html. The shell + CSS live under viewer/template/ and are embedded
// into the binary via go:embed, with soft-fallback overrides for
// shell.html/style.css sourced from cfg.Viewer.TemplateOverrides (see
// components.OverrideFile); per-layout partials live in the components/
// subpackage and are selected via a plain map lookup on each claim's Layout
// — no per-project branching lives here or in components.
package render

import (
	"bytes"
	"embed"
	"fmt"
	"html/template"
	"sort"
	"strings"
	"time"

	"github.com/BarterX-Tech/dossierx/internal/buildorder"
	"github.com/BarterX-Tech/dossierx/internal/catalog"
	"github.com/BarterX-Tech/dossierx/internal/config"
	"github.com/BarterX-Tech/dossierx/internal/model"
	"github.com/BarterX-Tech/dossierx/internal/render/components"
)

//go:embed viewer/template/shell.html viewer/template/style.css
var shellFS embed.FS

// shellFileName and styleFileName are the override-lookup names for the
// shell template and stylesheet respectively (see components.OverrideFile),
// and also the leaf names of their embedded viewer/template/ counterparts
// below. They are hoisted into constants — rather than repeated as string
// literals at each use site — so a future rename of either file only has to
// change one place instead of staying manually in sync across the
// OverrideFile lookup, the template.New name, and the embedded path.
const (
	shellFileName = "shell.html"
	styleFileName = "style.css"
)

// shellTemplatePath and styleTemplatePath are the embedded paths backing the
// go:embed directive above; embed.FS.ReadFile/ParseFS calls below reference
// these constants (viewer/template/ + the corresponding *FileName constant)
// instead of repeating the path as a separate literal.
const (
	shellTemplatePath = "viewer/template/" + shellFileName
	styleTemplatePath = "viewer/template/" + styleFileName
)

// generatedHeader returns the comment prepended to every rendered document
// ahead of the shell template's own output, stamped with the render time
// (UTC, RFC3339) so provenance in the emitted HTML is unambiguous. It is
// built in Go, not baked into shell.html, because html/template silently
// strips literal HTML comments out of parsed templates as part of its
// escaping pass — a header comment placed inside the template source would
// never reach the rendered output.
func generatedHeader() string {
	return fmt.Sprintf("<!-- generated by dossierx render at %s — do not edit. Re-run \"dossierx render\" to regenerate. -->\n", time.Now().UTC().Format(time.RFC3339))
}

type shellData struct {
	Title string
	// Eyebrow is cfg.Eyebrow verbatim, rendered as a one-line subtitle under
	// Title in the sidebar header. Empty means shell.html renders no eyebrow
	// element at all (unlike Title, there is no generic fallback text).
	Eyebrow string
	CSS     template.CSS
	// ThemeCSS is a second, optional :root{...} block built from
	// cfg.Viewer.Theme (see themeOverrideCSS). shell.html emits it in a
	// <style> block immediately after the one carrying CSS, and after
	// style.css's own @media (prefers-color-scheme: light) block, so any
	// project-supplied token wins over the engine default in both OS color
	// modes, per-token (unset tokens keep falling back to style.css's own
	// defaults via normal cascade). Empty when the project sets no theme.
	ThemeCSS template.CSS

	// ModuleGroups is cat.Claims folded into the two-level Module -> []Facet
	// shape fix 5 describes (one sidebar entry per module, a nested
	// .sub-nav/.subtab strip per module with more than one facet), computed
	// by buildModuleGroups from the flat, facet-level Groups buildGroups
	// produces. shell.html ranges exclusively over ModuleGroups (and each
	// entry's nested Facets) — the flat Groups slice is not exposed on
	// shellData; it exists only as buildModuleGroups' internal input so the
	// module/facet nav ordering logic in buildGroups stays the single source
	// of truth without being duplicated here.
	ModuleGroups []ModuleGroup
}

// Group is one module/facet section of the sidebar nav + content area, as
// described in NAV_SPEC. A claim whose module and/or facet is empty or not
// recognized by the project config lands in a single catch-all group with
// Module == ungroupedModuleName instead of being dropped.
type Group struct {
	// Module and Facet are the raw (unslugified) group keys, suitable for
	// display labels. Module == ungroupedModuleName and Facet == "" for the
	// catch-all bucket.
	Module string
	Facet  string
	// ID is a URL/HTML-id-safe slug of "<module>-<facet>" (or just
	// "<module>" when Facet is empty), used as both the claim-group
	// section id and the sec-tab's data-target/hash.
	ID string
	// Claims are this group's claims, already rendered via the existing
	// per-layout partials, ordered per orderClaims (explicit Order first,
	// then a stable SourcePath-order fallback for everything else).
	Claims []template.HTML
	// AllLocked is true only when the group is non-empty and every claim in
	// it has Status == locked; it drives an optional lock-indicator suffix
	// on the nav label. A group can never be empty in practice (it only
	// exists because at least one claim produced it), but the check is
	// written defensively regardless.
	AllLocked bool
	// ModuleLabel is a display-cased version of Module, used for the
	// sec-label heading shown once per module run.
	ModuleLabel string
	// TabLabel is a display-cased version of Facet (or of Module when Facet
	// is empty, e.g. the ungrouped catch-all bucket), used as the sec-tab's
	// button text.
	TabLabel string
	// firstInModule is true for the first group of each consecutive module
	// run in buildGroups' output. It is unexported (rather than
	// FirstInModule) precisely because it is not part of the template-facing
	// contract: no shell.html or partial ever ranges over a []Group and
	// reads this field, only buildModuleGroups does, in the same package, to
	// find each run's start when folding Groups into ModuleGroups. Keeping
	// it unexported makes that "internal plumbing only" claim something the
	// compiler enforces (a template accessing it would fail at execute time)
	// rather than something only a comment asserts.
	firstInModule bool
}

// ModuleGroup is one module's sidebar nav entry together with the one or
// more facet-level Groups shown inside its content section — the two-level
// Module -> []Facet shape fix 5 describes (docs/'s real nav has one sec-tab
// per MODULE; a module with more than one facet gets a secondary
// .sub-nav/.subtab strip inside its content area instead of one flat
// sidebar entry per module+facet pair). It is built by buildModuleGroups
// from the same flat, already-ordered Groups buildGroups produces, so the
// module/facet nav ordering logic in buildGroups stays the single source of
// truth and is not duplicated here.
type ModuleGroup struct {
	// Module is the raw (unslugified) module key; Module ==
	// ungroupedModuleName for the catch-all bucket, matching Group.Module.
	Module string
	// ModuleLabel is the display-cased Module, used for the sidebar's
	// module-level sec-tab label. It is copied from the first Facet rather
	// than recomputed, so ModuleGroup never disagrees with its own Facets
	// about what a module's display name is.
	ModuleLabel string
	// ID is slugify(Module) alone — never "module-facet" — used as the
	// module-level sec-tab's data-target/hash. It intentionally does not
	// have to equal Facets[0].ID (that ID may carry a facet suffix even for
	// a single-facet module); resolving a bare "#module" hash to
	// FirstFacetID's section is the later shell.html step's job.
	ID string
	// Facets are this module's facet-level groups, already in the nav
	// order buildGroups computed for them (declared facets first, then any
	// remaining present facets alphabetically). Always non-empty — a
	// ModuleGroup only ever exists because at least one Group produced it.
	Facets []Group
	// FirstFacetID is Facets[0].ID — the facet section that should render
	// visible-by-default when this module's sec-tab is chosen, whether by
	// click or by a bare "#module" hash with no facet suffix.
	FirstFacetID string
	// HasSubNav is true only when len(Facets) > 1. A module with exactly
	// one facet renders no .sub-nav/.subtab strip at all — there is
	// nothing to switch between — per fix 5's "skip the sub-nav entirely
	// for a module with exactly 1 facet" requirement.
	HasSubNav bool
	// AllLocked is true only when every facet in Facets has AllLocked ==
	// true (which itself requires every claim within that facet to be
	// locked). It drives the same optional lock-indicator suffix on the
	// module-level nav label that Group.AllLocked drives per facet.
	AllLocked bool

	// BuildOrderHTML is the pre-rendered (via build_order.html)
	// Build Order section for this module, non-empty only when it has a
	// LOCKED internal/buildorder.Artifact on disk (see attachBuildOrders).
	// A project that has never proposed/locked one for this module (the
	// common case for any project that hasn't adopted the build-order
	// feature at all) leaves this "", and shell.html renders nothing extra
	// for it, per this optional feature's graceful-degradation contract: a
	// project must never see a broken or partial viewer just because it
	// hasn't opted into build_role/build-order. Pre-rendered here (rather
	// than exposing the raw artifact to shell.html) for the same reason
	// Group.Claims is already a []template.HTML rather than []model.Claim:
	// shell.html is one standalone parsed template with no access to
	// component partials of its own.
	BuildOrderHTML template.HTML
}

// buildOrderView pairs one module's locked build-order artifact with the
// display-cased module label build_order.html renders as its heading — the
// same "raw key + display label" pairing ModuleGroup.Module/ModuleLabel
// already does for the ordinary claim nav, kept as its own small type
// rather than added directly to ModuleGroup's own fields because
// build_order.html is executed against exactly this shape (see
// renderBuildOrderHTML), independent of Group/ModuleGroup's much larger
// claims-nav shape.
type buildOrderView struct {
	ModuleLabel string
	Artifact    *buildorder.Artifact
}

// buildModuleGroups folds buildGroups' flat, facet-level Groups into the
// two-level ModuleGroup shape above: one ModuleGroup per consecutive run of
// same-Module Groups. It trusts Group.firstInModule (already computed by
// buildGroups) to find each run's boundary instead of re-deriving "did the
// module change" here — buildGroups already guarantees a given module's
// Groups are contiguous in its output. groups and firstInModule are purely
// an internal handoff between the two functions: shell.html never sees a
// []Group directly, only the ModuleGroups this returns. Returns nil for
// nil/empty groups.
func buildModuleGroups(groups []Group) []ModuleGroup {
	if len(groups) == 0 {
		return nil
	}

	var out []ModuleGroup
	for _, g := range groups {
		if g.firstInModule {
			out = append(out, ModuleGroup{
				Module:      g.Module,
				ModuleLabel: g.ModuleLabel,
				ID:          slugify(g.Module),
			})
		}
		last := &out[len(out)-1]
		last.Facets = append(last.Facets, g)
	}

	for i := range out {
		out[i].HasSubNav = len(out[i].Facets) > 1
		out[i].FirstFacetID = out[i].Facets[0].ID

		allLocked := true
		for _, f := range out[i].Facets {
			if !f.AllLocked {
				allLocked = false
				break
			}
		}
		out[i].AllLocked = allLocked
	}

	return out
}

// attachBuildOrders populates ModuleGroup.BuildOrderHTML for every module in
// groups that has a LOCKED internal/buildorder.Artifact on disk (via
// buildorder.ArtifactPath(cfg, module) + buildorder.LoadArtifact), leaving
// it "" (the zero value) for every other module — this is the optional
// Build Order viewer tab's entire graceful-degradation contract: a project
// that has never run "docs build-order propose"/"lock" for a module (which
// is every project that hasn't adopted model.BuildRole at all, and every
// module of a project that has adopted it but not finished locking it)
// sees Render produce byte-for-byte the same output it always has, because
// this function attaches nothing for it.
//
// Any error from LoadArtifact — no artifact proposed yet (the overwhelming
// common case), a corrupt/malformed artifact file, anything — is treated
// exactly the same way: skip that module's build order silently rather
// than fail Render. This is deliberate: a build-order artifact is a
// generated-and-regenerable side file (like .catalog.json), never
// hand-edited, so a problem with it is never a reason to break the
// viewer render entirely for a project that may not even know the file
// exists. Only a genuinely LOCKED artifact (artifact.Locked == true) is
// ever attached — a merely-proposed-but-not-yet-locked artifact is still
// a draft-quality computation a reviewer hasn't confirmed, so it isn't
// shown any more than a draft claim's content would be hidden, just not
// promoted to this locked-only, human-confirmed viewer surface.
//
// cfg == nil or buildOrderTmpl == nil (should not happen via loadTemplates,
// but this stays defensive like the rest of this file) makes this a no-op.
func attachBuildOrders(groups []ModuleGroup, cfg *config.Config, buildOrderTmpl *template.Template) []ModuleGroup {
	if cfg == nil || buildOrderTmpl == nil {
		return groups
	}

	for i := range groups {
		path := buildorder.ArtifactPath(cfg, groups[i].Module)
		artifact, err := buildorder.LoadArtifact(path)
		if err != nil || !artifact.Locked {
			continue
		}

		view := buildOrderView{ModuleLabel: groups[i].ModuleLabel, Artifact: artifact}
		var buf bytes.Buffer
		if err := buildOrderTmpl.Execute(&buf, view); err != nil {
			continue // never fail Render over a build-order rendering hiccup.
		}
		groups[i].BuildOrderHTML = template.HTML(buf.String())
	}

	return groups
}

// ungroupedModuleName is the catch-all bucket's Module value for claims
// whose module and/or facet is empty or not declared in the project config.
const ungroupedModuleName = "ungrouped"

// Render builds the full viewer/index.html document for cat and returns it
// as a string. It never panics on an empty catalog: Render(&catalog.Catalog{}, cfg)
// returns a valid, claim-less document.
//
// The work is split into three independently testable stages: loadTemplates
// resolves every override-able input (component partials, CSS, the shell
// template itself) against cfg.Viewer.TemplateOverrides; renderClaims turns
// each catalog claim into HTML via those partials; buildShellData assembles
// the resulting shellData (title/eyebrow/groups) ready for shell.Execute.
// Render itself is left as the sequencing of those three calls plus the
// final template execution, so a future fourth input or grouping level only
// has to touch the stage it belongs to.
func Render(cat *catalog.Catalog, cfg *config.Config) (string, error) {
	if cat == nil {
		cat = &catalog.Catalog{}
	}

	overrideDir := ""
	if cfg != nil {
		overrideDir = cfg.Viewer.TemplateOverrides
	}

	tmpl, err := loadTemplates(overrideDir)
	if err != nil {
		return "", err
	}

	// Optional, graceful-degradation-by-default extensions of the shared
	// edges footer — see implink_view.go and depended_by_view.go's doc
	// comments for why this is a no-op for a project that has never
	// called "docs implink set" and has no claim any other claim rests
	// on.
	attachEdgesOverride(tmpl.partials, buildImplinkLookup(cfg), buildDependedByLookup(cat))

	renderedByID, err := renderClaims(cat, tmpl.partials)
	if err != nil {
		return "", err
	}

	data := buildShellData(cat, cfg, tmpl.css, renderedByID, tmpl.buildOrder)

	var out bytes.Buffer
	if err := tmpl.shell.Execute(&out, data); err != nil {
		return "", fmt.Errorf("render: execute shell template: %w", err)
	}

	return generatedHeader() + out.String(), nil
}

// loadedTemplates bundles every override-able render input resolved by
// loadTemplates: the per-layout component partials, the stylesheet bytes,
// and the parsed shell template. Grouping them lets loadTemplates return a
// single value instead of Render having to thread three separate return
// values through to their eventual use sites.
type loadedTemplates struct {
	partials map[model.Layout]*template.Template
	css      []byte
	shell    *template.Template
	// buildOrder is the Build Order viewer partial (components.LoadBuildOrder),
	// loaded unconditionally like every other partial above — whether it is
	// ever executed depends on attachBuildOrders finding at least one
	// module with a locked build-order artifact, not on anything here.
	buildOrder *template.Template
}

// loadTemplates resolves all of Render's template and CSS inputs, applying
// the project's override directory (overrideDir, from
// cfg.Viewer.TemplateOverrides) over the engine's embedded defaults: a
// project may override style.css and/or shell.html independently, and falls
// back to the embedded copy of each when it does not.
func loadTemplates(overrideDir string) (loadedTemplates, error) {
	partials, err := components.Load(overrideDir)
	if err != nil {
		return loadedTemplates{}, fmt.Errorf("render: load component templates: %w", err)
	}

	buildOrderTmpl, err := components.LoadBuildOrder(overrideDir)
	if err != nil {
		return loadedTemplates{}, fmt.Errorf("render: load build_order template: %w", err)
	}

	css, cssOverridden, err := components.OverrideFile(overrideDir, styleFileName)
	if err != nil {
		return loadedTemplates{}, fmt.Errorf("render: load %s override: %w", styleFileName, err)
	}
	if !cssOverridden {
		css, err = shellFS.ReadFile(styleTemplatePath)
		if err != nil {
			return loadedTemplates{}, fmt.Errorf("render: load default stylesheet: %w", err)
		}
	}

	shellSrc, shellOverridden, err := components.OverrideFile(overrideDir, shellFileName)
	if err != nil {
		return loadedTemplates{}, fmt.Errorf("render: load %s override: %w", shellFileName, err)
	}
	var shell *template.Template
	if shellOverridden {
		shell, err = template.New(shellFileName).Parse(string(shellSrc))
		if err != nil {
			return loadedTemplates{}, fmt.Errorf("render: parse shell template override: %w", err)
		}
	} else {
		shell, err = template.ParseFS(shellFS, shellTemplatePath)
		if err != nil {
			return loadedTemplates{}, fmt.Errorf("render: parse shell template: %w", err)
		}
	}

	return loadedTemplates{partials: partials, css: css, shell: shell, buildOrder: buildOrderTmpl}, nil
}

// renderClaims executes each cat.Claims entry through its layout's partial
// template in partials (as loaded by loadTemplates), returning a
// claim-ID-keyed lookup (renderedByID, consumed by buildGroups/newGroup) so
// a claim is rendered exactly once regardless of how many places reference
// it afterwards. shell.html has no top-level "all claims, unordered" view
// (it renders exclusively via ModuleGroups' nested Facets[].Claims), so
// renderClaims does not also keep a flat catalog-order slice around for it.
func renderClaims(cat *catalog.Catalog, partials map[model.Layout]*template.Template) (map[string]template.HTML, error) {
	renderedByID := make(map[string]template.HTML, len(cat.Claims))
	for _, c := range cat.Claims {
		tmpl, ok := partials[c.Layout]
		if !ok {
			return nil, fmt.Errorf("render: claim %q has unsupported layout %q", c.ID, c.Layout)
		}
		var buf bytes.Buffer
		if err := tmpl.Execute(&buf, c); err != nil {
			return nil, fmt.Errorf("render: claim %q: %w", c.ID, err)
		}
		renderedByID[c.ID] = template.HTML(buf.String())
	}
	return renderedByID, nil
}

// buildShellData assembles the shellData passed to shell.Execute: cfg's
// title/eyebrow/theme (with the same fallbacks Render has always applied
// when cfg is nil or leaves a field blank) and the module/facet groups
// computed from cat via buildGroups/buildModuleGroups, combined with the
// css/renderedByID inputs loadTemplates and renderClaims already produced.
// buildOrderTmpl is only ever used by attachBuildOrders, and only for a
// module that actually has a locked build-order artifact on disk — see
// that function's doc comment for the graceful-degradation contract this
// preserves for every project that hasn't adopted the feature.
//
// Unlike the rest of Render's inputs, attachBuildOrders below does perform
// I/O (reading each module's build-order artifact file, if any) — the same
// already-established precedent as loadTemplates' own override-directory
// reads, just keyed by module instead of by override filename.
func buildShellData(cat *catalog.Catalog, cfg *config.Config, css []byte, renderedByID map[string]template.HTML, buildOrderTmpl *template.Template) shellData {
	var theme map[string]string
	if cfg != nil {
		theme = cfg.Viewer.Theme
	}

	// groups is buildModuleGroups' input only — the flat, facet-level
	// grouping is not exposed on shellData (shell.html renders exclusively
	// via ModuleGroups below).
	groups := buildGroups(cat, cfg, renderedByID)
	moduleGroups := buildModuleGroups(groups)
	moduleGroups = attachBuildOrders(moduleGroups, cfg, buildOrderTmpl)

	title := "docs viewer"
	eyebrow := ""
	if cfg != nil {
		if strings.TrimSpace(cfg.Title) != "" {
			title = cfg.Title
		}
		eyebrow = strings.TrimSpace(cfg.Eyebrow)
	}

	return shellData{
		Title:        title,
		Eyebrow:      eyebrow,
		CSS:          template.CSS(css),
		ThemeCSS:     themeOverrideCSS(theme),
		ModuleGroups: moduleGroups,
	}
}

// themeOverrideCSS builds a single ":root{...}" block from theme, one
// "--<key>:<value>;" declaration per present, allowlisted key. Keys are
// iterated in config.ThemeTokenAllowlist's fixed order — not theme's own
// map iteration order, which Go randomizes — so output is deterministic
// across runs for the same input. An empty or nil theme (or one with no
// allowlisted keys, which validateTheme should never actually allow through
// but this stays defensive) returns "" rather than an empty ":root{}" rule:
// there is nothing useful to emit, so nothing is emitted.
func themeOverrideCSS(theme map[string]string) template.CSS {
	if len(theme) == 0 {
		return ""
	}

	var b strings.Builder
	wrote := false
	for _, key := range config.ThemeTokenAllowlist {
		val, ok := theme[key]
		if !ok {
			continue
		}
		if !wrote {
			b.WriteString(":root{")
			wrote = true
		}
		b.WriteString("--")
		b.WriteString(key)
		b.WriteString(":")
		b.WriteString(val)
		b.WriteString(";")
	}
	if !wrote {
		return ""
	}
	b.WriteString("}")

	return template.CSS(b.String())
}

// buildGroups computes the module -> facet grouping described in NAV_SPEC.
// It never panics on an empty or nil catalog (returns nil groups) and never
// drops a claim: any claim whose module and/or facet is empty or not
// recognized by cfg lands in a single catch-all ungroupedModuleName group
// instead of being silently discarded.
func buildGroups(cat *catalog.Catalog, cfg *config.Config, renderedByID map[string]template.HTML) []Group {
	if cat == nil || len(cat.Claims) == 0 {
		return nil
	}

	var declaredModules, declaredFacets []string
	if cfg != nil {
		declaredModules = cfg.Modules
		declaredFacets = cfg.Facets
	}

	knownModule, knownFacet := newMembershipPredicates(declaredModules, declaredFacets)

	type groupKey struct{ module, facet string }
	claimsByKey := map[groupKey][]model.Claim{}
	overviewByModule := map[string][]model.Claim{}
	moduleSeen := map[string]bool{}
	facetSeenByModule := map[string]map[string]bool{}
	var ungrouped []model.Claim

	for _, c := range cat.Claims {
		if c.Facet == config.ReservedOverviewFacet && knownModule(c.Module) {
			overviewByModule[c.Module] = append(overviewByModule[c.Module], c)
			moduleSeen[c.Module] = true
			continue
		}
		if !knownModule(c.Module) || !knownFacet(c.Facet) {
			ungrouped = append(ungrouped, c)
			continue
		}
		k := groupKey{c.Module, c.Facet}
		claimsByKey[k] = append(claimsByKey[k], c)
		moduleSeen[c.Module] = true
		if facetSeenByModule[c.Module] == nil {
			facetSeenByModule[c.Module] = map[string]bool{}
		}
		facetSeenByModule[c.Module][c.Facet] = true
	}

	var groups []Group
	for _, m := range orderedNames(declaredModules, moduleSeen) {
		overviewHTML := renderOverviewHTML(model.OrderClaims(overviewByModule[m]), renderedByID)
		for _, f := range orderedNames(declaredFacets, facetSeenByModule[m]) {
			groups = append(groups, newGroup(m, f, claimsByKey[groupKey{m, f}], renderedByID, overviewHTML))
		}
	}

	if len(ungrouped) > 0 {
		groups = append(groups, newGroup(ungroupedModuleName, "", ungrouped, renderedByID, nil))
	}

	markFirstInModule(groups)

	return groups
}

// renderOverviewHTML pulls the already-rendered HTML (from renderedByID,
// keyed by claim ID, same lookup newGroup itself uses) for a module's
// overview claims, in the given order. It never re-renders — renderClaims
// already rendered every catalog claim, including overview-facet ones,
// exactly once.
func renderOverviewHTML(overview []model.Claim, renderedByID map[string]template.HTML) []template.HTML {
	if len(overview) == 0 {
		return nil
	}
	out := make([]template.HTML, 0, len(overview))
	for _, c := range overview {
		out = append(out, renderedByID[c.ID])
	}
	return out
}

// newMembershipPredicates builds the knownModule/knownFacet predicates used
// by buildGroups to decide whether a claim's module and facet belong to the
// project's declared taxonomy. Lookup sets are built once so the returned
// predicates are O(1) per call instead of re-scanning declaredModules/
// declaredFacets for every claim in the catalog (O(claims) overall rather
// than O(claims * declared)).
//
// A module/facet is "recognized" when the project config declares a list
// and the value appears in it. When the config declares no list at all (nil
// cfg, or a config with an empty Modules/Facets — validate() normally
// forbids the latter, but this stays defensive), any non-empty value is
// accepted and grouping falls back to alphabetical order for it in
// buildGroups.
func newMembershipPredicates(declaredModules, declaredFacets []string) (knownModule, knownFacet func(string) bool) {
	declaredModuleSet := stringSet(declaredModules)
	declaredFacetSet := stringSet(declaredFacets)

	knownModule = func(m string) bool {
		if m == "" {
			return false
		}
		if len(declaredModuleSet) == 0 {
			return true
		}
		return declaredModuleSet[m]
	}
	knownFacet = func(f string) bool {
		if f == "" {
			return false
		}
		if len(declaredFacetSet) == 0 {
			return true
		}
		return declaredFacetSet[f]
	}
	return knownModule, knownFacet
}

// markFirstInModule stamps firstInModule on each group in place: true for
// the first group of a new module (including the very first group overall),
// false for subsequent groups within the same module. groups is assumed to
// already be ordered by module (as buildGroups produces it).
func markFirstInModule(groups []Group) {
	prevModule := ""
	for i := range groups {
		groups[i].firstInModule = i == 0 || groups[i].Module != prevModule
		prevModule = groups[i].Module
	}
}

// orderedNames returns every name in present (a set), ordered by its
// position in preferred first, then any remaining present names not found
// in preferred, appended in alphabetical order. It is used for both
// module ordering (against cfg.Modules) and facet ordering (against
// cfg.Facets) so unlisted-but-present names still get a stable, deterministic
// nav position instead of being dropped or ordered randomly.
//
// The "rest" branch below (names present but not in preferred) is
// intentionally kept even though it is unreachable in practice for a
// lint-clean project: the id-shape lint (internal/lint.IDShapeLint) already
// rejects any claim whose module/facet segment isn't in the project's
// configured cfg.Modules/cfg.Facets, so by the time buildGroups calls this
// function, every module/facet name it has actually seen is guaranteed to
// already be in preferred — present is always a subset of preferred. This
// is not dead code to delete: it is the deliberate fallback for callers
// that bypass that guarantee (a nil cfg, as newMembershipPredicates'
// doc comment notes some defensive paths allow; a pre-lint or malformed
// catalog; a future caller of this helper that doesn't go through the
// lint-gated flow). Do not remove it on the assumption it can never run —
// it can, just not from today's lint-clean render path.
func orderedNames(preferred []string, present map[string]bool) []string {
	if len(present) == 0 {
		return nil
	}

	used := make(map[string]bool, len(present))
	out := make([]string, 0, len(present))
	for _, p := range preferred {
		if present[p] && !used[p] {
			out = append(out, p)
			used[p] = true
		}
	}

	var rest []string
	for name := range present {
		if !used[name] {
			rest = append(rest, name)
		}
	}
	sort.Strings(rest)

	return append(out, rest...)
}

// orderClaims delegates to model.OrderClaims — see that function's doc
// comment for the full algorithm description. Kept as a thin
// package-local wrapper (rather than calling model.OrderClaims directly
// at newGroup's one call site) so this package's existing
// TestOrderClaims_* tests keep exercising the same package-local name.
func orderClaims(claims []model.Claim) []model.Claim {
	return model.OrderClaims(claims)
}

// newGroup builds one Group, pulling each claim's already-rendered HTML out
// of renderedByID (keyed by claim ID) so claims are rendered exactly once
// regardless of how many places reference them. It also injects a section
// heading (sectionHeadingHTML) ahead of the first claim of each run of
// consecutive, same-Section claims — see sectionHeadingHTML's doc comment
// for the exact detection rule. overviewHTML, if non-empty, is the calling
// module's already-rendered overview-facet claims (see renderOverviewHTML)
// and is prepended ahead of any section heading — a module-level
// orientation note isn't its own tab, so buildGroups renders it once per
// module and injects the same HTML into every one of that module's facet
// groups.
func newGroup(module, facet string, claims []model.Claim, renderedByID map[string]template.HTML, overviewHTML []template.HTML) Group {
	claims = orderClaims(claims)
	htmls := make([]template.HTML, 0, len(claims)+len(overviewHTML))
	htmls = append(htmls, overviewHTML...)
	allLocked := len(claims) > 0
	prevSection := ""
	for _, c := range claims {
		if c.Status != model.StatusLocked {
			allLocked = false
		}
		if c.Section != "" && c.Section != prevSection {
			htmls = append(htmls, sectionHeadingHTML(c.Section))
			prevSection = c.Section
		}
		htmls = append(htmls, renderedByID[c.ID])
	}

	id := module
	if facet != "" {
		id = module + "-" + facet
	}

	tabSource := facet
	if tabSource == "" {
		tabSource = module
	}

	return Group{
		Module:      module,
		Facet:       facet,
		ID:          slugify(id),
		Claims:      htmls,
		AllLocked:   allLocked,
		ModuleLabel: displayCase(module),
		TabLabel:    displayCase(tabSource),
	}
}

// sectionHeadingHTML renders a claim's optional model.Claim.Section value as
// a standalone in-content heading marker, injected by newGroup ahead of the
// first claim of each new section run within a facet's claim sequence — the
// round-3 QA finding's fix for a flat, undifferentiated card stream on a
// long document, where the sidebar/sub-nav section identity scrolls out of
// view. It is deliberately a plain, semantic heading element rather than
// reusing the reference docs stylesheet's field-level .lbl class (a close visual
// cousin — mono, uppercase, letter-spaced, muted-color label) because .lbl
// is sized/spaced to sit inside a single card as a field caption, not to
// read as a break between many cards; section-heading instead gets its own
// rule in style.css so it can carry a top border and larger vertical rhythm
// befitting a document-level section break.
func sectionHeadingHTML(section string) template.HTML {
	return template.HTML(`<h4 class="section-heading">` + template.HTMLEscapeString(section) + `</h4>`)
}

// displayCase renders a raw module/facet value (e.g. "token-ledger" or
// "token_ledger") as a human-readable nav label ("Token Ledger"): '-' and
// '_' become spaces, and each resulting word is capitalized. It is a
// display-only transform — Group.Module/Facet and Group.ID (used for
// hashes/element ids) are untouched.
func displayCase(s string) string {
	words := strings.FieldsFunc(s, func(r rune) bool {
		return r == '-' || r == '_' || r == ' '
	})
	for i, w := range words {
		if w == "" {
			continue
		}
		r := []rune(w)
		r[0] = []rune(strings.ToUpper(string(r[0])))[0]
		words[i] = string(r)
	}
	return strings.Join(words, " ")
}

// slugify lowercases s and collapses every run of characters outside
// [a-z0-9] into a single '-', trimming any leading/trailing '-'. It keeps
// Group.ID safe to use verbatim as an HTML id and a URL hash fragment
// regardless of what characters a project's module/facet names contain.
func slugify(s string) string {
	var b strings.Builder
	prevDash := false
	for _, r := range strings.ToLower(s) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			prevDash = false
		} else if !prevDash {
			b.WriteByte('-')
			prevDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

// stringSet builds a lookup set from ss for O(1) membership checks.
func stringSet(ss []string) map[string]bool {
	if len(ss) == 0 {
		return nil
	}
	set := make(map[string]bool, len(ss))
	for _, x := range ss {
		set[x] = true
	}
	return set
}
