package config

import (
	"path"
	"path/filepath"
)

// The build directory is the ONE place the engine writes at runtime, and this
// file is the ONE place a generated path is spelled. Every kind the engine
// produces — the per-module build-order and code-links artifacts, the three
// ledger stores, the catalog, the viewer, the claim-file write sentinel and the
// build directory's own .gitignore — resolves through one method below, so a
// command, the check pipeline and serve cannot disagree about where a file is.
//
// The layout under BuildDirPath():
//
//	build-order/<module>.json     the build-order artifact, per module
//	code-links/<module>.json      the implementation-link artifact, per module
//	ledger/lock-store.json        the lock ledger
//	ledger/comment-digest.json    the comment digest store
//	ledger/flag-store.json        the pending-flag store
//	ledger/claims.lock            the project-wide claim-file write sentinel
//	catalog/catalog.json          the catalog, regenerated by every check
//	viewer/index.html             the viewer, regenerated by every check
//	.gitignore                    written by check, ignores the generated kinds
//
// One derived exception must stay true: internal/digest.StorePathBeside derives
// the digest store's path from the lock store's DIRECTORY, so the lock store
// and the digest are siblings under ledger/ by construction, and
// internal/digest's tests pin StorePathBeside(LockStorePath()) == CommentDigestPath().

const (
	// LedgerDirName is the subdirectory under the build directory that holds
	// the three tracked stores and the claim-file write sentinel.
	LedgerDirName = "ledger"

	// LockStoreFileName is the lock ledger's base name. It is the name a
	// finding may match on (internal/check's index scan recognises it by base
	// name), never the path a message prints — messages print
	// LockStoreDisplayPath, because the bare name is two directories away from
	// the file.
	LockStoreFileName = "lock-store.json"
	// CommentDigestFileName is the comment digest store's base name.
	CommentDigestFileName = "comment-digest.json"
	// FlagStoreFileName is the pending-flag store's base name.
	FlagStoreFileName = "flag-store.json"

	// DefaultBuildDir is the build_dir value a config that does not set one
	// gets, resolved against the config file's own directory.
	DefaultBuildDir = "build"

	// BuildOrderDirName and CodeLinksDirName are the per-module artifact
	// subdirectories; CatalogDirName and ViewerDirName hold the two kinds
	// every check regenerates.
	BuildOrderDirName = "build-order"
	CodeLinksDirName  = "code-links"
	CatalogDirName    = "catalog"
	ViewerDirName     = "viewer"

	// claimsSentinelBaseName is the claim-file write sentinel's base path under
	// ledger/; internal/lock.AcquireFileLock appends ".lock" to it, so the file
	// on disk is ledger/claims.lock.
	claimsSentinelBaseName = "claims"

	// catalogBaseName and viewerBaseName are deliberately unexported and
	// deliberately NOT named "…FileName": tests/docs_site_audit_test.go derives
	// the set of TRACKED stores from the "…StoreFileName" declarations in this
	// file, and a catalog or viewer constant caught by that extraction would
	// make the test demand that the catalog be documented as a tracked store —
	// the opposite of what README and build/.gitignore say about it.
	catalogBaseName = "catalog.json"
	viewerBaseName  = "index.html"
)

// LockStoreDisplayPath is the lock ledger's path as a reader sees it from the
// project directory with the default build_dir, and it is what every
// user-facing message prints. It is a display form, not a path to open: a
// project with a non-default build_dir keeps its files elsewhere, and the gate
// may be reading a store materialised out of the git index. Slash-separated on
// every platform, because it is text for a human and a gitignore pathspec,
// never an argument to the filesystem.
var LockStoreDisplayPath = path.Join(DefaultBuildDir, LedgerDirName, LockStoreFileName)

// CommentDigestDisplayPath is the comment digest store's display form.
var CommentDigestDisplayPath = path.Join(DefaultBuildDir, LedgerDirName, CommentDigestFileName)

// FlagStoreDisplayPath is the pending-flag store's display form.
var FlagStoreDisplayPath = path.Join(DefaultBuildDir, LedgerDirName, FlagStoreFileName)

// TrackedStoreFileNames is the list of store base names the engine writes
// under ledger/ that a consuming project must COMMIT. It is the list
// tests/docs_site_audit_test.go reads to demand that every enumeration of "the
// files you must commit" (README, FORMAT, the CI template, the hook
// installer) names each one, so a fourth store cannot ship undocumented; the
// same test cross-checks it against the "…StoreFileName" declarations above,
// so an author who forgets this slice is caught too. The catalog and the
// viewer are regenerated by every check and are not in it.
var TrackedStoreFileNames = []string{LockStoreFileName, CommentDigestFileName, FlagStoreFileName}

// BuildDirPath is the resolved, absolute build directory: build_dir from the
// config, resolved against the config file's own directory exactly as
// claims_dir is (never against the process cwd), defaulting to "build".
func (c *Config) BuildDirPath() string { return c.BuildDir }

// BuildOrderPath is module's build-order artifact: <build>/build-order/<module>.json.
func (c *Config) BuildOrderPath(module string) string {
	return filepath.Join(c.BuildDir, BuildOrderDirName, module+".json")
}

// CodeLinksPath is module's implementation-link artifact: <build>/code-links/<module>.json.
func (c *Config) CodeLinksPath(module string) string {
	return filepath.Join(c.BuildDir, CodeLinksDirName, module+".json")
}

// LockStorePath is the lock ledger: <build>/ledger/lock-store.json.
func (c *Config) LockStorePath() string {
	return filepath.Join(c.BuildDir, LedgerDirName, LockStoreFileName)
}

// CommentDigestPath is the comment digest store: <build>/ledger/comment-digest.json.
func (c *Config) CommentDigestPath() string {
	return filepath.Join(c.BuildDir, LedgerDirName, CommentDigestFileName)
}

// FlagStorePath is the pending-flag store: <build>/ledger/flag-store.json.
func (c *Config) FlagStorePath() string {
	return filepath.Join(c.BuildDir, LedgerDirName, FlagStoreFileName)
}

// CatalogPath is the catalog check writes: <build>/catalog/catalog.json.
func (c *Config) CatalogPath() string {
	return filepath.Join(c.BuildDir, CatalogDirName, catalogBaseName)
}

// ViewerPath is the viewer check writes: <build>/viewer/index.html.
func (c *Config) ViewerPath() string {
	return filepath.Join(c.BuildDir, ViewerDirName, viewerBaseName)
}

// ClaimsSentinelPath is the BASE path of the project-wide claim-file write
// sentinel, <build>/ledger/claims; internal/lock.AcquireFileLock appends
// ".lock", so the file on disk is <build>/ledger/claims.lock. It lives under the
// build directory — which config guarantees is outside claims_dir — so it is
// never decoded as a claim and never trips a claims_dir watcher.
func (c *Config) ClaimsSentinelPath() string {
	return filepath.Join(c.BuildDir, LedgerDirName, claimsSentinelBaseName)
}

// BuildGitignorePath is the build directory's own .gitignore, which check
// writes once (see internal/layout.EnsureBuildGitignore) so the generated kinds
// under it are ignored and the tracked kinds are not.
func (c *Config) BuildGitignorePath() string {
	return filepath.Join(c.BuildDir, ".gitignore")
}
